begin;
create extension if not exists pgtap with schema extensions;
set local search_path=public,extensions;
select no_plan();
insert into auth.users(id,email) values ('b2000000-0000-4000-8000-000000000021','pilot-operator@elifora.test'),('b2000000-0000-4000-8000-000000000022','pilot-member@elifora.test');
insert into public.organizations(id,name,slug,base_currency) values ('b2000000-0000-4000-8000-000000000002','Pilot test salon','pilot-test','TRY');
insert into public.locations(id,organization_id,name,timezone) values ('b2000000-0000-4000-8000-000000000012','b2000000-0000-4000-8000-000000000002','Test','Europe/Istanbul');
insert into public.salon_memberships(id,organization_id,location_id,user_id,role_code,status,joined_at) values ('b2000000-0000-4000-8000-000000000112','b2000000-0000-4000-8000-000000000002','b2000000-0000-4000-8000-000000000012','b2000000-0000-4000-8000-000000000022','owner','active',now());
insert into app_private.catalog_operators(user_id) values ('b2000000-0000-4000-8000-000000000021');
select set_config('request.jwt.claim.sub','b2000000-0000-4000-8000-000000000021',true);
create temporary table pilot_ids(id uuid);
insert into pilot_ids select (public.catalog_governance('IMPORT',null,'Test-only development extraction review',gen_random_uuid())->>'catalogId')::uuid;
grant select on pilot_ids to authenticated;
select is((select state from public.brand_catalog_releases where id=(select id from pilot_ids)),'DRAFT','official manifest imports only a draft');
select is((select count(*) from public.catalog_products where product_type='SHADE'),29::bigint,'only 29 documented occupied shade cells imported');
select is((select count(*) from public.catalog_products where product_type='DEVELOPER'),2::bigint,'only two documented developers imported');
select is((select count(*) from public.catalog_sources),3::bigint,'three hashed manufacturer documents registered');
select is((select count(*) from public.catalog_sources where verification_status='UNVERIFIED'),3::bigint,'no automatic source verification');
select is((select count(*) from public.catalog_compatibility_rules),58::bigint,'exact shade developer combinations recorded');
select is((select count(*) from public.catalog_compatibility_rules where outcome='UNKNOWN'),58::bigint,'compatibility unverified before review');
select is((select count(*) from public.catalog_technical_facts where source='UNKNOWN' and value is not null),0::bigint,'no numerical pigment or exact time invented');
select is((select count(*) from public.catalog_product_evidence where manufacturer_level=8 and manufacturer_tone='01'),1::bigint,'natural notation preserved');
select throws_ok($$select public.brand_catalog_transition((select id from pilot_ids),'PUBLISHED',null,gen_random_uuid())$$,'23514','CATALOG_STATE_CONFLICT','cannot publish draft directly');
select public.catalog_governance('START_REVIEW',(select id from pilot_ids),'Test-only review started',gen_random_uuid());
select throws_ok($$select public.brand_catalog_transition((select id from pilot_ids),'GOLDEN_TEST',null,gen_random_uuid())$$,'23514','SOURCE_REVIEW_REQUIRED','legacy RPC cannot bypass official source review');
select throws_ok($$update public.catalog_sources set source_url='https://reseller.example/guide'$$,'23514','SOURCE_REPLACEMENT_REQUIRES_NEW_VERSION','official source URL immutable; replacement requires new version');
select public.catalog_governance('COMPLETE_REVIEW',(select id from pilot_ids),'Test-only source extraction checked; numeric channels remain UNKNOWN',gen_random_uuid());
select is((select count(*) from public.catalog_sources where review_status='APPROVED'),3::bigint,'review records approved sources');
select is((select count(*) from public.catalog_products where verification_status='ELIFORA_VERIFIED'),31::bigint,'review verifies product identity, not fabricated chemistry');
select is((select count(*) from public.catalog_compatibility_rules where outcome='VERIFIED_RESTRICTED'),58::bigint,'manufacturer contexts remain restricted');
select is((select reviewed_by from public.brand_catalog_releases where id=(select id from pilot_ids)),auth.uid(),'reviewer recorded separately');
select throws_ok($$select public.catalog_governance('APPROVE',(select id from pilot_ids),'No golden run',gen_random_uuid())$$,'23514','GOLDEN_RECEIPT_REQUIRED','approval requires actual validation receipt');
select public.catalog_governance('VALIDATE_GOLDEN',(select id from pilot_ids),'Source-backed golden validation',gen_random_uuid());
select is((select passed_count from public.catalog_golden_runs),10,'ten persisted validation groups executed');
select throws_ok($$update public.catalog_golden_runs set passed_count=0$$,'23514','IMMUTABLE_CATALOG_AUDIT','golden validation record immutable');
select public.catalog_governance('APPROVE',(select id from pilot_ids),'Test-only approval',gen_random_uuid());
select public.catalog_governance('PUBLISH',(select id from pilot_ids),'Test-only publication in disposable DB',gen_random_uuid());
select is((select state from public.brand_catalog_releases where id=(select id from pilot_ids)),'PUBLISHED','ordered workflow publishes');
select is((select approved_by from public.brand_catalog_releases where id=(select id from pilot_ids)),auth.uid(),'approval actor recorded');
select is((select published_by from public.brand_catalog_releases where id=(select id from pilot_ids)),auth.uid(),'publication actor recorded');
select throws_ok($$update public.catalog_sources set document_title='silent change'$$,'23514','IMMUTABLE_CATALOG_CONTENT','published source immutable');
select throws_ok($$update public.catalog_product_evidence set manufacturer_level=1$$,'23514','IMMUTABLE_CATALOG_CONTENT','published mapping immutable');
select throws_ok($$delete from public.catalog_fact_sources$$,'23514','IMMUTABLE_CATALOG_CONTENT','provenance cannot be deleted');
create temporary table pilot_history as select public.catalog_pilot_packet((select id from pilot_ids)) as packet;
set local role authenticated;
select ok(public.catalog_operator_access(),'operator access resolved from private database assignment');
select throws_ok($$update public.catalog_sources set verification_status='ELIFORA_VERIFIED'$$,'42501',null,'operator still cannot directly write exposed source table');
select set_config('request.jwt.claim.sub','b2000000-0000-4000-8000-000000000022',true);
select ok(not public.catalog_operator_access(),'salon owner is not global operator');
select is((select count(*) from public.catalog_sources),3::bigint,'active intended member can read published source provenance');
select throws_ok($$select public.catalog_governance('RETIRE',(select id from pilot_ids),'forged',gen_random_uuid())$$,'42501','FORBIDDEN','salon owner cannot retire global catalog');
select throws_ok($$select app_private.pilot_golden_validate((select id from pilot_ids))$$,'42501','FORBIDDEN','direct private golden call still requires operator');
select throws_ok($$insert into public.catalog_sources default values$$,'42501',null,'client cannot forge an official source');
select throws_ok($$insert into public.catalog_golden_runs default values$$,'42501',null,'client cannot forge passing golden receipt');
reset role;
update public.salon_memberships set status='revoked',revoked_at=now() where user_id='b2000000-0000-4000-8000-000000000022';
set local role authenticated;
select is((select count(*) from public.catalog_sources),0::bigint,'revocation removes source access');
reset role;
set local role anon;
select throws_ok($$select * from public.catalog_sources$$,'42501',null,'anonymous source read denied');
select throws_ok($$select public.catalog_governance('IMPORT',null,'forged',gen_random_uuid())$$,'42501',null,'anonymous governance denied');
reset role;
select set_config('request.jwt.claim.sub','b2000000-0000-4000-8000-000000000021',true);
create temporary table pilot_next(id uuid);
insert into pilot_next select (public.catalog_governance('IMPORT',null,'Source replacement opens new review',gen_random_uuid(),(select id from pilot_ids))->>'catalogId')::uuid;
select is((select state from public.brand_catalog_releases where id=(select id from pilot_next)),'DRAFT','replacement creates a new draft cycle');
select is(public.catalog_pilot_packet((select id from pilot_ids)),(select packet from pilot_history),'historical packet remains byte-for-byte unchanged');
select is((select count(*) from public.catalog_products where version=2),31::bigint,'product V2 preserves lineage');
select public.catalog_governance('REJECT',(select id from pilot_next),'Test-only rejection',gen_random_uuid());
select is((select state from public.brand_catalog_releases where id=(select id from pilot_next)),'REJECTED','rejected review is a terminal recorded state');
select throws_ok($$select public.catalog_governance('PUBLISH',(select id from pilot_next),'forged',gen_random_uuid())$$,'23514','CATALOG_STATE_CONFLICT','rejected catalog cannot publish');
select ok((select count(*) from public.brand_catalog_audit where action='source.replaced')=1,'source replacement audited');
select ok((select count(*) from public.brand_catalog_audit where action='governance.complete_review' and decision_note is not null)=1,'review decision note persisted');
select throws_ok($$update public.brand_catalog_audit set decision_note='rewrite'$$,'23514','IMMUTABLE_CATALOG_AUDIT','decision audit immutable');
select * from finish();
rollback;
