import type { z } from "zod";
import { createLiveRequest,liveSession,terminal,type LiveSession,type LiveCommand,permissionFor } from "./model";
import type { storedControlledRecipe } from "@/lib/brand/controlled-model";
export class LiveError extends Error{constructor(public code:string,public status=409){super(code);}}
type Recipe=z.infer<typeof storedControlledRecipe>;
export type Authority={actorId:string;now:string;permissions:string[];id:()=>string;recipe?:Recipe;target?:LiveSession["targetSnapshot"];sourceToken?:string;passportId?:string;risk?:LiveSession["riskSnapshot"];transferAllowed?:boolean;photoPath?:string};
function fail(code="LIVE_SESSION_TRANSITION_INVALID"):never{throw new LiveError(code);}
export function timerElapsed(t:LiveSession["timers"][number],now:number){return t.elapsedSeconds+(t.status==="RUNNING"&&t.anchorAt?Math.max(0,(now-Date.parse(t.anchorAt))/1000):0);}
export function createSession(raw:z.infer<typeof createLiveRequest>,a:Authority,locationId:string,passportId:string):LiveSession{
 if(!a.recipe||!a.sourceToken||!a.risk||!a.target)fail("SESSION_START_BLOCKED_STALE_INPUT");
 if(!a.permissions.includes("live_session.start"))throw new LiveError("FORBIDDEN",403);
 const recipe=a.recipe,sessionId=a.id(),bowlId=a.id(),stepId=a.id();
 return liveSession.parse({schemaVersion:1,id:sessionId,clientId:raw.client_id,locationId,passportId,colorCaseLink:raw.color_case_link,appointmentLink:raw.appointment_link,
 status:"PREPARING",recordVersion:1,controllerUserId:a.actorId,controllerDeviceId:raw.device_id,controlEpoch:1,startedBy:a.actorId,createdAt:a.now,updatedAt:a.now,startedAt:null,pausedAt:null,completedAt:null,cancelledAt:null,
 originalRecipeId:recipe.id,currentRecipeId:recipe.id,recipes:[recipe],targetSnapshot:a.target,review:{by:a.actorId,at:a.now,note:raw.review_note},sourceToken:a.sourceToken,riskSnapshot:a.risk,
 steps:[{id:stepId,sequenceIndex:0,regionId:recipe.result.context.regionId,bowlId,instructionType:"APPLICATION",instructionText:"Onaylı dip yenileme reçetesi. Ayrıntılı uygulama sırasını profesyonel belirler.",createdFrom:"VERIFIED_RECIPE",professionalModified:false,status:"PENDING",actualStart:null,actualFinish:null}],
 bowls:[{id:bowlId,label:"Kap A · Dip",recipeId:recipe.id,regionIds:[recipe.result.context.regionId],plannedGrams:recipe.result.totalGrams,preparedGrams:null,usedGrams:null,wasteGrams:null,closed:false}],timers:[],
 checkpoints:[{id:a.id(),type:"HAIR_INTEGRITY_CHECK",stepId,required:true,result:"PENDING",note:"",completedBy:null,completedAt:null}],usage:[],deviations:[],riskEvents:[],photos:[],notes:[],outcome:null,actualProcessSeconds:null});
}
export function applyCommand(current:LiveSession,c:LiveCommand,a:Authority):LiveSession{
 if(!a.permissions.includes(permissionFor(c.type)))throw new LiveError("FORBIDDEN",403);
 if(c.expected_version!==current.recordVersion||c.control_epoch!==current.controlEpoch)fail("LIVE_SESSION_CONFLICT");
 const contribution=["NOTE","PHOTO","CHECKPOINT_RECORD","RISK_EVENT","USAGE","MATERIAL_RECONCILE"].includes(c.type);
 if(!contribution&&(current.controllerUserId!==a.actorId||current.controllerDeviceId!==c.device_id))fail("LIVE_CONTROLLER_CONFLICT");
 if(terminal(current.status)&&c.type!=="MATERIAL_RECONCILE")fail("LIVE_SESSION_IMMUTABLE");
 const s=structuredClone(current),now=Date.parse(a.now);
 const states=(...allowed:string[])=>{if(!allowed.includes(s.status))fail();};
 const deviation=(type:LiveSession["deviations"][number]["type"],reason:string,before:unknown,after:unknown)=>s.deviations.push({id:a.id(),type,reason,changedBy:a.actorId,at:a.now,before,after});
 const refresh=()=>{if(!a.recipe||!a.risk||!a.sourceToken||a.recipe.id!==s.currentRecipeId)fail("SESSION_START_BLOCKED_STALE_INPUT");s.sourceToken=a.sourceToken;s.riskSnapshot=a.risk;};
 const unresolved=()=>s.riskEvents.some(e=>!e.resolvedAt);
 switch(c.type){
 case "READY":states("PREPARING");if(!s.steps.length||s.steps.some(st=>!st.instructionText.trim()))fail();s.status="READY";break;
 case "START":states("READY");refresh();s.status="IN_PROGRESS";s.startedAt=a.now;break;
 case "PAUSE":states("IN_PROGRESS","CHECKPOINT_REQUIRED");s.status="PAUSED";s.pausedAt=a.now;break;
 case "RESUME":states("PAUSED","CHECKPOINT_REQUIRED");if(unresolved()||s.checkpoints.some(cp=>cp.result==="FAIL"||cp.result==="CONCERN"))fail("LIVE_CHECKPOINT_REQUIRED");refresh();s.status="IN_PROGRESS";s.pausedAt=null;break;
 case "TRANSFER_CONTROL":if(!a.transferAllowed)throw new LiveError("FORBIDDEN",403);deviation("PROFESSIONAL_DECISION",c.reason,{user:s.controllerUserId,device:s.controllerDeviceId},{user:c.user_id,device:c.target_device_id});s.controllerUserId=c.user_id;s.controllerDeviceId=c.target_device_id;s.controlEpoch++;break;
 case "STEP_START":{states("IN_PROGRESS");const st=s.steps.find(x=>x.id===c.step_id),b=s.bowls.find(x=>x.id===st?.bowlId);if(st?.status==="SUPERSEDED"||b&&b.recipeId!==s.currentRecipeId)fail("SESSION_START_BLOCKED_STALE_INPUT");refresh();if(unresolved())fail("LIVE_CHECKPOINT_REQUIRED");if(!st||st.status!=="PENDING"||!b||b.closed||s.steps.some(x=>x.sequenceIndex<st.sequenceIndex&&!["COMPLETED","SUPERSEDED"].includes(x.status))||s.checkpoints.some(cp=>cp.required&&cp.result!=="PASS"&&s.steps.find(x=>x.id===cp.stepId)!.status!=="SUPERSEDED"&&s.steps.find(x=>x.id===cp.stepId)!.sequenceIndex<st.sequenceIndex))fail("LIVE_CHECKPOINT_REQUIRED");st.status="IN_PROGRESS";st.actualStart=a.now;break;}
 case "STEP_COMPLETE":{states("IN_PROGRESS","CHECKPOINT_REQUIRED");const st=s.steps.find(x=>x.id===c.step_id);if(!st||st.status!=="IN_PROGRESS"||s.checkpoints.some(cp=>cp.stepId===st.id&&cp.required&&cp.result!=="PASS"))fail("LIVE_CHECKPOINT_REQUIRED");st.status="COMPLETED";st.actualFinish=a.now;s.status=unresolved()?"CHECKPOINT_REQUIRED":"IN_PROGRESS";break;}
 case "SEQUENCE":{states("PREPARING","READY","PAUSED");const old=s.steps;const historical=old.filter(st=>st.status!=="PENDING"),base=Math.max(-1,...historical.map(st=>st.sequenceIndex))+1;const next=c.steps.map((st,i)=>{const previous=old.find(x=>x.id===st.id),bowl=s.bowls.find(b=>b.id===st.bowl_id);if(!bowl||bowl.closed||bowl.recipeId!==s.currentRecipeId||!bowl.regionIds.includes(st.region_id)||previous&&previous.status!=="PENDING")fail("SESSION_START_BLOCKED_STALE_INPUT");return {id:st.id,sequenceIndex:base+i,regionId:st.region_id,bowlId:st.bowl_id,instructionType:st.instruction_type,instructionText:st.instruction_text,createdFrom:"PROFESSIONAL_INPUT" as const,professionalModified:true,status:"PENDING" as const,actualStart:null,actualFinish:null};});if(new Set(next.map(st=>st.id)).size!==next.length||s.checkpoints.some(cp=>!historical.some(st=>st.id===cp.stepId)&&!next.some(st=>st.id===cp.stepId)))fail();s.steps=[...historical,...next];deviation("SEQUENCE_CHANGED",c.reason,old,s.steps);break;}

 case "BOWL_ADD":{states("PREPARING","READY","PAUSED");const recipe=s.recipes.find(r=>r.id===s.currentRecipeId)!;if(c.region_id!==recipe.result.context.regionId)fail("LIVE_REGION_UNSUPPORTED");s.bowls.push({id:a.id(),label:c.label,recipeId:recipe.id,regionIds:[c.region_id],plannedGrams:c.planned_grams,preparedGrams:null,usedGrams:null,wasteGrams:null,closed:false});deviation("GRAM_CHANGED",c.reason,null,s.bowls.at(-1));break;}
 case "USAGE":{states("IN_PROGRESS","PAUSED","CHECKPOINT_REQUIRED");const b=s.bowls.find(b=>b.id===c.bowl_id);if(!b||b.closed||c.used_grams>c.prepared_grams||Math.round(c.prepared_grams*100)%2||Math.round(c.used_grams*100)%2)fail("LIVE_USAGE_INVALID");b.preparedGrams=c.prepared_grams;b.usedGrams=c.used_grams;b.wasteGrams=(Math.round(c.prepared_grams*100)-Math.round(c.used_grams*100))/100;b.closed=true;
 const r=s.recipes.find(r=>r.id===b.recipeId)!;for(const [productId,productVersion] of [[r.result.selected.productId,r.result.snapshots.productVersion],[r.result.selected.developerId,r.result.snapshots.developerVersion]] as const)s.usage.push({id:a.id(),bowlId:b.id,recipeId:r.id,productId,productVersion,preparedGrams:b.preparedGrams/2,usedGrams:b.usedGrams/2,wasteGrams:b.wasteGrams/2,recordedBy:a.actorId,recordedAt:a.now});deviation("GRAM_CHANGED",c.reason,{plannedGrams:b.plannedGrams},{preparedGrams:b.preparedGrams,usedGrams:b.usedGrams,wasteGrams:b.wasteGrams});break;}
 case "TIMER_ADD":{states("IN_PROGRESS","CHECKPOINT_REQUIRED");const region=c.region_id;if(c.step_id&&!s.steps.some(st=>st.id===c.step_id)||region&&!s.bowls.some(b=>b.regionIds.includes(region)))fail();s.timers.push({id:a.id(),label:c.label,stepId:c.step_id,regionId:c.region_id,plannedDuration:c.duration_seconds,startedAt:a.now,anchorAt:a.now,elapsedSeconds:0,status:"RUNNING"});break;}
 case "TIMER_ACTION":{const t=s.timers.find(t=>t.id===c.timer_id);if(!t||["COMPLETED","CANCELLED"].includes(t.status))fail();if(c.action==="RESUME"){states("IN_PROGRESS","CHECKPOINT_REQUIRED");if(t.status!=="PAUSED")fail();t.status="RUNNING";t.anchorAt=a.now;}else{if(c.action==="PAUSE"&&t.status!=="RUNNING")fail();t.elapsedSeconds=timerElapsed(t,now);t.anchorAt=null;t.status=c.action==="PAUSE"?"PAUSED":c.action==="COMPLETE"?"COMPLETED":"CANCELLED";}deviation("TIME_CHANGED",`Timer ${c.action}`,current.timers.find(t=>t.id===c.timer_id),t);break;}
 case "CHECKPOINT_ADD":{if(!s.steps.some(st=>st.id===c.step_id)||s.status==="COMPLETION_REVIEW")fail();s.checkpoints.push({id:a.id(),type:c.checkpoint_type,stepId:c.step_id,required:c.required,result:"PENDING",note:"",completedBy:null,completedAt:null});break;}
 case "CHECKPOINT_RECORD":{states("IN_PROGRESS","CHECKPOINT_REQUIRED","PAUSED");const cp=s.checkpoints.find(cp=>cp.id===c.checkpoint_id);if(!cp||cp.result!=="PENDING")fail();cp.result=c.result;cp.note=c.note;cp.completedAt=a.now;cp.completedBy=a.actorId;if(c.result!=="PASS"){s.status="PAUSED";s.pausedAt=a.now;deviation("CHECKPOINT_FAILED",c.note,"PENDING",c.result);}break;}
 case "RISK_EVENT":{states("IN_PROGRESS","PAUSED","CHECKPOINT_REQUIRED");const action=["UNEXPECTED_BREAKAGE","SCALP_CONCERN"].includes(c.event_type)?"STOP":c.event_type==="ELASTICITY_CONCERN"?"PAUSE":"REASSESS";s.riskEvents.push({id:a.id(),type:c.event_type,note:c.note,action,recordedBy:a.actorId,at:a.now,resolvedAt:null});s.status=action==="STOP"?"ABORTED":action==="PAUSE"?"PAUSED":"CHECKPOINT_REQUIRED";s.pausedAt=a.now;break;}
 case "REASSESS":states("PAUSED","CHECKPOINT_REQUIRED");refresh();if(s.checkpoints.some(cp=>cp.result!=="PASS"&&cp.required))fail("LIVE_CHECKPOINT_REQUIRED");s.riskEvents.forEach(e=>{if(!e.resolvedAt)e.resolvedAt=a.now;});deviation("PROFESSIONAL_DECISION",c.reason,"REASSESS",s.riskSnapshot);s.status="PAUSED";break;
 case "NOTE":if(s.status==="COMPLETION_REVIEW")fail();s.notes.push({id:a.id(),text:c.text,by:a.actorId,at:a.now});break;
 case "DEVIATION":if(["PRODUCT_CHANGED","REGION_CHANGED","SEQUENCE_CHANGED","TIME_CHANGED","GRAM_CHANGED"].includes(c.deviation_type))fail("LIVE_USE_STRUCTURED_COMMAND");deviation(c.deviation_type,c.reason,null,null);break;
 case "RECIPE_REVISION":{states("PREPARING","READY","PAUSED");if(!a.recipe||!a.sourceToken||!a.risk||!a.target||a.recipe.id===s.currentRecipeId||s.recipes.some(r=>r.id===a.recipe!.id))fail("SESSION_START_BLOCKED_STALE_INPUT");const before=s.currentRecipeId;s.recipes.push(a.recipe);s.currentRecipeId=a.recipe.id;s.review={by:a.actorId,at:a.now,note:c.review_note};s.sourceToken=a.sourceToken;s.riskSnapshot=a.risk;s.targetSnapshot=a.target;
 for(const step of s.steps)if(step.status==="PENDING")step.status="SUPERSEDED";
 const bowlId=a.id(),stepId=a.id(),region=a.recipe.result.context.regionId;
 s.bowls.push({id:bowlId,label:"Revize kap · Dip",recipeId:a.recipe.id,regionIds:[region],plannedGrams:a.recipe.result.totalGrams,preparedGrams:null,usedGrams:null,wasteGrams:null,closed:false});
 s.steps.push({id:stepId,sequenceIndex:Math.max(-1,...s.steps.map(st=>st.sequenceIndex))+1,regionId:region,bowlId,instructionType:"APPLICATION",instructionText:"Revize onaylı dip reçetesi; profesyonel uygulama planını kontrol edin.",createdFrom:"VERIFIED_RECIPE",professionalModified:false,status:"PENDING",actualStart:null,actualFinish:null});
 s.checkpoints.push({id:a.id(),type:"HAIR_INTEGRITY_CHECK",stepId,required:true,result:"PENDING",note:"",completedBy:null,completedAt:null});
 deviation("PRODUCT_CHANGED",c.reason,before,a.recipe.id);break;}
 case "MATERIAL_RECONCILE":{if(!terminal(s.status))fail();const b=s.bowls.find(b=>b.id===c.bowl_id);if(!b)fail("LIVE_USAGE_INVALID");const events=s.materialReconciliations??[],last=events.filter(e=>e.bowlId===b.id).at(-1);if((last?.id??null)!==c.supersedes_id)fail("LIVE_SESSION_CONFLICT");const p=c.prepared_grams,u=c.used_grams,w=c.waste_grams;if([p,u,w].some(v=>v!==null&&Math.round(v*100)%2!==0)||p!==null&&u!==null&&u>p||p!==null&&w!==null&&w>p||p!==null&&u!==null&&w!==null&&Math.round(p*100)!==Math.round(u*100)+Math.round(w*100))fail("LIVE_USAGE_INVALID");s.materialReconciliations=[...events,{id:a.id(),mutationId:c.mutation_id,bowlId:b.id,recipeId:b.recipeId,supersedesId:c.supersedes_id,preparedGrams:p,usedGrams:u,wasteGrams:w,reason:c.reason,recordedBy:a.actorId,recordedAt:a.now}];break;}
 case "PHOTO":if(!a.photoPath||s.photos.some(p=>p.id===c.photo_id))fail();s.photos.push({id:c.photo_id,kind:c.kind,path:a.photoPath,contentType:c.content_type,uploadedBy:a.actorId,createdAt:a.now});break;
 case "COMPLETION_REVIEW":states("IN_PROGRESS","PAUSED");if(unresolved()||s.steps.some(st=>!["COMPLETED","SUPERSEDED"].includes(st.status))||s.checkpoints.some(cp=>cp.required&&cp.result!=="PASS"&&s.steps.find(st=>st.id===cp.stepId)?.status!=="SUPERSEDED")||s.timers.some(t=>!["COMPLETED","CANCELLED"].includes(t.status))||s.bowls.some(b=>!b.closed&&s.steps.some(st=>st.bowlId===b.id&&st.status!=="SUPERSEDED")))fail("LIVE_COMPLETION_INCOMPLETE");{const regions=[...new Set(s.bowls.filter(b=>(b.usedGrams??0)>0||s.steps.some(st=>st.bowlId===b.id&&st.status!=="SUPERSEDED")).flatMap(b=>b.regionIds))];if(c.outcome.regionalResults.length!==regions.length||new Set(c.outcome.regionalResults.map(r=>r.regionId)).size!==regions.length||regions.some(r=>!c.outcome.regionalResults.some(x=>x.regionId===r)))fail("LIVE_COMPLETION_INCOMPLETE");}s.outcome=c.outcome;s.status="COMPLETION_REVIEW";break;
 case "COMPLETE":states("COMPLETION_REVIEW");if(!s.outcome||!s.startedAt)fail("LIVE_COMPLETION_INCOMPLETE");s.status="COMPLETED";s.completedAt=a.now;s.actualProcessSeconds=Math.max(0,(now-Date.parse(s.startedAt))/1000);break;
 case "CANCEL":case "ABORT":s.status=c.type==="CANCEL"?"CANCELLED":"ABORTED";s.cancelledAt=a.now;deviation("PROFESSIONAL_DECISION",c.reason,current.status,s.status);break;
 }
 if(terminal(s.status))for(const t of s.timers){if(t.status==="RUNNING"||t.status==="PAUSED"){t.elapsedSeconds=timerElapsed(t,now);t.anchorAt=null;t.status="CANCELLED";}}
 s.recordVersion++;s.updatedAt=a.now;return liveSession.parse(s);
}
