import { expect,it } from "vitest";
import { liveFixture } from "@/test/live-fixtures";
import { fixtureId } from "@/test/confidence-fixtures";
import { applyCommand } from "./engine";
import { createLiveRequest,liveCommand } from "./model";
import { colorHash } from "@/lib/color/engine";
import { draftable,reconcileDraft } from "./offline";
function fixture(){const f=liveFixture();let s=f.s,n=9000;const act=(raw:Record<string,unknown>)=>s=applyCommand(s,liveCommand.parse({mutation_id:fixtureId(n++),device_id:f.q.device_id,expected_version:s.recordVersion,control_epoch:s.controlEpoch,...raw}),f.a);return {f,act,get:()=>s,start:()=>{act({type:"READY"});act({type:"START"});},revise:()=>{f.a.recipe={...f.a.recipe!,id:fixtureId(888),version:2,supersedesId:s.currentRecipeId};act({type:"RECIPE_REVISION",recipe_id:fixtureId(888),professional_review:true,review_note:"Reviewed revision",reason:"Technical change"});}};}
it("revision supersedes old pending execution and projects reviewed new units",()=>{const x=fixture(),old=x.get().steps[0]!;x.revise();expect(x.get().steps[0]!.status).toBe("SUPERSEDED");x.start();expect(()=>x.act({type:"STEP_START",step_id:old.id})).toThrow("SESSION_START_BLOCKED_STALE_INPUT");x.act({type:"STEP_START",step_id:x.get().steps[1]!.id});expect(x.get().steps[1]!.status).toBe("IN_PROGRESS");});
it("revision preserves executed old work and usage exactly",()=>{const x=fixture();x.start();x.act({type:"STEP_START",step_id:x.get().steps[0]!.id});x.act({type:"CHECKPOINT_RECORD",checkpoint_id:x.get().checkpoints[0]!.id,result:"PASS",note:"Checked"});x.act({type:"STEP_COMPLETE",step_id:x.get().steps[0]!.id});x.act({type:"USAGE",bowl_id:x.get().bowls[0]!.id,prepared_grams:60,used_grams:20,reason:"Measured"});const step=structuredClone(x.get().steps[0]),usage=structuredClone(x.get().usage);x.act({type:"PAUSE"});x.revise();expect(x.get().steps[0]).toEqual(step);expect(x.get().usage).toEqual(usage);});
it("step start requires fresh technical and catalog authority",()=>{const x=fixture();x.start();x.f.a.recipe=undefined;expect(()=>x.act({type:"STEP_START",step_id:x.get().steps[0]!.id})).toThrow("SESSION_START_BLOCKED_STALE_INPUT");});
it("regional revision updates target and new pending region without rewriting old geometry",()=>{const x=fixture(),old=x.get().steps[0]!.regionId;x.f.a.target=structuredClone(x.f.a.target!);x.f.a.target.definition.regions[0]!.level=7;x.f.a.recipe={...x.f.a.recipe!,id:fixtureId(888),result:{...x.f.a.recipe!.result,context:{...x.f.a.recipe!.result.context,regionId:fixtureId(777)}}};x.act({type:"RECIPE_REVISION",recipe_id:fixtureId(888),professional_review:true,review_note:"New regional review",reason:"Target changed"});expect(x.get().targetSnapshot.definition.regions[0]!.level).toBe(7);expect(x.get().steps[0]!.regionId).toBe(old);expect(x.get().steps[1]!.regionId).toBe(fixtureId(777));});
it.each(["ABORT","CANCEL"])("%s permits accounting but never restarts application",type=>{const x=fixture();x.start();x.act({type,reason:"Stop"});const before=structuredClone(x.get());x.act({type:"MATERIAL_RECONCILE",bowl_id:before.bowls[0]!.id,supersedes_id:null,prepared_grams:60,used_grams:20,waste_grams:40,reason:"Late measured actual"});expect(x.get().status).toBe(before.status);expect(x.get().steps).toEqual(before.steps);expect(x.get().usage).toEqual(before.usage);expect(x.get().materialReconciliations![0]).toMatchObject({preparedGrams:60,usedGrams:20,wasteGrams:40,recordedBy:x.f.a.actorId});expect(()=>x.act({type:"STEP_START",step_id:before.steps[0]!.id})).toThrow("LIVE_SESSION_IMMUTABLE");});
it("unknown material is null and measured zero remains zero",()=>{const x=fixture();x.act({type:"CANCEL",reason:"Cancelled before starting"});x.act({type:"MATERIAL_RECONCILE",bowl_id:x.get().bowls[0]!.id,supersedes_id:null,prepared_grams:null,used_grams:0,waste_grams:null,reason:"Use confirmed zero, preparation unknown"});expect(x.get().materialReconciliations![0]).toMatchObject({preparedGrams:null,usedGrams:0,wasteGrams:null});});
it("correction appends a new event and requires the current event id",()=>{const x=fixture();x.act({type:"ABORT",reason:"Stopped"});const command={type:"MATERIAL_RECONCILE",bowl_id:x.get().bowls[0]!.id,supersedes_id:null,prepared_grams:null,used_grams:null,waste_grams:null,reason:"Unknown"};x.act(command);const first=structuredClone(x.get().materialReconciliations![0]!);expect(()=>x.act(command)).toThrow("LIVE_SESSION_CONFLICT");x.act({...command,supersedes_id:first.id,prepared_grams:60,used_grams:20,waste_grams:40,reason:"Measured later"});expect(x.get().materialReconciliations).toHaveLength(2);expect(x.get().materialReconciliations![0]).toEqual(first);});
it("active sessions reject post-stop reconciliation",()=>{const x=fixture();expect(()=>x.act({type:"MATERIAL_RECONCILE",bowl_id:x.get().bowls[0]!.id,supersedes_id:null,prepared_grams:null,used_grams:null,waste_grams:null,reason:"Invalid"})).toThrow("LIVE_SESSION_TRANSITION_INVALID");});
it("invalid material conservation cannot be stored",()=>{const x=fixture();x.act({type:"ABORT",reason:"Stop"});expect(()=>x.act({type:"MATERIAL_RECONCILE",bowl_id:x.get().bowls[0]!.id,supersedes_id:null,prepared_grams:60,used_grams:20,waste_grams:50,reason:"Bad sum"})).toThrow("LIVE_USAGE_INVALID");});
it("historical payload hash does not gain default reconciliation fields",()=>{const f=liveFixture();expect(f.s.materialReconciliations).toBeUndefined();expect(colorHash(f.s)).toBe(colorHash(JSON.parse(JSON.stringify(f.s))));});
it("new sessions reject any legacy appointment UUID",()=>{const f=liveFixture();expect(createLiveRequest.safeParse({...f.q,appointment_link:fixtureId(987)}).success).toBe(false);});
it("delayed reconciliation is draftable and version conflicts require explicit review",()=>{expect(draftable("MATERIAL_RECONCILE")).toBe(true);const f=liveFixture(),command=liveCommand.parse({type:"MATERIAL_RECONCILE",mutation_id:fixtureId(998),device_id:f.q.device_id,expected_version:1,control_epoch:1,bowl_id:f.s.bowls[0]!.id,supersedes_id:null,prepared_grams:null,used_grams:null,waste_grams:null,reason:"Offline unknown"});expect(reconcileDraft({key:command.mutation_id,scope:"synthetic",command,createdAt:f.a.now},2,1)).toBe("CONFLICT_REVIEW");});

it("professional replan preserves superseded history and cannot revive an old bowl",()=>{const x=fixture();x.revise();const old=structuredClone(x.get().steps[0]!),pending=x.get().steps[1]!,bowl=x.get().bowls[1]!;const step={id:pending.id,region_id:pending.regionId,bowl_id:bowl.id,instruction_type:"APPLICATION",instruction_text:"Reviewed professional sequence"};x.act({type:"SEQUENCE",steps:[step],reason:"Professional replan"});expect(x.get().steps[0]).toEqual(old);expect(x.get().steps[1]!.instructionText).toBe(step.instruction_text);expect(()=>x.act({type:"SEQUENCE",steps:[{...step,id:old.id,bowl_id:old.bowlId}],reason:"Invalid old recipe"})).toThrow("SESSION_START_BLOCKED_STALE_INPUT");});
it("revised pending execution rejects retired catalog authority on step start",()=>{const x=fixture();x.revise();x.start();x.f.a.recipe=undefined;expect(()=>x.act({type:"STEP_START",step_id:x.get().steps[1]!.id})).toThrow("SESSION_START_BLOCKED_STALE_INPUT");});
