/** Conservative technical planning defaults; no chemical compatibility or medical claims. */
export const riskRules = {
 version: "risk-engine/1.0.0",
 minimumEvidenceQuality: 0.4,
 repeatedLighteningEvents: 2,
 regionalLevelDelta: 2,
 dimensions: ["HAIR_INTEGRITY", "CHEMICAL_HISTORY", "LIGHTENING_HISTORY", "REGIONAL_COMPLEXITY",
  "POROSITY_ELASTICITY", "EVIDENCE_INFORMATION", "PHYSICAL_TEST_SUFFICIENCY", "TECHNICAL_CONSISTENCY"],
 bands: ["LOW", "MODERATE", "HIGH", "CRITICAL"],
 gatePrecedence: ["CONTINUE_TECHNICAL_PLANNING", "CONTINUE_WITH_CHECKPOINTS", "REQUIRE_ADDITIONAL_ASSESSMENT",
  "REQUIRE_PHYSICAL_TEST", "REQUIRE_STRAND_TEST", "BLOCK_INSUFFICIENT_INFORMATION", "REQUIRE_RECOVERY_REASSESSMENT",
  "BLOCK_TECHNICAL_PLANNING", "OUTSIDE_COSMETIC_SCOPE"],
} as const;
export const riskReasonCodes = ["NO_ESCALATING_STRUCTURED_FACT", "HIGH_POROSITY_EVIDENCE", "LOW_ELASTICITY_EVIDENCE",
 "COMBINED_INTEGRITY_CONCERN", "INTEGRITY_INFORMATION_UNKNOWN", "LIGHTENING_HISTORY_PRESENT", "REPEATED_LIGHTENING_HISTORY",
 "LIGHTENING_HISTORY_UNKNOWN", "CHEMICAL_HISTORY_PRESENT", "CHEMICAL_HISTORY_COMPLEX", "CHEMICAL_HISTORY_UNKNOWN",
 "HISTORY_UNVERIFIED", "REGIONAL_VARIATION_HIGH", "REGION_INFORMATION_MISSING", "PHYSICAL_TEST_MISSING",
 "PHYSICAL_TEST_STALE", "PHYSICAL_TEST_UNRELIABLE", "CONFLICTING_INTEGRITY_EVIDENCE", "CONFLICTING_TECHNICAL_EVIDENCE",
 "CONFIDENCE_LOW", "CONFIDENCE_MODERATE", "CONFIDENCE_INSUFFICIENT", "CRITICAL_INFORMATION_GAP",
 "ADDITIONAL_INFORMATION_REQUIRED", "OUTSIDE_COSMETIC_SCOPE"] as const;
export const riskRequirementCodes = ["PERFORM_POROSITY_TEST", "PERFORM_ELASTICITY_TEST", "REASSESS_HAIR_INTEGRITY"] as const;
export type RiskBand = typeof riskRules.bands[number];
export type RiskDimension = typeof riskRules.dimensions[number];
export type GateOutcome = typeof riskRules.gatePrecedence[number];
export type RiskReasonCode = typeof riskReasonCodes[number];
