import Link from "next/link";
import { notFound } from "next/navigation";
import { SalonFrame } from "@/components/salon-frame";
import { CatalogGovernanceControls } from "@/components/catalog-governance-controls";
import { catalogOperator,readPilotCatalog } from "@/lib/brand/governance-service";
import { AccessError } from "@/lib/tenant/bootstrap";
export default async function CatalogPage({params}:{params:Promise<{catalogId:string}>}){
 try{await catalogOperator();}catch(e){if(e instanceof AccessError&&[401,403].includes(e.status))return <SalonFrame active="settings"><main className="salon-main"><h1>Teknik katalog yönetimi</h1><p role="alert">Yetkili katalog operatörü oturumu gerekir.</p></main></SalonFrame>;throw e;}
 const p=await readPilotCatalog((await params).catalogId).catch((e:unknown)=>{if(e instanceof AccessError&&[400,404].includes(e.status))notFound();throw e;});
 return <SalonFrame active="settings"><main className="salon-main" id="main-content"><Link href="/internal/catalogs">Katalog sürümleri</Link><h1>IGORA ROYAL ABSOLUTES</h1><p className="lead">Sürüm {p.catalog.release.version} · {p.catalog.release.state}</p><section className="salon-card"><h2>Resmi kaynaklar</h2>{p.sources.map(s=><article key={s.id}><h3>{s.document_title}</h3><p>{s.review_status} · {s.verification_status}</p><Link href={s.source_url} target="_blank" rel="noreferrer">Üretici belgesini aç</Link><p>Belge sürümü / tarihi: {s.document_version??"UNKNOWN"} / {s.document_date??"UNKNOWN"}</p><p>Alınma: {s.retrieved_at} · SHA-256: <code style={{overflowWrap:"anywhere"}}>{s.content_sha256}</code></p></article>)}</section><section className="salon-card"><h2>Ürün ve doğrulama durumu</h2><p>{p.catalog.products.filter(p=>p.productType==="SHADE").length} ton · {p.catalog.products.filter(p=>p.productType==="DEVELOPER").length} geliştirici · {p.catalog.compatibility.length} bağlama bağlı kural</p><div className="salon-table-scroll"><table className="salon-table"><thead><tr><th>Üretici kodu</th><th>Ürün</th><th>Doğrulama</th></tr></thead><tbody>{p.catalog.products.map(product=><tr key={product.id}><td>{product.manufacturerCode}</td><td>{product.displayName}</td><td>{product.verificationStatus}</td></tr>)}</tbody></table></div></section><section className="salon-card"><h2>Uyumluluk sınırları</h2><p>1:1 · 30–45 dakika aralığı · yalnızca dip bölgesi.</p><p>6%: %90&#39;dan fazla beyazda saf deposit. 9%: %90&#39;a kadar beyaz ve en fazla 3 seviye lift. Tam üretici talimatı ve profesyonel güvenlik incelemesi gerekir.</p><p>Diğer geliştiriciler UNKNOWN; markalar arası ikame yapılmaz. Sayısal pigmentler ve kesin işlem süresi UNKNOWN.</p></section><CatalogGovernanceControls id={p.catalog.release.id} state={p.catalog.release.state}/></main></SalonFrame>;
}
