import {z} from "zod";
import {minor,signedMinor} from "@/lib/finance/model";
import {stockCommand} from "@/lib/stock/model";
const id=z.uuid(),time=z.iso.datetime({offset:true}),currency=z.enum(["TRY","EUR","USD","GBP","JPY","KWD"]),reason=z.string().trim().min(1).max(2000),scope={organization_id:id,location_id:id};
const natural=z.string().regex(/^(0|[1-9]\d*)$/),positiveRational=z.string().regex(/^[1-9]\d{0,15}$/),base={mutation_id:id,reason};
export const costStatus=z.enum(["KNOWN","PARTIAL","UNKNOWN","NOT_APPLICABLE"]);
export const profitabilityStatus=z.enum(["COMPLETE","INCOMPLETE_COST","PARTIAL_COST","NOT_APPLICABLE"]);
export const costingReadRequest=z.strictObject({kind:z.enum(["PROFITABILITY","COST_BASIS","POLICIES","COMMISSION_SELF","COMMISSION_ALL"]).optional(),offset:z.int().min(0).max(10000).optional(),from:time.optional(),until:time.optional(),charge_id:id.optional(),staff_user_id:id.optional(),stock_item_id:id.optional()});
export const costingCommand=z.discriminatedUnion("type",[
 z.strictObject({...base,type:z.literal("INTAKE"),stock_command:stockCommand.refine(c=>c.type==="OPENING"||c.type==="RECEIPT"),currency,total_cost_minor:minor.nullable(),unit_cost_numerator:minor.nullable(),unit_cost_denominator:positiveRational.nullable(),cost_basis_at:time,external_reference:z.string().max(160).nullable()}).refine(c=>c.mutation_id===c.stock_command.mutation_id&&(c.total_cost_minor!==null?(c.unit_cost_numerator===null&&c.unit_cost_denominator===null):(c.unit_cost_numerator!==null&&c.unit_cost_denominator!==null))),
 z.strictObject({...base,type:z.literal("SET_BASIS"),stock_item_id:id,lot_id:id.nullable(),expected_version:z.int().nonnegative(),currency,unit_cost_numerator:minor,unit_cost_denominator:positiveRational,cost_basis_at:time}),
 z.strictObject({...base,type:z.literal("POLICY_VERSION"),id,expected_version:z.int().nonnegative(),name:z.string().trim().min(1).max(160),domain:z.enum(["SERVICE","RETAIL"]),method:z.enum(["PERCENT_GROSS","PERCENT_NET_OF_TAX","FIXED_AMOUNT"]),rate_bps:z.int().min(0).max(10000).nullable(),fixed_minor:minor.nullable(),currency,effective_from:time}).refine(c=>c.method==="FIXED_AMOUNT"?c.fixed_minor!==null&&c.rate_bps===null:c.rate_bps!==null&&c.fixed_minor===null),
 z.strictObject({...base,type:z.literal("ASSIGN"),id,staff_user_id:id,policy_id:id,scope:z.enum(["SERVICE","SERVICE_CATEGORY","DEFAULT_SERVICE","DEFAULT_RETAIL"]),service_id:id.nullable(),category:z.string().max(40).nullable(),effective_from:time,effective_until:time.nullable()}).refine(c=>(c.scope==="SERVICE")===(c.service_id!==null)&&(c.scope==="SERVICE_CATEGORY")===(c.category!==null)),
 z.strictObject({...base,type:z.literal("ASSIGN_END"),assignment_id:id,effective_until:time}),
 z.strictObject({...base,type:z.literal("DECLARE_NO_STOCK"),charge_id:id}),
 z.strictObject({...base,type:z.literal("ATTRIBUTE_RETAIL"),charge_id:id,staff_user_id:id}),
 z.strictObject({...base,type:z.literal("PROCESS_CHARGE"),charge_id:id}),
]);
export type CostingCommand=z.infer<typeof costingCommand>;
export const stockCostBasis=z.strictObject({id,...scope,stock_item_id:id,stock_lot_id:id.nullable(),version:z.int().positive(),stock_movement_id:id.nullable(),previous_event_id:id.nullable(),quantity_hundredths:z.string().regex(/^-?\d+$/),value_numerator:z.string().regex(/^-?\d+$/),value_denominator:natural,currency,status:z.enum(["KNOWN","UNKNOWN"]),event_type:z.enum(["MOVEMENT","FUTURE_CORRECTION"]),incoming_numerator:natural.nullable(),incoming_denominator:natural.nullable(),cost_basis_at:time,external_reference:z.string().nullable(),reason,actor_id:id,created_at:time,correlation_id:id,mutation_id:id});
export const directCostFact=z.strictObject({id,...scope,stock_movement_id:id,stock_item_id:id,stock_lot_id:id.nullable(),source_session_id:id.nullable(),source_bowl_id:id.nullable(),source_product_id:id.nullable(),finance_document_id:id.nullable(),source_client_id:id.nullable(),quantity:z.string(),unit:z.enum(["GRAM","MILLILITER","UNIT"]),currency,cost_method:z.literal("MOVING_WEIGHTED_AVERAGE"),cost_basis_event_id:id.nullable(),cost_basis_version:z.int().positive().nullable(),unit_cost_numerator:natural.nullable(),unit_cost_denominator:natural.nullable(),total_cost_minor:signedMinor.nullable(),status:z.enum(["KNOWN","UNKNOWN"]),source_domain:z.enum(["RETAIL","LIVE_USAGE","STOCK_ADJUSTMENT"]),correction_of:id.nullable(),actor_id:id,created_at:time,correlation_id:id});
const rule={method:z.enum(["PERCENT_GROSS","PERCENT_NET_OF_TAX","FIXED_AMOUNT"]),rate_bps:z.int().min(0).max(10000).nullable(),fixed_minor:minor.nullable()};
export const commissionPolicy=z.strictObject({id,...scope,name:z.string(),domain:z.enum(["SERVICE","RETAIL"]),created_by:id,created_at:time,version:z.int().positive(),...rule,currency,effective_from:time});
export const commissionAssignment=z.strictObject({id,...scope,staff_user_id:id,policy_id:id,scope:z.enum(["SERVICE","SERVICE_CATEGORY","DEFAULT_SERVICE","DEFAULT_RETAIL"]),service_id:id.nullable(),category:z.string().nullable(),effective_from:time,effective_until:time.nullable(),reason,actor_id:id,created_at:time,correlation_id:id});
export const commissionAccrual=z.strictObject({id,...scope,charge_id:id,staff_user_id:id,policy_id:id,policy_version:z.int().positive(),assignment_id:id,...rule,basis_minor:minor,amount_minor:minor,currency,eligible_at:time,created_at:time});
export const commissionAdjustment=z.strictObject({id,...scope,accrual_id:id,staff_user_id:id,source_document_id:id,amount_minor:signedMinor,reason,created_at:time});
const revenueAdjustment=z.strictObject({id,...scope,charge_id:id,source_document_id:id,source_allocation_id:id.nullable(),gross_delta_minor:signedMinor,net_delta_minor:signedMinor,tax_delta_minor:signedMinor,created_at:time});
export const profitabilityBreakdown=z.strictObject({charge_id:id,...scope,client_id:id.nullable(),appointment_id:id.nullable(),live_session_id:id.nullable(),service_id:id.nullable(),service_name:z.string().nullable(),service_version:z.int().positive().nullable(),category:z.string().nullable(),performed_by:id.nullable(),domain:z.enum(["SERVICE","RETAIL"]),currency,gross_minor:minor,net_minor:minor,tax_minor:minor,tax_rate_bps:z.int(),tax_inclusive:z.boolean(),eligible_at:time,created_at:time,
 gross_revenue_minor:signedMinor,net_revenue_minor:signedMinor,tax_revenue_minor:signedMinor,recognized_revenue_minor:signedMinor,revenue_basis:z.literal("NET_OF_TAX"),direct_product_cost_minor:signedMinor.nullable(),known_product_cost_minor:signedMinor.nullable(),cost_status:costStatus,profitability_status:profitabilityStatus,gross_contribution_minor:signedMinor.nullable(),commission_minor:signedMinor.nullable(),contribution_after_commission_minor:signedMinor.nullable(),margin_bps:z.int().nullable(),commission_disclosed:z.boolean(),cost_facts:directCostFact.array().max(200),commission_accrual:commissionAccrual.nullable(),commission_adjustments:commissionAdjustment.array().max(200),revenue_adjustments:revenueAdjustment.array().max(200),cost_method:z.literal("MOVING_WEIGHTED_AVERAGE"),cost_sources_truncated:z.boolean()});
export const commissionRow=commissionAccrual.extend({service_name:z.string().nullable(),domain:z.enum(["SERVICE","RETAIL"]),client_id:id.nullable(),adjustment_minor:signedMinor,commission_net_minor:signedMinor});
export const costingSnapshot=z.strictObject({...scope,kind:z.enum(["PROFITABILITY","COST_BASIS","POLICIES","COMMISSION_SELF","COMMISSION_ALL"]),offset:z.int().nonnegative(),total:z.int().nonnegative(),items:z.union([profitabilityBreakdown,commissionRow]).array().max(50),policies:commissionPolicy.array().max(50),assignments:commissionAssignment.array().max(50),assignment_endings:z.strictObject({assignment_id:id,...scope,effective_until:time,reason,actor_id:id,created_at:time,correlation_id:id}).array().max(50),cost_basis:stockCostBasis.array().max(50),staff:z.strictObject({user_id:id,display_name:z.string()}).array().max(100),services:z.strictObject({id,name:z.string(),category:z.string()}).array().max(200)});
export type CostingSnapshot=z.infer<typeof costingSnapshot>;
export const costingResult=z.strictObject({id,status:z.literal("SAVED")});
export function costingPermission(type:CostingCommand["type"]){return type==="INTAKE"?"cost.manage_acquisition":["SET_BASIS","DECLARE_NO_STOCK"].includes(type)?"cost.correct":"commission.manage_policies";}
export function costingReadPermission(kind:string|undefined){return kind==="POLICIES"?"commission.manage_policies":kind==="COMMISSION_ALL"?"commission.view_all":kind==="COMMISSION_SELF"?"commission.view_self":"cost.view";}
