/** Brand-independent planning defaults; no manufacturer chemistry or achievement guarantees. */
export const colorRules = {
 version:"color-engine/1.0.0", targetSchemaVersion:1,
 smallLiftMax:1, moderateLiftMax:3, fillDarkeningDelta:3, greyNaturalBaseThreshold:0.5,
 sessions:{direct:{min:1,max:1}, staged:{min:1,max:2}, major:{min:2,max:4}, processedMajor:{min:3,max:6}},
 minimumFieldQuality:0.4,
 targetModes:["UNIFORM_COLOR","ROOT_REFRESH","ROOT_SHADOW","GREY_COVERAGE","LIGHTENING","TONING","COLOR_CORRECTION","FILL_PREPIGMENTATION","DIMENSIONAL_COLOR","MULTI_REGION_CUSTOM"],
 tones:["NEUTRAL","ASH_COOL","VIOLET","BLUE","GREEN","GOLD_WARM","COPPER","RED","MIXED"],
 stages:["ASSESS","PREPARE","FILL_PREPIGMENT","REDUCE_CORRECT","LIGHTEN","DEPOSIT","NEUTRALIZE","TONE","ROOT_APPLICATION","LENGTHS_APPLICATION","ENDS_APPLICATION","REASSESS","RECOVERY","FINALIZE"],
 feasibility:["DIRECT","CONDITIONAL","MULTI_STAGE","MULTI_SESSION","INFORMATION_REQUIRED","RECOVERY_REQUIRED","BLOCKED_BY_SAFETY_GATE"],
 strategies:["CONSERVATIVE","SINGLE_SESSION_PROGRESS","MULTI_SESSION"],
} as const;
export const colorReasonCodes=["TARGET_REQUIRES_LIGHTENING","TARGET_REQUIRES_DARKENING","TARGET_SAME_LEVEL","TONE_ADJUSTMENT_INTENT","NEUTRALIZATION_INTENT",
 "MULTI_SESSION_REQUIRED","REGION_REQUIRES_SEPARATE_STRATEGY","GREY_COVERAGE_PRIORITY","NATURAL_BASE_SUPPORT_CANDIDATE","BAND_REQUIRES_ISOLATION",
 "PREVIOUS_LIGHTENING_LIMITS_PROGRESS","COSMETIC_HISTORY_REQUIRES_REVIEW","FILL_PREPIGMENTATION_CANDIDATE","CORRECTION_REQUIRES_INTERMEDIATE_GOAL",
 "POROUS_ENDS_REQUIRE_CHECKPOINT","PRESERVE_EXISTING_REGION","PHYSICAL_TEST_REQUIRED","SAFETY_GATE_BLOCKS_PLANNING","TARGET_INFORMATION_INCOMPLETE",
 "CURRENT_STATE_INFORMATION_REQUIRED","PARTIAL_PROGRESS_ONLY","BRAND_ADAPTER_REQUIRED","RISK_CHECKPOINTS_REQUIRED"] as const;
export const targetIssueCodes=["TARGET_INVALID","TARGET_LEVEL_REQUIRED","TARGET_TONE_REQUIRED","TARGET_REGION_INVALID","TARGET_REGION_DUPLICATE",
 "TARGET_REGION_MISSING","TARGET_PRESERVE_CONFLICT","TARGET_PRIORITY_CONFLICT","TARGET_UNIFORM_CONFLICT","TARGET_INTERMEDIATE_REQUIRED","TARGET_MIXED_TONE_INVALID"] as const;
