import { expect,it,vi } from "vitest";
import { controlledResponse } from "./controlled-http";
import { fixtureId } from "@/test/confidence-fixtures";
const body={client_id:fixtureId(1),plan_id:fixtureId(2),catalog_id:fixtureId(3),request_id:fixtureId(4),product_id:fixtureId(5),developer_id:fixtureId(6),color_grams:30.15};
function request(data:unknown=body,origin="http://localhost:3001",url="http://localhost:3001/api",type="application/json"){return new Request(url,{method:"POST",headers:{origin,"content-type":type,"x-workspace-reference":"test"},body:typeof data==="string"?data:JSON.stringify(data)});}
it.each(["white_ratio","organization_id","developer_grams","processing_minutes","verified","executable"])("HTTP rejects forged %s before service",async field=>{const execute=vi.fn();expect((await controlledResponse(request({...body,[field]:true}),"create",null,execute)).status).toBe(400);expect(execute).not.toHaveBeenCalled();});
it.each(["http://evil.test","http://localhost:3002",""])("foreign/missing origin %s cannot create",async origin=>{const execute=vi.fn();expect((await controlledResponse(request(body,origin),"create",null,execute)).status).toBe(403);expect(execute).not.toHaveBeenCalled();});
it.each([request("{"),request("x".repeat(8193)),request(body,"http://localhost:3001","http://localhost:3001/api?force=true"),request(body,"http://localhost:3001","http://localhost:3001/api","text/plain"),request({...body,color_grams:.001})])("malformed body/precision/query/media denied",async req=>{const execute=vi.fn();expect((await controlledResponse(req,"create",null,execute)).status).toBe(400);expect(execute).not.toHaveBeenCalled();});
it.each(["","?client_id=x&client_id=y","?client_id=x&ignoreRisk=true"])("history query %s denied",async query=>{const read=vi.fn();expect((await controlledResponse(new Request(`http://localhost/api${query}`),"read",null,undefined,undefined,read)).status).toBe(400);expect(read).not.toHaveBeenCalled();});
it("unexpected exception stays private and hides internals",async()=>{const execute=vi.fn().mockRejectedValue(new Error("secret implementation"));const response=await controlledResponse(request(),"create",null,execute);expect(response.status).toBe(503);expect(response.headers.get("cache-control")).toBe("private, no-store");expect(JSON.stringify(await response.json())).not.toContain("secret implementation");});
