import { z } from "zod";
import { colorPlanning } from "@/lib/color/model";

export const verification = z.enum(["ELIFORA_VERIFIED", "SALON_VERIFIED", "UNVERIFIED", "DEPRECATED"]);
export const source = z.enum(["MANUFACTURER_DOCUMENTATION", "ELIFORA_EXPERT_VALIDATED", "SALON_VALIDATED", "IMPORTED_UNVERIFIED", "UNKNOWN"]);
export const pigmentDimensions = ["level_effect", "neutral", "ash", "blue", "violet", "green", "red", "copper", "gold", "pearl", "beige", "natural_base", "opacity", "coverage_strength", "deposit_strength", "lift_behavior"] as const;
export const factKeys = [...pigmentDimensions, "shade_level", "tone_family", "mixing_ratio", "processing_minutes", "developer_strength", "lift_levels", "grey_coverage", "deposit_capability"] as const;
export const technicalFact = z.strictObject({
 key: z.enum(factKeys), value: z.union([z.number().finite(), z.string().min(1).max(200), z.boolean()]).nullable(),
 unit: z.enum(["SOURCE_SCALE", "LEVEL", "LEVELS", "PERCENT", "MINUTES", "RATIO", "CATEGORY", "BOOLEAN"]).nullable(),
 source, verificationStatus: verification, sourceReference: z.string().min(1).max(1000).nullable(),
 version: z.int().positive(), verifiedBy: z.uuid().nullable(), verifiedAt: z.iso.datetime({offset:true}).nullable(), confidence: z.number().min(0).max(1).nullable(),
}).superRefine((f, c) => {
 const verified = ["ELIFORA_VERIFIED", "SALON_VERIFIED"].includes(f.verificationStatus);
 if (verified && (f.value === null || f.unit === null || !f.sourceReference || !f.verifiedBy || !f.verifiedAt || f.confidence === null || ["UNKNOWN","IMPORTED_UNVERIFIED"].includes(f.source))) c.addIssue({code:"custom", message:"Verified fact needs complete provenance"});
 if (f.source === "UNKNOWN" && (f.value !== null || f.unit !== null || f.confidence !== null || verified)) c.addIssue({code:"custom", message:"Unknown is not a measurement"});
 if (pigmentDimensions.includes(f.key as typeof pigmentDimensions[number]) && f.value !== null && (typeof f.value !== "number" || f.unit !== "SOURCE_SCALE")) c.addIssue({code:"custom", message:"Pigment channels use documented source scales, never inferred percentages"});
 if (f.verificationStatus === "SALON_VERIFIED" && f.source !== "SALON_VALIDATED") c.addIssue({code:"custom", message:"Salon provenance required"});
 if (f.verificationStatus === "ELIFORA_VERIFIED" && !["MANUFACTURER_DOCUMENTATION","ELIFORA_EXPERT_VALIDATED"].includes(f.source)) c.addIssue({code:"custom", message:"Central provenance required"});
 const units:Record<string,string>={shade_level:"LEVEL",tone_family:"CATEGORY",mixing_ratio:"RATIO",processing_minutes:"MINUTES",developer_strength:"PERCENT",lift_levels:"LEVELS",grey_coverage:"BOOLEAN",deposit_capability:"BOOLEAN"};
 if(f.value!==null&&units[f.key]&&f.unit!==units[f.key])c.addIssue({code:"custom",message:"Technical unit mismatch"});
 if(f.value!==null&&["shade_level","processing_minutes","developer_strength","lift_levels"].includes(f.key)&&typeof f.value!=="number"||f.value!==null&&["tone_family","mixing_ratio"].includes(f.key)&&typeof f.value!=="string"||f.value!==null&&["grey_coverage","deposit_capability"].includes(f.key)&&typeof f.value!=="boolean")c.addIssue({code:"custom",message:"Technical value type mismatch"});
});
export const productTypes = ["SHADE","DEVELOPER","LIGHTENER","TONER","CORRECTOR","ACTIVATOR","TREATMENT","BOND"] as const;
export const catalogRelease = z.strictObject({id:z.uuid(), version:z.int().positive(), scope:z.enum(["GLOBAL","ORGANIZATION"]), organizationId:z.uuid().nullable(), state:z.enum(["DRAFT","TECHNICAL_REVIEW","GOLDEN_TEST","APPROVED","PUBLISHED","RETIRED"]), versionFingerprint:z.string().regex(/^[a-f0-9]{64}$/)}).superRefine((v,c)=>{if ((v.scope === "GLOBAL") !== (v.organizationId === null)) c.addIssue({code:"custom",message:"Scope/ownership mismatch"});});
export const catalogBrand = z.strictObject({id:z.uuid(),catalogId:z.uuid(),displayName:z.string().min(1).max(160)});
export const catalogLine = z.strictObject({id:z.uuid(),catalogId:z.uuid(),brandId:z.uuid(),displayName:z.string().min(1).max(160)});
export const catalogProduct = z.strictObject({id:z.uuid(),seriesId:z.uuid(),version:z.int().positive(),catalogId:z.uuid(),brandId:z.uuid(),lineId:z.uuid(),manufacturerCode:z.string().min(1).max(100),displayName:z.string().min(1).max(160),productType:z.enum(productTypes),professionalCategory:z.string().min(1).max(100),countryRegion:z.string().max(100).nullable(),manufacturerSourceReference:z.string().max(1000).nullable(),verificationStatus:verification,active:z.boolean(),verifiedBy:z.uuid().nullable(),verifiedAt:z.iso.datetime({offset:true}).nullable(),pigmentVectorVersion:z.literal("pigment-vector/1.0.0"),facts:technicalFact.array().max(24)}).superRefine((p,c)=>{if(new Set(p.facts.map(f=>f.key)).size!==p.facts.length)c.addIssue({code:"custom",message:"Duplicate technical fact"});if(["ELIFORA_VERIFIED","SALON_VERIFIED"].includes(p.verificationStatus)&&(!p.verifiedBy||!p.verifiedAt))c.addIssue({code:"custom",message:"Verification actor/time required"});});
export const compatibilityRule = z.strictObject({id:z.uuid(),catalogId:z.uuid(),version:z.int().positive(),productId:z.uuid(),developerId:z.uuid(),technique:z.string().min(1).max(100),applicationContext:z.string().min(1).max(100),mixingRatio:z.string().min(1).max(200).nullable(),outcome:z.enum(["VERIFIED_ALLOWED","VERIFIED_RESTRICTED","NOT_RECOMMENDED","INCOMPATIBLE","UNKNOWN"]),reason:z.string().min(1).max(500),source,sourceReference:z.string().max(1000).nullable(),verifiedBy:z.uuid().nullable(),verifiedAt:z.iso.datetime({offset:true}).nullable(),conditions:z.enum(["NO_LIFT","NO_GREY_COVERAGE","STANDARD_REGION_ONLY"]).array().max(3),restrictions:z.string().min(1).max(200).array().max(10)}).superRefine((r,c)=>{if(r.outcome.startsWith("VERIFIED_")&&(["UNKNOWN","IMPORTED_UNVERIFIED"].includes(r.source)||!r.sourceReference||!r.verifiedBy||!r.verifiedAt))c.addIssue({code:"custom",message:"Verified compatibility needs provenance"});if(r.outcome==="VERIFIED_RESTRICTED"&&r.conditions.length+r.restrictions.length===0)c.addIssue({code:"custom",message:"Restricted rule needs conditions"});});
export const catalogPacket = z.strictObject({release:catalogRelease,brands:catalogBrand.array().max(100),lines:catalogLine.array().max(100),products:catalogProduct.array().max(100),compatibility:compatibilityRule.array().max(1000)});
export type CatalogPacket = z.infer<typeof catalogPacket>;
export type Product = z.infer<typeof catalogProduct>;
export type Fact = z.infer<typeof technicalFact>;
export const evaluateRequest = z.strictObject({request_id:z.uuid(),client_id:z.uuid(),plan_id:z.uuid(),catalog_id:z.uuid(),allow_salon_verified:z.boolean().default(false)});
export const catalogQuery = z.strictObject({catalog_id:z.uuid(),brand_id:z.uuid().optional(),product_id:z.uuid().optional(),offset:z.coerce.number().int().min(0).max(10000).default(0),limit:z.coerce.number().int().min(1).max(50).default(25)});
export const adapterStates = ["BRAND_READY","BRAND_MATCH_PENDING","BLOCKED_BY_SAFETY","BLOCKED_UNVERIFIED_PRODUCT","BLOCKED_COMPATIBILITY","BLOCKED_MISSING_TECHNICAL_DATA"] as const;
export const requirement = z.strictObject({schemaVersion:z.literal(1),plan:colorPlanning,developerConstraints:z.literal("VERIFIED_COMPATIBILITY_ONLY")});
export const brandRecipe = z.strictObject({schemaVersion:z.literal(2),version:z.literal(1),parentRecipeId:z.string().regex(/^[a-f0-9]{64}$/),executionStatus:z.literal("BRAND_READY"),executable:z.literal(false),professionalReviewRequired:z.literal(true),product:catalogProduct,developer:catalogProduct,compatibility:compatibilityRule,technicalRequirement:requirement,snapshots:z.strictObject({colorEngine:z.string(),riskEngine:z.string(),brandAdapter:z.literal("brand-adapter/1.0.0"),brandCatalogId:z.uuid(),brandCatalogVersion:z.int().positive(),catalogFingerprint:z.string().regex(/^[a-f0-9]{64}$/),compatibilityMatrixVersion:z.int().positive(),productVersions:z.int().positive().array().length(2),pigmentVectorVersion:z.literal("pigment-vector/1.0.0")})});
export const adapterEvaluation = z.strictObject({engineVersion:z.literal("brand-adapter/1.0.0"),status:z.enum(adapterStates),candidateIds:z.uuid().array().max(100),reasons:z.string().array().max(100),recipe:brandRecipe.nullable()}).superRefine((v,c)=>{if((v.status==="BRAND_READY")!==(v.recipe!==null))c.addIssue({code:"custom",message:"Recipe/status mismatch"});});
export type AdapterEvaluation = z.infer<typeof adapterEvaluation>;
