import { z } from "zod";
import { catalogPacket, evaluateRequest } from "./model";
const uuid=z.uuid();
export const pilotKey="schwarzkopf-igora-royal-absolutes" as const;
export const sourceDocument=z.strictObject({id:uuid,catalog_id:uuid,document_key:uuid,manufacturer:z.string().min(1).max(160),document_title:z.string().min(1).max(200),document_version:z.string().nullable(),document_date:z.string().nullable(),source_url:z.string().regex(/^https:\/\/dm\.henkel-dam\.com\/is\/content\/henkel\/[A-Za-z0-9_-]+$/),retrieved_at:z.iso.datetime({offset:true}),source_type:z.literal("MANUFACTURER_TECHNICAL_DOCUMENT"),content_sha256:z.string().regex(/^[a-f0-9]{64}$/),review_status:z.enum(["PENDING","APPROVED","REJECTED"]),verification_status:z.enum(["UNVERIFIED","ELIFORA_VERIFIED"]),created_by:uuid,verified_by:uuid.nullable(),verified_at:z.iso.datetime({offset:true}).nullable()}).superRefine((s,c)=>{if(s.verification_status==="ELIFORA_VERIFIED"&&(s.review_status!=="APPROVED"||!s.verified_by||!s.verified_at))c.addIssue({code:"custom",message:"Official source review required"});});
export const productEvidence=z.strictObject({catalog_id:uuid,product_id:uuid,source_id:uuid,notation_source_id:uuid,page_or_section:z.string(),notation_section:z.string(),manufacturer_level:z.int().min(1).max(10).nullable(),manufacturer_tone:z.string().nullable(),manufacturer_tone_label:z.string().nullable(),normalized_tone:z.string().nullable(),processing_minutes_min:z.int().positive().nullable(),processing_minutes_max:z.int().positive().nullable()});
export const ruleEvidence=z.strictObject({catalog_id:uuid,rule_id:uuid,source_id:uuid,page_or_section:z.string(),white_min_exclusive:z.int().min(0).max(100).nullable(),white_max_inclusive:z.int().min(0).max(100).nullable(),max_lift:z.int().min(0).max(3).nullable(),regrowth_only:z.boolean()});
export const factEvidence=z.strictObject({catalog_id:uuid,product_id:uuid,key:z.string(),source_id:uuid,page_or_section:z.string()});
export const pilotPacket=z.strictObject({catalog:catalogPacket,pilotKey:z.literal(pilotKey),sources:sourceDocument.array().length(3),evidence:productEvidence.array().max(100),ruleSources:ruleEvidence.array().max(1000),factSources:factEvidence.array().max(2400),governance:z.strictObject({createdBy:uuid,reviewedBy:uuid.nullable(),approvedBy:uuid.nullable(),publishedBy:uuid.nullable()})}).superRefine((p,c)=>{
 const id=p.catalog.release.id,sourceIds=new Set(p.sources.map(s=>s.id)),productIds=new Set(p.catalog.products.map(s=>s.id)),ruleIds=new Set(p.catalog.compatibility.map(s=>s.id));
 if(p.catalog.release.scope!=="GLOBAL"||p.sources.some(s=>s.catalog_id!==id)||p.evidence.some(e=>e.catalog_id!==id||!productIds.has(e.product_id)||!sourceIds.has(e.source_id)||!sourceIds.has(e.notation_source_id)||e.processing_minutes_min!==null&&e.processing_minutes_max!==null&&e.processing_minutes_max<e.processing_minutes_min)||p.ruleSources.some(r=>r.catalog_id!==id||!ruleIds.has(r.rule_id)||!sourceIds.has(r.source_id))||p.factSources.some(f=>f.catalog_id!==id||!productIds.has(f.product_id)||!sourceIds.has(f.source_id)))c.addIssue({code:"custom",message:"Pilot provenance ownership invalid"});
});
export type PilotPacket=z.infer<typeof pilotPacket>;
export const governanceOperations=["IMPORT","START_REVIEW","COMPLETE_REVIEW","VALIDATE_GOLDEN","APPROVE","PUBLISH","RETIRE","REJECT"] as const;
export const governanceRequest=z.strictObject({operation:z.enum(governanceOperations),note:z.string().trim().min(1).max(1000),previous_id:uuid.transform(v=>v.toLowerCase()).nullable().optional()}).superRefine((r,c)=>{if(r.operation!=="IMPORT"&&r.previous_id)c.addIssue({code:"custom",message:"Only import selects a previous version"});});
export const pilotRequest=evaluateRequest.omit({allow_salon_verified:true,request_id:true});
export const pilotCandidate=z.strictObject({productId:uuid,manufacturerCode:z.string(),displayName:z.string(),manufacturerTone:z.string(),normalizedTone:z.string(),developerId:uuid,developerName:z.string(),compatibilityRuleId:uuid,compatibility:z.literal("VERIFIED_RESTRICTED"),mixingRatio:z.string(),processingMinutes:z.strictObject({min:z.int().positive(),max:z.int().positive()}),restrictions:z.strictObject({whitePercentGreaterThan:z.int().nullable(),whitePercentAtMost:z.int().nullable(),maxLift:z.int(),regrowthOnly:z.literal(true),safetyReviewRequired:z.literal(true)}),sourceIds:uuid.array().min(1),executable:z.literal(false)});
export const pilotResult=z.strictObject({schemaVersion:z.literal(1),status:z.enum(["CANDIDATES_FOR_REVIEW","BLOCKED_BY_SAFETY","CATALOG_UNAVAILABLE","NO_VERIFIED_MATCH"]),catalogId:uuid,catalogVersion:z.int().positive(),catalogFingerprint:z.string(),candidates:pilotCandidate.array().max(100),executable:z.literal(false),professionalReviewRequired:z.literal(true),explanation:z.strictObject({summary:z.string(),unknowns:z.string().array(),limitations:z.string().array()})});
