import { beforeEach,expect,it,vi } from "vitest";
import { randomBytes,createHmac } from "node:crypto";
import { brandFixture,orgId,actorId } from "@/test/brand-fixtures";
import { fixtureId } from "@/test/confidence-fixtures";
import { workspaceReference } from "@/lib/tenant/context";
import { AccessError } from "@/lib/tenant/bootstrap";
const mocks=vi.hoisted(()=>({context:vi.fn(),rpc:vi.fn(),user:vi.fn(),color:vi.fn(),rows:vi.fn()}));
vi.mock("@/lib/clients/service",()=>({verifiedClientContext:mocks.context}));
vi.mock("@/lib/color/service",()=>({executeColorCommand:mocks.color}));
vi.mock("@/lib/supabase/server",()=>({createClient:async()=>({rpc:mocks.rpc,auth:{getUser:mocks.user},from:()=>({select:()=>{const builder={eq:()=>builder,limit:()=>mocks.rows(),maybeSingle:()=>mocks.rows()};return builder;}})})}));
import { evaluateBrandRequest,readBrandCatalog,readBrandRecipe } from "./service";
import { evaluateBrandAdapter } from "./engine";
const context={membership_id:fixtureId(5),location_id:fixtureId(2),organization_id:orgId,organization_name:"Synthetic",location_name:"Synthetic",role:"owner" as const,membership_status:"active" as const,permissions:["clients.read","hair_passport.read","color_plan.read","color_plan.create","brand_catalog.manage"]};
const correlation=fixtureId(500),planId=fixtureId(501),recipeId=fixtureId(502);
const f=brandFixture(),q={request_id:fixtureId(503),client_id:f.input.target.clientId,plan_id:planId,catalog_id:f.catalog.release.id};
beforeEach(()=>{vi.clearAllMocks();vi.stubEnv("ELIFORA_COLOR_PLAN_SIGNING_KEY",randomBytes(32).toString("hex"));mocks.context.mockResolvedValue(context);mocks.user.mockResolvedValue({data:{user:{id:actorId}},error:null});mocks.rows.mockResolvedValue({data:[],error:null});mocks.color.mockResolvedValue({data:{id:planId,clientId:q.client_id,targetId:f.input.target.id,createdAt:f.plan.evaluatedAt,createdBy:actorId,result:f.plan},correlationId:correlation});mocks.rpc.mockImplementation(async(name,args)=>({error:null,data:name==="brand_catalog_packet"?f.catalog:name==="brand_adapter_snapshot"?{data:f.input.snapshot,sourceToken:"a".repeat(64),correlationId:correlation}:{id:recipeId,clientId:q.client_id,planId,catalogId:q.catalog_id,createdAt:f.plan.evaluatedAt,result:JSON.parse(args.p_envelope).result}}));});
it("server recomputes safety and signs a bound non-executable immutable snapshot",async()=>{const r=await evaluateBrandRequest(q,correlation,workspaceReference(context));expect(r.data.result.status).toBe("BRAND_READY");expect(r.data.result.recipe?.executable).toBe(false);const args=mocks.rpc.mock.calls.find(c=>c[0]==="brand_recipe_store")![1],packet=JSON.parse(args.p_envelope);expect(packet).toMatchObject({organizationId:orgId,actorId,planId,clientId:q.client_id,allowSalonVerified:false});expect(args.p_signature).toBe(createHmac("sha256",Buffer.from(process.env.ELIFORA_COLOR_PLAN_SIGNING_KEY!,"hex")).update(args.p_envelope).digest("hex"));expect(JSON.stringify(r)).not.toContain(process.env.ELIFORA_COLOR_PLAN_SIGNING_KEY!);});
it.each(["organization_id","verificationStatus","pigment","compatibility","created_by"])("forged %s denied before database access",async key=>{await expect(evaluateBrandRequest({...q,[key]:true},correlation,workspaceReference(context))).rejects.toMatchObject({code:"VALIDATION_FAILED"});expect(mocks.rpc).not.toHaveBeenCalled();});
it.each(["FORBIDDEN","MEMBERSHIP_REVOKED","UNAUTHENTICATED"])("fresh %s denies evaluation",async code=>{mocks.context.mockRejectedValue(new AccessError(code,403));await expect(evaluateBrandRequest(q,correlation,workspaceReference(context))).rejects.toMatchObject({code});expect(mocks.rpc).not.toHaveBeenCalled();});
it("stale workspace prevents evaluation",async()=>{await expect(evaluateBrandRequest(q,correlation,"stale")).rejects.toMatchObject({code:"TENANT_CONTEXT_INVALID"});expect(mocks.rpc).not.toHaveBeenCalled();});
it("salon product opt-in requires a management permission",async()=>{mocks.context.mockResolvedValue({...context,permissions:context.permissions.filter(p=>p!=="brand_catalog.manage")});await expect(evaluateBrandRequest({...q,allow_salon_verified:true},correlation,workspaceReference(context))).rejects.toMatchObject({code:"FORBIDDEN"});});
it("unsigned configuration cannot persist a derived recipe",async()=>{vi.stubEnv("ELIFORA_COLOR_PLAN_SIGNING_KEY","");await expect(evaluateBrandRequest(q,correlation,workspaceReference(context))).rejects.toMatchObject({code:"COLOR_ENGINE_UNAVAILABLE"});expect(mocks.rpc.mock.calls.some(c=>c[0]==="brand_recipe_store")).toBe(false);});
it("foreign organization catalog is concealed",async()=>{mocks.rpc.mockResolvedValueOnce({data:{...f.catalog,release:{...f.catalog.release,scope:"ORGANIZATION",organizationId:fixtureId(9999)}}});await expect(evaluateBrandRequest(q,correlation,workspaceReference(context))).rejects.toMatchObject({code:"BRAND_CATALOG_NOT_FOUND"});});
it("unpublished catalog cannot be persisted",async()=>{mocks.rpc.mockResolvedValueOnce({data:{...f.catalog,release:{...f.catalog.release,state:"DRAFT"}}});await expect(evaluateBrandRequest(q,correlation,workspaceReference(context))).rejects.toMatchObject({code:"CATALOG_STATE_CONFLICT"});});
it("a changed passport forces a new color plan",async()=>{mocks.rpc.mockImplementation(async name=>({data:name==="brand_catalog_packet"?f.catalog:{data:{...f.input.snapshot,pages:[{...f.input.snapshot.pages[0],passport:{...f.input.snapshot.pages[0]!.passport,version:999}}]},sourceToken:"a".repeat(64),correlationId:correlation}}));await expect(evaluateBrandRequest(q,correlation,workspaceReference(context))).rejects.toMatchObject({code:"COLOR_PLAN_SOURCE_CONFLICT"});});
it("revocation after storage conceals protected output",async()=>{mocks.context.mockResolvedValueOnce(context).mockRejectedValueOnce(new AccessError("MEMBERSHIP_REVOKED",403));await expect(evaluateBrandRequest(q,correlation,workspaceReference(context))).rejects.toMatchObject({code:"MEMBERSHIP_REVOKED"});});
it("catalog results are paginated and never include operator records",async()=>{const r=await readBrandCatalog({catalog_id:q.catalog_id,limit:1},"products",correlation);expect(r).toMatchObject({pagination:{offset:0,limit:1,total:2}});expect(r.data).toHaveLength(1);expect(JSON.stringify(r)).not.toContain("catalog_operators");});
it("invalid catalog paging is rejected",async()=>{await expect(readBrandCatalog({catalog_id:q.catalog_id,limit:101},"products",correlation)).rejects.toMatchObject({code:"VALIDATION_FAILED"});expect(mocks.rpc).not.toHaveBeenCalled();});
it("history read conceals missing or cross tenant recipes",async()=>{mocks.rows.mockResolvedValue({data:null,error:null});await expect(readBrandRecipe(recipeId,correlation)).rejects.toMatchObject({code:"BRAND_RECIPE_NOT_FOUND"});});
it("an idempotent retry reads the original snapshot without re-evaluating a changed catalog",async()=>{
 const payload=evaluateBrandAdapter(f.plan,f.catalog,orgId,false);
 mocks.rows.mockResolvedValue({data:[{id:recipeId,created_by:actorId,created_at:f.plan.evaluatedAt,client_id:q.client_id,plan_id:planId,catalog_id:q.catalog_id,allow_salon_verified:false,payload}],error:null});
 expect((await evaluateBrandRequest(q,correlation,workspaceReference(context))).data.result).toEqual(payload);
 expect(mocks.color).not.toHaveBeenCalled();expect(mocks.rpc).not.toHaveBeenCalled();
});
it("an idempotency key cannot be reused with a changed salon opt-in",async()=>{
 mocks.rows.mockResolvedValue({data:[{created_by:actorId,client_id:q.client_id,plan_id:planId,catalog_id:q.catalog_id,allow_salon_verified:true}],error:null});
 await expect(evaluateBrandRequest(q,correlation,workspaceReference(context))).rejects.toMatchObject({code:"COLOR_PLAN_VERSION_CONFLICT"});
 expect(mocks.rpc).not.toHaveBeenCalled();
});
