import { expect,test,type Page } from "@playwright/test";
import { randomUUID } from "node:crypto";
import { seedAccount,login,expectReady } from "./local-auth";
import * as m from "@/lib/crm/model";
test.use({actionTimeout:20000});
async function capture(page:Page,path:string){
 await page.evaluate(async()=>{if(document.activeElement instanceof HTMLElement)document.activeElement.blur();window.scrollTo({top:0,left:0,behavior:"instant"});await new Promise<void>(resolve=>requestAnimationFrame(()=>requestAnimationFrame(()=>resolve())));});
 await page.screenshot({path,fullPage:true});
}
async function session(page:Page){const r=await page.request.get("/api/session");expect(r.status()).toBe(200);return (await r.json()).context;}
async function op(page:Page,command:object){const c=await session(page);const r=await page.request.post("/api/salon",{headers:{origin:"http://127.0.0.1:4173","x-workspace-reference":`${c.membership_id}:${c.location_id}`},data:{mutation_id:randomUUID(),...command}});return {status:r.status(),body:await r.json()};}
async function seed(page:Page){
 const account=await seedAccount(),second=await account.addMember("colorist");await login(page,account);await expectReady(page);
 const c=await session(page),r=await page.request.post("/api/clients",{headers:{origin:"http://127.0.0.1:4173","x-workspace-reference":`${c.membership_id}:${c.location_id}`},data:{operation:"create",payload:{full_name:"Deniz CRM",phone:"05321112233",phone_region:"TR",request_id:randomUUID()}}});expect(r.status()).toBe(200);const client=(await r.json()).data;
 const serviceId=randomUUID(),resourceId=randomUUID();
 const save=async(q:object)=>{const result=await op(page,q);expect(result.status,JSON.stringify(result.body)).toBe(200);return result.body.data;};
 await save({type:"HOURS_SAVE",expected_version:0,days:Array.from({length:7},(_,i)=>({day:i+1,closed:false,opens:540,closes:1080}))});
 for(const [membership_id,display_name] of [[account.membershipId,"Elif Operations"],[second.membershipId,"Merve Operations"]])await save({type:"STAFF_SAVE",membership_id,expected_version:0,definition:{display_name,active:true,bookable:true,working_capacity:null,notes:null,competencies:[{code:"GENERAL_COLOR",level:"INDEPENDENT"}],shifts:[...Array.from({length:7},(_,i)=>({day:i+1,type:"SHIFT",starts:540,ends:1080})),{day:1,type:"BREAK",starts:720,ends:780}]}});
 await save({type:"RESOURCE_SAVE",id:resourceId,expected_version:0,definition:{name:"Renk koltuğu",type:"CHAIR",capacity:1,active:true}});
 await save({type:"SERVICE_SAVE",id:serviceId,expected_version:0,definition:{name:"Renk danışmanlığı",category:"COLOR",description:"Yerel test hizmeti",organization_wide:false,base_duration_minutes:60,buffer_before_minutes:5,buffer_after_minutes:10,base_price:1000,tax_rate:20,tax_inclusive:false,requires_colorlab:true,requires_hair_passport:true,requires_precheck:true,active:true,eligible_membership_ids:[account.membershipId,second.membershipId],capabilities:[{code:"GENERAL_COLOR",level:"INDEPENDENT"}],resources:[{type:"CHAIR",units:1}]}});
 const booking=(id:string,start:string,member=account.membershipId)=>({type:"APPOINTMENT_SAVE",id,expected_version:0,definition:{client_id:client.id,service_id:serviceId,staff_membership_id:member,local_start:start,utc_offset_minutes:null,scheduled_duration_minutes:null,adjustment_reason:null,notes:null,status:"CONFIRMED"}});
 return {account,second,client,serviceId,resourceId,save,booking};
}

async function crm(page:Page,data:object,write=false){const c=await session(page);const r=await page.request.post(`/api/crm${write?"":"/read"}`,{headers:{origin:"http://127.0.0.1:4173","x-workspace-reference":`${c.membership_id}:${c.location_id}`},data:write?{mutation_id:randomUUID(),...data}:data});return {status:r.status(),body:await r.json()};}
test("CRM real-auth profile, preferences, note privacy, reviewed merge, rebook and responsive screens",async({page,browser},info)=>{
 test.setTimeout(240000);const f=await seed(page),reception=await f.account.addMember("reception");
 const read=async(data:object)=>{const r=await crm(page,data);expect(r.status,JSON.stringify(r.body)).toBe(200);return r.body.data;};
 const write=async(data:object)=>{const r=await crm(page,data,true);expect(r.status,JSON.stringify(r.body)).toBe(200);return r.body.data;};
 expect(m.crmOverview.parse(await read({operation:"summary",client_id:f.client.id})).summary.relationship_status).toBe("NEW");
 const a=await f.save(f.booking(randomUUID(),"2026-10-12T10:00"));
 for(const [expected_version,status] of [[1,"ARRIVED"],[2,"IN_SERVICE"],[3,"COMPLETED"]])await f.save({type:"APPOINTMENT_TRANSITION",id:a.id,expected_version,status,reason:"Synthetic CRM lifecycle"});
 await write({type:"RETURN_WINDOW_SAVE",service_id:f.serviceId,expected_version:0,min_days:1,max_days:30});
 await page.goto(`/workspace/clients/${f.client.id}`);await expect(page.getByRole("heading",{name:"Ziyaret ve dönüş"})).toBeVisible();
 const panel=page.getByRole("region",{name:"Müşteri ilişkileri"});
 await panel.getByText("Tercihler ve iletişim",{exact:true}).click();await panel.getByLabel("Tercih edilen personel",{exact:true}).selectOption(f.account.membershipId);await panel.getByLabel("Hizmet tercihleri").selectOption(f.serviceId);await panel.getByLabel("İletişim tercihi").selectOption("WHATSAPP");await panel.getByLabel("Elle iletişime izin var").check();await panel.getByRole("button",{name:"Tercihleri kaydet"}).click();
 await expect(panel.getByText(/Elif Operations · Müşterinin açık tercihi/)).toBeVisible();
 const pref=m.crmOverview.parse(await read({operation:"summary",client_id:f.client.id})).preferences!;expect(pref.version).toBe(1);
 expect((await crm(page,{type:"PREFERENCE_SAVE",client_id:f.client.id,expected_version:0,definition:{preferred_staff_id:pref.preferred_staff_id,preferred_service_ids:pref.preferred_service_ids,request_notes:pref.request_notes,preferred_channel:pref.preferred_channel,allow_manual_contact:pref.allow_manual_contact,do_not_contact:pref.do_not_contact}},true)).body.code).toBe("CRM_CONFLICT");
 const contact=await page.request.post("/api/crm/contact",{headers:{origin:"http://127.0.0.1:4173","x-workspace-reference":`${(await session(page)).membership_id}:${f.account.locations[0]!.id}`},data:{client_id:f.client.id}});expect(contact.status()).toBe(200);expect((await contact.json()).data.url).toBe("https://wa.me/905321112233");
 await panel.getByRole("button",{name:"Notlar",exact:true}).click();await panel.getByLabel("Görünürlük").selectOption("PRIVATE_MANAGEMENT");await panel.getByLabel("Not",{exact:true}).fill("Yalnızca yönetim görebilir");await panel.getByRole("button",{name:"Not ekle",exact:true}).click();await expect(panel.getByLabel("Not",{exact:true}).nth(1)).toHaveValue("Yalnızca yönetim görebilir");
 await write({type:"NOTE_SAVE",id:randomUUID(),client_id:f.client.id,expected_version:0,visibility:"RECEPTION",body:"Geliş bilgisi",archived:false});
 const staffContext=await browser.newContext(),staffPage=await staffContext.newPage();await login(staffPage,reception);await expectReady(staffPage);const staffNotes=await crm(staffPage,{operation:"notes",client_id:f.client.id});expect(staffNotes.status).toBe(200);expect(staffNotes.body.data.items.map((n:{body:string})=>n.body)).toEqual(["Geliş bilgisi"]);expect((await crm(staffPage,{operation:"merge_review",source_client_id:f.client.id,target_client_id:randomUUID()})).status).toBe(403);await staffContext.close();
 await page.goto(`/workspace/clients/${f.client.id}`);await expect(page.getByRole("heading",{name:"Ziyaret ve dönüş"})).toBeVisible();
 for(const [width,name] of [[1440,"desktop"],[820,"tablet"],[320,"mobile-320"]] as const){await page.setViewportSize({width,height:900});await capture(page,info.outputPath(`client-crm-profile-${name}.png`));expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);}
 await page.getByRole("link",{name:"Yeniden randevu hazırla"}).click();const dialog=page.getByRole("dialog");await expect(dialog.getByLabel("Hizmet",{exact:true})).toHaveValue(f.serviceId);await expect(dialog.getByLabel("Personel",{exact:true})).toHaveValue(f.account.membershipId);await expect(dialog.getByText("Deniz CRM",{exact:true})).toBeVisible();await dialog.getByRole("button",{name:"Kapat"}).click();
 await page.goto("/workspace/clients/new");await page.getByLabel("Ad Soyad *").fill("Deniz CRM İkinci");await page.getByLabel("Telefon *").fill("05321112233");await page.getByRole("button",{name:"Müşteri Oluştur",exact:true}).click();await expect(page.getByRole("heading",{name:"Benzer müşteri bulundu"})).toBeVisible();await page.getByRole("button",{name:"Farklı kişi olduğunu onaylıyorum"}).click();await expect(page.getByRole("heading",{name:"Deniz CRM İkinci",exact:true})).toBeVisible();const target={id:page.url().split("/").at(-1)!};
 await page.goto(`/workspace/clients/${f.client.id}`);await expect(page.getByRole("heading",{name:"Ziyaret ve dönüş"})).toBeVisible();await page.getByText("Benzer kayıtları incele",{exact:true}).click();await page.getByRole("button",{name:"Benzer kayıt takip aksiyonu oluştur"}).click();await expect(page.getByRole("button",{name:"Benzer kayıt takip aksiyonu oluştur"})).toHaveCount(0);
 await page.goto("/workspace/clients");await page.getByRole("button",{name:"CRM aksiyon merkezi",exact:true}).click();await expect(page.getByText("Benzer kayıt incelemesi · Açık",{exact:true})).toBeVisible();await page.getByLabel("Erteleme zamanı").fill(new Date(Date.now()+86400000).toISOString().slice(0,16));await page.getByRole("button",{name:"Ertelendi",exact:true}).click();await expect(page.getByText("Bu durumda görünür aksiyon yok.")).toBeVisible();await page.getByLabel("Aksiyon durumu").selectOption("SNOOZED");await expect(page.getByText("Benzer kayıt incelemesi · Ertelendi",{exact:true})).toBeVisible();await page.getByRole("button",{name:"Tamamlandı",exact:true}).click();await expect(page.getByText("Bu durumda görünür aksiyon yok.")).toBeVisible();await page.getByLabel("Aksiyon durumu").selectOption("DONE");await expect(page.getByText("Benzer kayıt incelemesi · Tamamlandı",{exact:true})).toBeVisible();
 for(const [width,name] of [[1440,"desktop"],[320,"mobile-320"]] as const){await page.setViewportSize({width,height:900});await capture(page,info.outputPath(`client-crm-actions-${name}.png`));expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);}
 await page.goto("/workspace/clients");await page.getByLabel("Ad soyad veya telefon").fill("Deniz CRM");await page.getByRole("button",{name:"Ara",exact:true}).click();await expect(page.getByRole("link",{name:"Deniz CRM",exact:true})).toBeVisible();await page.getByLabel("Arama isteği").fill("60 gündür gelmeyen müşteriler");await page.getByRole("button",{name:"Filtre olarak yorumla"}).click();await expect(page.getByText(/Yorumlanan filtreleri yukarıda/)).toBeVisible();await page.getByText("İlişki ve ziyaret filtreleri",{exact:true}).click();await expect(page.getByLabel("Son ziyaretten en az gün")).toHaveValue("60");await page.getByRole("button",{name:"Filtreleri temizle"}).click();await expect(page.getByRole("link",{name:"Deniz CRM",exact:true})).toBeVisible();
 for(const [width,name] of [[1440,"desktop"],[320,"mobile-320"]] as const){await page.setViewportSize({width,height:900});await capture(page,info.outputPath(`client-crm-directory-${name}.png`));expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);}
 await page.goto(`/workspace/clients/${f.client.id}`);await expect(page.getByRole("heading",{name:"Ziyaret ve dönüş"})).toBeVisible();await page.getByText("Benzer kayıtları incele",{exact:true}).click();await page.getByRole("button",{name:"Bu hedefle birleştirmeyi incele"}).click();
 const merge=page.getByRole("button",{name:"İncelenen kayıtları birleştir"});await expect(merge).toBeVisible();const choices=page.locator("form").filter({has:merge}).locator("select");await expect(choices).toHaveCount(10);for(let i=0;i<10;i++)await choices.nth(i).selectOption("SOURCE");await page.getByLabel("Aynı kişi olduğunu ve her alan seçimini doğruladım").check();await merge.click();await expect(page).toHaveURL(new RegExp(`/clients/${target.id}$`));await expect(page.getByRole("heading",{name:"Ziyaret ve dönüş"})).toBeVisible();
 const merged=m.crmOverview.parse(await read({operation:"summary",client_id:target.id}));expect(merged.summary.total_completed_visits).toBe(1);expect(merged.summary.source_client_ids).toContain(f.client.id);const timeline=m.page(m.clientTimelineEvent).parse(await read({operation:"timeline",client_id:target.id,limit:50}));const completed=timeline.items.filter(e=>e.event_type==="APPOINTMENT_COMPLETED");expect(completed).toHaveLength(1);expect(completed[0]!.source_client_id).toBe(f.client.id);
 await f.account.revoke();await page.evaluate(()=>window.dispatchEvent(new Event("focus")));await expect(page).toHaveURL(/\/workspaces/,{timeout:20000});await expect(page.getByRole("region",{name:"Müşteri ilişkileri"})).toHaveCount(0);
});
