import {expect,type Page,type TestInfo} from "@playwright/test";
import {randomUUID} from "node:crypto";
import {costingSnapshot,profitabilityBreakdown} from "@/lib/costing/model";
export async function prepareLiveCosting(page:Page,clientId:string,recipeId:string,headers:Record<string,string>){
 const op=async(route:string,q:object)=>{const r=await page.request.post(route,{headers,data:{mutation_id:randomUUID(),...q}});expect(r.status(),await r.text()).toBe(200);return (await r.json()).data;};
 const context=(await(await page.request.get("/api/session")).json()).context,recipe=(await(await page.request.get(`/api/controlled-brand-recipes/${recipeId}?client_id=${clientId}`)).json()).data;
 await op("/api/finance",{type:"CURRENCY_SET",currency:"TRY",expected_version:0,reason:"Verified operation currency"});await op("/api/stock",{type:"ENABLE",reason:"Measured inventory before session creation"});
 for(const [product,cost] of [[recipe.result.selected.productId,"1000"],[recipe.result.selected.developerId,"2000"]]){const item=randomUUID();await op("/api/stock",{type:"ITEM_SAVE",id:item,expected_version:0,definition:{source:"GLOBAL_VERIFIED_CATALOG",catalog_product_id:product,product_type:cost==="1000"?"COLOR":"DEVELOPER",display_name:cost==="1000"?"Doğrulanmış boya":"Doğrulanmış geliştirici",sku:null,barcode:null,inventory_unit:"GRAM",active:true,track_quantity:true,lot_required:false,low_threshold:10},reason:"Verified actual product mapping"});const mid=randomUUID();await op("/api/costing",{type:"INTAKE",mutation_id:mid,stock_command:{type:"OPENING",mutation_id:mid,stock_item_id:item,lot_id:null,quantity:100,unit:"GRAM",occurred_at:new Date().toISOString(),reference:null,reason:"Actual acquisition basis"},currency:"TRY",total_cost_minor:cost,unit_cost_numerator:null,unit_cost_denominator:null,cost_basis_at:new Date().toISOString(),external_reference:null,reason:"Actual acquisition basis"});}
 await op("/api/salon",{type:"HOURS_SAVE",expected_version:0,days:Array.from({length:7},(_,i)=>({day:i+1,closed:false,opens:540,closes:1080}))});await op("/api/salon",{type:"STAFF_SAVE",membership_id:context.membership_id,expected_version:0,definition:{display_name:"Elif Colorist",active:true,bookable:true,working_capacity:null,notes:null,competencies:[],shifts:Array.from({length:7},(_,i)=>({day:i+1,type:"SHIFT",starts:540,ends:1080}))}});
 const service=randomUUID();await op("/api/salon",{type:"SERVICE_SAVE",id:service,expected_version:0,definition:{name:"Gerçek kullanım renk hizmeti",category:"COLOR",description:null,organization_wide:false,base_duration_minutes:60,buffer_before_minutes:0,buffer_after_minutes:0,base_price:1000,tax_rate:20,tax_inclusive:false,requires_colorlab:false,requires_hair_passport:false,requires_precheck:false,active:true,eligible_membership_ids:[context.membership_id],capabilities:[],resources:[]}});
 const policy=randomUUID();await op("/api/costing",{type:"POLICY_VERSION",id:policy,expected_version:0,name:"Renk hizmeti komisyonu",domain:"SERVICE",method:"PERCENT_NET_OF_TAX",rate_bps:1000,fixed_minor:null,currency:"TRY",effective_from:new Date().toISOString(),reason:"Future service commission"});
 const staffSnapshot=(await(await page.request.get("/api/costing?kind=POLICIES")).json()).data;
 const staffUser=staffSnapshot.staff[0].user_id;expect(staffUser).toBeTruthy();
 await op("/api/costing",{type:"ASSIGN",id:randomUUID(),staff_user_id:staffUser,policy_id:policy,scope:"DEFAULT_SERVICE",service_id:null,category:null,effective_from:new Date().toISOString(),effective_until:null,reason:"Explicit performer assignment"});
 const ap=await op("/api/salon",{type:"APPOINTMENT_SAVE",id:randomUUID(),expected_version:0,definition:{client_id:clientId,service_id:service,staff_membership_id:context.membership_id,local_start:"2026-10-12T10:00",utc_offset_minutes:null,scheduled_duration_minutes:null,adjustment_reason:null,notes:null,status:"CONFIRMED"}});
 for(const [v,status] of [[1,"ARRIVED"],[2,"IN_SERVICE"]])await op("/api/salon",{type:"APPOINTMENT_TRANSITION",id:ap.id,expected_version:v,status,reason:"Actual service state"});
 return {async link(sessionId:string){await op("/api/salon",{type:"LINK_LIVE_SESSION",id:ap.id,expected_version:3,live_session_id:sessionId});},async finish(info:TestInfo){
  await op("/api/stock",{type:"PROCESS_BATCH",limit:20});await op("/api/salon",{type:"APPOINTMENT_TRANSITION",id:ap.id,expected_version:4,status:"COMPLETED",reason:"Verified live outcome complete"});const charge=await op("/api/finance",{type:"SERVICE_CHARGE",id:randomUUID(),appointment_id:ap.id,reason:"Completed real service"});
  const response=await page.request.get(`/api/costing?charge_id=${charge.id}`);expect(response.status(),await response.text()).toBe(200);const d=profitabilityBreakdown.parse(costingSnapshot.parse((await response.json()).data).items[0]);expect(d.cost_status).toBe("KNOWN");expect(d.direct_product_cost_minor).toBe("1350");expect(d.net_revenue_minor).toBe("100000");expect(d.commission_minor).toBe("10000");expect(d.contribution_after_commission_minor).toBe("88650");expect(d.cost_facts).toHaveLength(2);expect(d.live_session_id).not.toBeNull();
  await page.goto(`/workspace/finance/profitability?charge_id=${charge.id}`);await expect(page.getByRole("heading",{name:"Nasıl hesaplandı?"})).toBeVisible();for(const [width,name] of [[1440,"desktop"],[320,"mobile-320"]] as const){await page.setViewportSize({width,height:900});await page.screenshot({path:info.outputPath(`costing-service-${name}.png`),fullPage:true});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);}
 }};
}
