import {test,expect,type Page} from "@playwright/test";
import {randomUUID} from "node:crypto";
import {seedAccount,login,expectReady} from "./local-auth";
import {costingSnapshot,profitabilityBreakdown} from "@/lib/costing/model";
test.use({actionTimeout:20000});
const now=()=>new Date().toISOString();
async function setup(page:Page){const account=await seedAccount();await login(page,account);await expectReady(page);const c=(await(await page.request.get('/api/session')).json()).context;const headers={origin:'http://127.0.0.1:4173','x-workspace-reference':`${c.membership_id}:${c.location_id}`};const call=async(route:string,q:object)=>{const r=await page.request.post(route,{headers,data:{mutation_id:randomUUID(),...q}});expect(r.status(),await r.text()).toBe(200);return(await r.json()).data;};const cr=await page.request.post('/api/clients',{headers,data:{operation:'create',payload:{full_name:'Sentetik maliyet müşterisi',phone:'05321118877',phone_region:'TR',request_id:randomUUID()}}});expect(cr.status()).toBe(200);const client=(await cr.json()).data;await call('/api/finance',{type:'CURRENCY_SET',currency:'TRY',expected_version:0,reason:'Confirmed currency'});return{account,client,call};}
async function detail(page:Page,id:string){const r=await page.request.get('/api/costing?charge_id='+id);expect(r.status(),await r.text()).toBe(200);return profitabilityBreakdown.parse(costingSnapshot.parse((await r.json()).data).items[0]);}
const local=()=>{const d=new Date();return new Date(+d-d.getTimezoneOffset()*60000).toISOString().slice(0,23);};
test('cost-bearing acquisition UI, retail contribution, permanent replay, reversal and 320px',async({page},info)=>{
 test.setTimeout(180000);const f=await setup(page);await f.call('/api/stock',{type:'ENABLE',reason:'Measured stock'});const item=randomUUID();await f.call('/api/stock',{type:'ITEM_SAVE',id:item,expected_version:0,definition:{source:'SALON_CUSTOM_OPERATIONAL_PRODUCT',catalog_product_id:null,product_type:'SHAMPOO',display_name:'Ölçülmüş bakım ürünü',sku:null,barcode:null,inventory_unit:'UNIT',active:true,track_quantity:true,lot_required:false,low_threshold:1},reason:'Operational item'});
 await page.goto('/workspace/finance/profitability');await page.getByRole('button',{name:'Maliyet temeli',exact:true}).click();await page.getByRole('combobox',{name:'Stok ürünü',exact:true}).selectOption(item);const form=page.locator('form').filter({has:page.getByRole('button',{name:'Maliyetli girişi kaydet'})});await form.getByRole('combobox',{name:'Giriş türü',exact:true}).selectOption('OPENING');await form.getByLabel('Giriş miktarı').fill('10');await form.getByLabel('Toplam edinim maliyeti').fill('200');await form.getByLabel('Gerekçe',{exact:true}).fill('Measured opening acquisition');await form.getByRole('button',{name:'Maliyetli girişi kaydet'}).click();await expect(page.getByText('v1 · Maliyet biliniyor · Konum / ürün havuzu')).toBeVisible();
 const sale=await f.call('/api/finance',{type:'RETAIL_SALE',id:randomUUID(),client_id:f.client.id,currency:'TRY',stock_item_id:item,lot_id:null,quantity:'2',unit_price_minor:'10000',tax_rate_bps:0,tax_inclusive:true,description:'Gerçek perakende katkısı',occurred_at:now(),reason:'Actual sale'});const d=await detail(page,sale.id);expect(d.direct_product_cost_minor).toBe('4000');expect(d.gross_contribution_minor).toBe('16000');expect(d.commission_minor).toBe('0');
 await page.goto('/workspace/finance/profitability?charge_id='+sale.id);await expect(page.getByRole('heading',{name:'Nasıl hesaplandı?'})).toBeVisible();for(const [width,name]of [[1440,'desktop'],[320,'mobile-320']]as const){await page.setViewportSize({width,height:900});await page.screenshot({path:info.outputPath(`costing-retail-${name}.png`),fullPage:true});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);}
 const reverse={type:'REVERSAL',id:randomUUID(),document_id:sale.id,mutation_id:randomUUID(),reason:'Mistaken retail sale'};await f.call('/api/finance',reverse);await f.call('/api/finance',reverse);const end=await detail(page,sale.id);expect(end.net_revenue_minor).toBe('0');expect(end.direct_product_cost_minor).toBe('0');expect(end.gross_contribution_minor).toBe('0');expect(end.cost_facts).toHaveLength(2);
});
test('policy and assignment UI, immutable future versions, unknown cost, explicit zero and refund commission',async({page},info)=>{
 test.setTimeout(180000);const f=await setup(page);await f.call('/api/salon',{type:'HOURS_SAVE',expected_version:0,days:Array.from({length:7},(_,i)=>({day:i+1,closed:false,opens:540,closes:1080}))});await f.call('/api/salon',{type:'STAFF_SAVE',membership_id:f.account.membershipId,expected_version:0,definition:{display_name:'Maliyet uzmanı',active:true,bookable:true,working_capacity:null,notes:null,competencies:[],shifts:Array.from({length:7},(_,i)=>({day:i+1,type:'SHIFT',starts:540,ends:1080}))}});const sid=randomUUID();await f.call('/api/salon',{type:'SERVICE_SAVE',id:sid,expected_version:0,definition:{name:'Kaynaklı hizmet',category:'CARE',description:null,organization_wide:false,base_duration_minutes:60,buffer_before_minutes:0,buffer_after_minutes:0,base_price:1000,tax_rate:20,tax_inclusive:false,requires_colorlab:false,requires_hair_passport:false,requires_precheck:false,active:true,eligible_membership_ids:[f.account.membershipId],capabilities:[],resources:[]}});
 await page.goto('/workspace/finance/profitability');await page.getByRole('button',{name:'Politika ve atamalar'}).click();const policy=page.locator('form').filter({has:page.getByRole('button',{name:'Politika sürümünü kaydet'})});await policy.getByLabel('Ad',{exact:true}).fill('Gelecek hizmet oranı');await policy.getByLabel('Oran (%)').fill('10');await policy.getByLabel('Gerekçe',{exact:true}).fill('Reviewed future rate');await policy.getByRole('button',{name:'Politika sürümünü kaydet'}).click();await expect(policy.getByRole('combobox',{name:'Politika',exact:true}).locator('option').filter({hasText:'Gelecek hizmet oranı'})).toHaveCount(1);const ps=costingSnapshot.parse((await(await page.request.get('/api/costing?kind=POLICIES')).json()).data),pid=ps.policies[0]!.id;const assignment=page.locator('form').filter({has:page.getByRole('button',{name:'Atamayı kaydet'})});await assignment.getByRole('combobox',{name:'İşlemi yapan çalışan',exact:true}).selectOption(f.account.userId);await assignment.getByRole('combobox',{name:'Atanacak politika',exact:true}).selectOption(pid);await assignment.getByRole('combobox',{name:'Kapsam',exact:true}).selectOption('DEFAULT_SERVICE');await assignment.getByLabel('Gerekçe',{exact:true}).fill('Explicit performer');await assignment.getByRole('button',{name:'Atamayı kaydet'}).click();await expect(page.getByText(new RegExp(f.account.userId+' · DEFAULT_SERVICE'))).toBeVisible();
 const charge=async(day:string)=>{const ap=await f.call('/api/salon',{type:'APPOINTMENT_SAVE',id:randomUUID(),expected_version:0,definition:{client_id:f.client.id,service_id:sid,staff_membership_id:f.account.membershipId,local_start:day,utc_offset_minutes:null,scheduled_duration_minutes:null,adjustment_reason:null,notes:null,status:'CONFIRMED'}});for(const[v,status]of [[1,'ARRIVED'],[2,'IN_SERVICE'],[3,'COMPLETED']])await f.call('/api/salon',{type:'APPOINTMENT_TRANSITION',id:ap.id,expected_version:v,status,reason:'Real completion'});return await f.call('/api/finance',{type:'SERVICE_CHARGE',id:randomUUID(),appointment_id:ap.id,reason:'Stored quote'});};
 const one=await charge('2026-10-13T10:00');expect((await detail(page,one.id)).commission_minor).toBe('10000');await page.goto('/workspace/finance/profitability?charge_id='+one.id);await expect(page.getByText('Maliyet eksik — katkı hesaplanamaz',{exact:true})).toBeVisible();const zero=page.locator('form').filter({has:page.getByRole('button',{name:'Sıfır tüketim doğrulaması kaydet'})});await zero.getByRole('checkbox').check();await zero.getByLabel('Gerekçe',{exact:true}).fill('Consultation-only service; verified no physical product');await zero.getByRole('button',{name:'Sıfır tüketim doğrulaması kaydet'}).click();await expect(page.getByText('Hesap tamam',{exact:true})).toBeVisible();expect((await detail(page,one.id)).contribution_after_commission_minor).toBe('90000');
 await page.getByRole('button',{name:'Politika ve atamalar'}).click();await policy.getByRole('combobox',{name:'Politika',exact:true}).selectOption(pid);await policy.getByLabel('Oran (%)').fill('20');await policy.getByLabel('Yürürlük başlangıcı').fill(local());await policy.getByLabel('Gerekçe',{exact:true}).fill('Future revised rate');await policy.getByRole('button',{name:'Politika sürümünü kaydet'}).click();await expect(policy.getByRole('combobox',{name:'Politika',exact:true}).locator('option').filter({hasText:'v2'})).toHaveCount(1);const two=await charge('2026-10-14T10:00');expect((await detail(page,two.id)).commission_minor).toBe('20000');expect((await detail(page,one.id)).commission_accrual?.policy_version).toBe(1);
 const p=await f.call('/api/finance',{type:'PAYMENT',id:randomUUID(),client_id:f.client.id,currency:'TRY',amount_minor:'120000',method:'CARD',appointment_id:null,external_reference:null,occurred_at:now(),allocations:[{charge_id:one.id,amount_minor:'120000'}],confirm_credit:false,reason:'Actual payment'});await f.call('/api/finance',{type:'REFUND',id:randomUUID(),original_payment_id:p.id,amount_minor:'60000',occurred_at:now(),reason:'Actual half refund'});const refund=await detail(page,one.id);expect(refund.net_revenue_minor).toBe('50000');expect(refund.commission_minor).toBe('5000');expect(refund.commission_adjustments).toHaveLength(1);expect(refund.contribution_after_commission_minor).toBe('45000');await page.goto('/workspace/commission');await expect(page.getByRole('heading',{name:'Komisyon tahakkukları',exact:true})).toBeVisible();await page.screenshot({path:info.outputPath('costing-commission-desktop.png'),fullPage:true});
});
test('reception and technical users cannot access private cost or another staff earnings',async({page,browser})=>{const f=await setup(page);for(const role of ['reception','colorist']as const){const member=await f.account.addMember(role),bc=await browser.newContext(),p=await bc.newPage();try{await login(p,member);await expectReady(p);expect((await p.request.get('/api/costing')).status()).toBe(403);expect((await p.request.get('/api/costing?kind=COMMISSION_ALL')).status()).toBe(403);expect((await p.request.get('/api/costing?kind=COMMISSION_SELF&staff_user_id='+f.account.userId)).status()).toBe(403);if(role==='colorist'){await p.goto('/workspace/commission');await expect(p.getByText('Bu dönemde komisyon tahakkuku yok.')).toBeVisible();}}finally{await bc.close();}}});
