import {test,expect,type Page} from "@playwright/test";
import {randomUUID} from "node:crypto";
import {seedAccount,login,expectReady} from "./local-auth";
import {financeSnapshot} from "@/lib/finance/model";
test.use({actionTimeout:20000});
async function context(page:Page){const r=await page.request.get('/api/session');expect(r.status()).toBe(200);return (await r.json()).context;}
async function op(page:Page,q:object,route='/api/finance'){const c=await context(page),r=await page.request.post(route,{headers:{origin:'http://127.0.0.1:4173','x-workspace-reference':`${c.membership_id}:${c.location_id}`},data:{mutation_id:randomUUID(),...q}});return {status:r.status(),body:await r.json()};}
async function read(page:Page,query=''){const r=await page.request.get('/api/finance'+query);expect(r.status()).toBe(200);return financeSnapshot.parse((await r.json()).data);}
const now=()=>new Date().toISOString();
test('retail sale consumes existing stock once and exposes finance provenance',async({page})=>{const f=await setup(page);const stock=async(q:object)=>{const r=await op(page,q,'/api/stock');expect(r.status,JSON.stringify(r.body)).toBe(200);return r.body.data;};await stock({type:'ENABLE',reason:'Measured inventory cutover'});const item=randomUUID();await stock({type:'ITEM_SAVE',id:item,expected_version:0,reason:'Real salon retail item',definition:{source:'SALON_CUSTOM_OPERATIONAL_PRODUCT',catalog_product_id:null,product_type:'SHAMPOO',display_name:'Salon bakım ürünü',sku:'FIN-SYN',barcode:null,inventory_unit:'UNIT',active:true,track_quantity:true,lot_required:false,low_threshold:1}});await stock({type:'OPENING',stock_item_id:item,lot_id:null,quantity:10,unit:'UNIT',occurred_at:now(),reference:null,reason:'Measured opening'});await page.goto('/workspace/finance');await page.getByRole('button',{name:'Perakende satış',exact:true}).click();const form=page.locator('form.stock-form');await form.getByLabel('Müşteri',{exact:true}).selectOption(f.client.id);await form.getByLabel('Stok ürünü').selectOption(item);await form.getByLabel('Miktar',{exact:true}).fill('2');await form.getByLabel('Birim fiyat').fill('12.55');await form.getByLabel('Açıklama',{exact:true}).fill('Bakım ürünü satışı');await form.getByLabel('Gerekçe',{exact:true}).fill('Confirmed retail sale');await form.getByRole('button',{name:'Kaydet',exact:true}).click();await expect(form).toHaveCount(0);const sale=(await read(page)).documents.find(d=>d.type==='RETAIL_SALE')!;expect(sale.amount_minor).toBe('2510');const sr=await page.request.get(`/api/stock?item_id=${item}`);expect(sr.status()).toBe(200);const s=(await sr.json()).data;expect(s.items[0].on_hand).toBe(8);expect(s.movements.filter((m:{finance_document_id:string|null})=>m.finance_document_id===sale.id)).toHaveLength(1);await page.goto(`/workspace/stock?item_id=${item}`);await expect(page.getByRole('link',{name:'Perakende satış',exact:true})).toBeVisible();await page.getByRole('link',{name:'Perakende satış',exact:true}).click();await expect(page.getByRole('heading',{name:'İşlem detayı',exact:true})).toBeVisible();});
test('foreign financial identity and forged server money fields are rejected',async({page,browser})=>{const f=await setup(page),c=await f.write(charge(f.client.id));expect((await op(page,{...payment(f.client.id,'100'),cash_expected_minor:'0'})).status).toBe(400);const other=await seedAccount(),bc=await browser.newContext(),p=await bc.newPage();await login(p,other);await expectReady(p);expect((await p.request.get(`/api/finance?document_id=${c.id}`)).status()).toBe(404);await bc.close();});
async function setup(page:Page){const account=await seedAccount();await login(page,account);await expectReady(page);const c=await context(page),r=await page.request.post('/api/clients',{headers:{origin:'http://127.0.0.1:4173','x-workspace-reference':`${c.membership_id}:${c.location_id}`},data:{operation:'create',payload:{full_name:'Deniz Finance',phone:'05321112233',phone_region:'TR',request_id:randomUUID()}}});expect(r.status()).toBe(200);const client=(await r.json()).data;const write=async(q:object)=>{const r=await op(page,q);expect(r.status,JSON.stringify(r.body)).toBe(200);return r.body.data;};await write({type:'CURRENCY_SET',currency:'TRY',expected_version:0,reason:'Confirmed organization currency'});return {account,client,write};}
const charge=(client_id:string,n='100000')=>({type:'MANUAL_CHARGE',id:randomUUID(),client_id,currency:'TRY',amount_minor:n,tax_rate_bps:2000,tax_inclusive:true,description:'Renk hizmeti',occurred_at:now(),reason:'Explicit service charge'});
const payment=(client_id:string,n:string,allocations:object[]=[],method='CARD',deposit=false)=>({type:deposit?'DEPOSIT':'PAYMENT',id:randomUUID(),client_id,currency:'TRY',amount_minor:n,method,appointment_id:null,external_reference:null,occurred_at:now(),reason:'Measured payment',...(deposit?{}:{allocations,confirm_credit:true})});
async function openCash(f:Awaited<ReturnType<typeof setup>>){const id=randomUUID();await f.write({type:'CASH_OPEN',id,currency:'TRY',opening_cash_minor:'10000',reason:'Measured opening'});return id;}
test('real finance forms: partial and split payment, deposit, refund, expense and 320px captures',async({page},info)=>{
 test.setTimeout(180000);const f=await setup(page);await openCash(f);await page.goto('/workspace/finance');await expect(page.getByRole('heading',{name:'Salon finansı',exact:true})).toBeVisible();
 const form=page.locator('form.stock-form');const save=async(reason:string)=>{await form.getByLabel('Gerekçe',{exact:true}).fill(reason);await form.getByRole('button',{name:'Kaydet',exact:true}).click();await expect(form).toHaveCount(0);};
 await page.getByRole('button',{name:'Manuel hizmet ücreti',exact:true}).click();await form.getByLabel('Müşteri',{exact:true}).selectOption(f.client.id);await form.getByLabel('Tutar',{exact:true}).fill('1000');await form.getByLabel('Açıklama',{exact:true}).fill('Renk hizmeti');await form.getByLabel('Vergi oranı (%)').fill('20');await save('Confirmed manual service');
 const d=(await read(page)).documents.find(d=>d.type==='SERVICE_CHARGE')!;expect(d.amount_minor).toBe('100000');expect(d.tax_amount_minor).toBe('16667');
 await page.getByRole('button',{name:'Ödeme',exact:true}).click();await form.getByLabel('Müşteri',{exact:true}).selectOption(f.client.id);await form.getByLabel('Tutar',{exact:true}).fill('600');await form.getByLabel('Ödeme yöntemi').selectOption('CARD');await form.getByLabel('Ücret 1',{exact:true}).selectOption(d.id);await form.getByLabel('Dağıtılacak tutar 1').fill('600');await save('Partial card payment');expect((await read(page)).client_balances[0]!.balance_minor).toBe('40000');
 await page.getByRole('button',{name:'Depozito',exact:true}).click();await form.getByLabel('Müşteri',{exact:true}).selectOption(f.client.id);await form.getByLabel('Tutar',{exact:true}).fill('100');await form.getByLabel('Ödeme yöntemi').selectOption('BANK_TRANSFER');await save('Advance bank payment');
 const deposit=(await read(page)).documents.find(d=>d.type==='DEPOSIT')!;await page.getByRole('button',{name:'Kredi uygula',exact:true}).click();await form.getByLabel('Müşteri',{exact:true}).selectOption(f.client.id);await form.getByLabel('Kullanılabilir kredi').selectOption(deposit.id);await form.getByLabel('Ücret 1',{exact:true}).selectOption(d.id);await form.getByLabel('Dağıtılacak tutar 1').fill('100');await save('Explicit deposit allocation');
 await page.getByRole('button',{name:'Ödeme',exact:true}).click();await form.getByLabel('Müşteri',{exact:true}).selectOption(f.client.id);await form.getByLabel('Tutar',{exact:true}).fill('300');await form.getByLabel('Ödeme yöntemi').selectOption('CASH');await form.getByLabel('Ücret 1',{exact:true}).selectOption(d.id);await form.getByLabel('Dağıtılacak tutar 1').fill('300');await save('Cash split completion');expect((await read(page)).client_balances[0]!.balance_minor).toBe('0');
 const card=(await read(page)).documents.find(d=>d.type==='PAYMENT'&&d.method==='CARD')!;await page.getByRole('button',{name:'Para iadesi',exact:true}).click();await form.getByLabel('Orijinal ödeme').selectOption(card.id);await form.getByLabel('Tutar',{exact:true}).fill('200');await save('Actual partial refund');expect((await read(page)).client_balances[0]!.balance_minor).toBe('20000');
 await page.getByRole('button',{name:'Gider',exact:true}).click();await form.getByLabel('Tutar',{exact:true}).fill('50');await form.getByLabel('Ödeme yöntemi').selectOption('CASH');await form.getByLabel('Açıklama',{exact:true}).fill('Salon sarf malzemesi');await save('Recorded supply expense');expect((await read(page)).cash_sessions[0]!.current_expected_minor).toBe('35000');
 for(const [width,name] of [[1440,'desktop'],[320,'mobile-320']] as const){await page.setViewportSize({width,height:900});await page.evaluate(()=>{if(document.activeElement instanceof HTMLElement)document.activeElement.blur();window.scrollTo(0,0);});await page.screenshot({path:info.outputPath(`finance-overview-${name}.png`),fullPage:true});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);}
 await page.getByRole('button',{name:'Renk hizmeti',exact:true}).click();await expect(page.getByRole('heading',{name:'İşlem detayı',exact:true})).toBeVisible();await page.screenshot({path:info.outputPath('finance-detail-mobile-320.png'),fullPage:true});
});
test('cash discrepancy is explicit and close never adds automatic adjustment',async({page})=>{const f=await setup(page),id=await openCash(f);await page.goto('/workspace/finance');await page.getByRole('button',{name:'Kasa sayımını gönder'}).click();await page.getByLabel('Sayılan nakit').fill('95');await page.getByLabel('Gerekçe',{exact:true}).fill('Measured shortage');await page.getByRole('button',{name:'Kaydet',exact:true}).click();await expect(page.getByText(/Fark:.*Eksik/)).toBeVisible();const rejected=await op(page,{type:'CASH_CLOSE_CONFIRM',id,expected_version:2,acknowledge_difference:false,reason:'Not acknowledged'});expect(rejected.body.code).toBe('CASH_DIFFERENCE_ACK_REQUIRED');await page.getByLabel('Kasa farkını gördüm; dengeleme kaydı yapılmayacak.').check();await page.getByLabel('Kapanış gerekçesi').fill('Shortage reviewed');await page.getByRole('button',{name:'Kasayı kapat',exact:true}).click();await expect(page.getByText('Açık kasa yok.',{exact:true})).toBeVisible();const data=await read(page);expect(data.cash_sessions[0]!.difference_minor).toBe('-500');expect(data.documents).toHaveLength(0);});
test('permanent payment replay and over-allocation preserve original facts',async({page})=>{const f=await setup(page),c=await f.write(charge(f.client.id,'1000')),q={...payment(f.client.id,'600',[{charge_id:c.id,amount_minor:'600'}]),mutation_id:randomUUID()};const one=await op(page,q),two=await op(page,q);expect(one.status).toBe(200);expect(two.body.data).toEqual(one.body.data);expect((await op(page,{...q,amount_minor:'601'})).status).toBe(409);const over=await op(page,payment(f.client.id,'401',[{charge_id:c.id,amount_minor:'401'}]));expect(over.body.code).toBe('FINANCE_ALLOCATION_CONFLICT');expect((await read(page)).documents.filter(d=>d.type==='PAYMENT')).toHaveLength(1);});
test('refund limits and administrative reversal are separate',async({page})=>{const f=await setup(page),p=await f.write(payment(f.client.id,'1000'));await f.write({type:'REFUND',id:randomUUID(),original_payment_id:p.id,amount_minor:'400',occurred_at:now(),reason:'Actual money returned'});expect((await op(page,{type:'REFUND',id:randomUUID(),original_payment_id:p.id,amount_minor:'601',occurred_at:now(),reason:'Excess return'})).body.code).toBe('FINANCE_REFUND_LIMIT');expect((await op(page,{type:'REVERSAL',id:randomUUID(),document_id:p.id,reason:'Cannot erase refunded history'})).body.code).toBe('FINANCE_CONFLICT');const credit=await f.write(charge(f.client.id,'1000'));await f.write({type:'REVERSAL',id:randomUUID(),document_id:credit.id,reason:'Mistaken charge'});const d=(await read(page)).documents;expect(d.find(x=>x.id===credit.id)!.amount_minor).toBe('1000');expect(d.find(x=>x.id===credit.id)!.reversed).toBe(true);});
test('reception may record payments but expenses and discrepancy remain private',async({page,browser})=>{const f=await setup(page);await openCash(f);await f.write({type:'EXPENSE',id:randomUUID(),currency:'TRY',amount_minor:'500',method:'CARD',category:'OTHER',description:'Private operational expense',stock_receipt_id:null,external_reference:null,occurred_at:now(),reason:'Private management note'});const reception=await f.account.addMember('reception'),bc=await browser.newContext(),p=await bc.newPage();await login(p,reception);await expectReady(p);await p.goto('/workspace/finance');await expect(p.getByRole('heading',{name:'Salon finansı',exact:true})).toBeVisible();await expect(p.getByRole('button',{name:'Ödeme',exact:true})).toBeVisible();await expect(p.getByRole('button',{name:'Gider',exact:true})).toHaveCount(0);const data=await read(p);expect(data.summary.expenses_minor).toBeNull();expect(data.cash_sessions[0]).not.toHaveProperty('difference_minor');expect(data.documents.some(d=>d.description==='Private operational expense')).toBe(false);await bc.close();});
test('technical staff denied full finance and revoked owner conceals loaded balances',async({page,browser})=>{const f=await setup(page);await f.write(charge(f.client.id));const technical=await f.account.addMember('colorist'),bc=await browser.newContext(),p=await bc.newPage();await login(p,technical);await expectReady(p);expect((await p.request.get('/api/finance')).status()).toBe(403);await bc.close();await page.goto('/workspace/finance');await expect(page.getByText('Deniz Finance',{exact:true}).last()).toBeVisible();await f.account.revoke();await page.evaluate(()=>window.dispatchEvent(new Event('focus')));await expect(page).toHaveURL(/\/workspaces/,{timeout:25000});await expect(page.getByText('Deniz Finance',{exact:true})).toHaveCount(0);});
test('completed appointment uses stored quote even after service price changes',async({page})=>{test.setTimeout(180000);const f=await setup(page);const save=async(q:object)=>{const r=await op(page,q,'/api/salon');expect(r.status,JSON.stringify(r.body)).toBe(200);return r.body.data;};await save({type:'HOURS_SAVE',expected_version:0,days:Array.from({length:7},(_,i)=>({day:i+1,closed:false,opens:540,closes:1080}))});await save({type:'STAFF_SAVE',membership_id:f.account.membershipId,expected_version:0,definition:{display_name:'Elif Finance',active:true,bookable:true,working_capacity:null,notes:null,competencies:[],shifts:Array.from({length:7},(_,i)=>({day:i+1,type:'SHIFT',starts:540,ends:1080}))}});const service=randomUUID(),definition={name:'Tarihsel hizmet',category:'CARE',description:null,organization_wide:false,base_duration_minutes:60,buffer_before_minutes:0,buffer_after_minutes:0,base_price:1000,tax_rate:20,tax_inclusive:false,requires_colorlab:false,requires_hair_passport:false,requires_precheck:false,active:true,eligible_membership_ids:[f.account.membershipId],capabilities:[],resources:[]};await save({type:'SERVICE_SAVE',id:service,expected_version:0,definition});const ap=await save({type:'APPOINTMENT_SAVE',id:randomUUID(),expected_version:0,definition:{client_id:f.client.id,service_id:service,staff_membership_id:f.account.membershipId,local_start:'2026-10-12T10:00',utc_offset_minutes:null,scheduled_duration_minutes:null,adjustment_reason:null,notes:null,status:'CONFIRMED'}});expect((await op(page,{type:'SERVICE_CHARGE',id:randomUUID(),appointment_id:ap.id,reason:'Premature charge'})).body.code).toBe('SERVICE_NOT_COMPLETED');for(const [version,status] of [[1,'ARRIVED'],[2,'IN_SERVICE'],[3,'COMPLETED']] as const)await save({type:'APPOINTMENT_TRANSITION',id:ap.id,expected_version:version,status,reason:'Controlled completion'});await save({type:'SERVICE_SAVE',id:service,expected_version:1,definition:{...definition,base_price:2000}});await page.goto('/workspace/finance');await page.getByRole('button',{name:'Hizmet ücreti',exact:true}).click();await page.getByLabel('Tamamlanmış randevu').selectOption(ap.id);await page.getByLabel('Gerekçe',{exact:true}).fill('Use completed appointment quote');await page.getByRole('button',{name:'Kaydet',exact:true}).click();await expect(page.locator('form.stock-form')).toHaveCount(0);const d=(await read(page,`?appointment_id=${ap.id}`)).documents[0]!;expect(d.amount_minor).toBe('120000');expect(d.service_name_snapshot).toBe('Tarihsel hizmet');expect(d.performed_by).not.toBeNull();expect(d.live_session_id).toBeNull();});
