import { expect,test,type Page } from "@playwright/test";
import { randomUUID } from "node:crypto";
import { seedAccount,login,expectReady } from "./local-auth";
import { salonSnapshot,appointment,precheckResult,slotResult } from "@/lib/salon/model";
async function session(page:Page){const r=await page.request.get("/api/session");expect(r.status()).toBe(200);return (await r.json()).context;}
async function op(page:Page,command:object){const c=await session(page);const r=await page.request.post("/api/salon",{headers:{origin:"http://127.0.0.1:4173","x-workspace-reference":`${c.membership_id}:${c.location_id}`},data:{mutation_id:randomUUID(),...command}});return {status:r.status(),body:await r.json()};}
async function seed(page:Page){
 const account=await seedAccount(),second=await account.addMember("colorist");await login(page,account);await expectReady(page);
 const c=await session(page),r=await page.request.post("/api/clients",{headers:{origin:"http://127.0.0.1:4173","x-workspace-reference":`${c.membership_id}:${c.location_id}`},data:{operation:"create",payload:{full_name:"Deniz Operations",phone:"05321112233",phone_region:"TR",request_id:randomUUID()}}});expect(r.status()).toBe(200);const client=(await r.json()).data;
 const serviceId=randomUUID(),resourceId=randomUUID();
 const save=async(q:object)=>{const result=await op(page,q);expect(result.status,JSON.stringify(result.body)).toBe(200);return result.body.data;};
 await save({type:"HOURS_SAVE",expected_version:0,days:Array.from({length:7},(_,i)=>({day:i+1,closed:false,opens:540,closes:1080}))});
 for(const [membership_id,display_name] of [[account.membershipId,"Elif Operations"],[second.membershipId,"Merve Operations"]])await save({type:"STAFF_SAVE",membership_id,expected_version:0,definition:{display_name,active:true,bookable:true,working_capacity:null,notes:null,competencies:[{code:"GENERAL_COLOR",level:"INDEPENDENT"}],shifts:[...Array.from({length:7},(_,i)=>({day:i+1,type:"SHIFT",starts:540,ends:1080})),{day:1,type:"BREAK",starts:720,ends:780}]}});
 await save({type:"RESOURCE_SAVE",id:resourceId,expected_version:0,definition:{name:"Renk koltuğu",type:"CHAIR",capacity:1,active:true}});
 await save({type:"SERVICE_SAVE",id:serviceId,expected_version:0,definition:{name:"Renk danışmanlığı",category:"COLOR",description:"Yerel test hizmeti",organization_wide:false,base_duration_minutes:60,buffer_before_minutes:5,buffer_after_minutes:10,base_price:1000,tax_rate:20,tax_inclusive:false,requires_colorlab:true,requires_hair_passport:true,requires_precheck:true,active:true,eligible_membership_ids:[account.membershipId,second.membershipId],capabilities:[{code:"GENERAL_COLOR",level:"INDEPENDENT"}],resources:[{type:"CHAIR",units:1}]}});
 const booking=(id:string,start:string,member=account.membershipId)=>({type:"APPOINTMENT_SAVE",id,expected_version:0,definition:{client_id:client.id,service_id:serviceId,staff_membership_id:member,local_start:start,utc_offset_minutes:null,scheduled_duration_minutes:null,adjustment_reason:null,notes:null,status:"CONFIRMED"}});
 return {account,second,client,serviceId,resourceId,save,booking};
}
test("real salon forms, calendar, precheck and immutable appointment lifecycle",async({page},info)=>{
 test.setTimeout(180000);const f=await seed(page);
 await page.goto("/workspace/team");await expect(page.getByRole("heading",{name:"Salon ekibi",exact:true})).toBeVisible();await expect(page.getByRole("heading",{name:"Elif Operations"})).toBeVisible();await page.screenshot({path:info.outputPath("client-salon-team.png"),fullPage:true});
 await page.getByRole("button",{name:"Personeli düzenle"}).first().click();const staff=page.getByRole("dialog");await staff.getByLabel("Notlar",{exact:true}).fill("Plan onaylandı");await staff.getByRole("button",{name:"Değişiklikleri kaydet"}).click();await expect(staff).toHaveCount(0);await expect(page.getByText("Plan onaylandı")).toBeVisible();
 await page.goto("/workspace/settings");await expect(page.getByRole("heading",{name:"Hizmet kataloğu"})).toBeVisible();await page.getByRole("button",{name:"Hizmeti düzenle"}).click();const service=page.getByRole("dialog");await expect(service.getByLabel("Hizmet adı")).toHaveValue("Renk danışmanlığı");await service.getByLabel("Açıklama",{exact:true}).fill("Kalıcı hizmet açıklaması");await service.getByRole("button",{name:"Değişiklikleri kaydet"}).click();await expect(service).toHaveCount(0);await expect(page.getByText("Kalıcı hizmet açıklaması")).toBeVisible();await page.screenshot({path:info.outputPath("client-salon-services.png"),fullPage:true});
 await page.getByRole("button",{name:"Çalışma saatleri",exact:true}).click();await expect(page.getByLabel("Pazartesi açılış")).toHaveValue("09:00");await page.screenshot({path:info.outputPath("client-salon-hours.png"),fullPage:true});
 await page.goto("/workspace/appointments");await page.getByLabel("Takvim başlangıcı").fill("2026-10-12");await expect(page.getByText("Bu aralıkta kayıtlı randevu yok.")).toBeVisible();await page.getByRole("button",{name:"Randevu oluştur",exact:true}).click();const dialog=page.getByRole("dialog");await dialog.getByLabel("Müşteri ara",{exact:true}).fill("Deniz");await dialog.getByRole("button",{name:"Deniz Operations",exact:true}).click();await dialog.getByLabel("Hizmet",{exact:true}).selectOption(f.serviceId);await dialog.getByLabel("Personel",{exact:true}).selectOption(f.account.membershipId);await dialog.getByLabel("Başlangıç (Europe/Istanbul)").fill("2026-10-12T10:00");await dialog.getByLabel("Durum",{exact:true}).selectOption("CONFIRMED");await dialog.getByRole("button",{name:"Randevuyu kaydet"}).click();await expect(dialog).toHaveCount(0);
 const event=page.getByRole("button",{name:/10:00 · Deniz Operations/});await expect(event).toBeVisible();await event.click();await expect(page.getByRole("heading",{name:"Deniz Operations",exact:true})).toBeVisible();await page.getByRole("button",{name:"Teknik ön kontrol",exact:true}).click();await expect(page.getByText("Bilgi gerekli",{exact:true})).toBeVisible();await expect(page.getByText("Ön kontrol reçete oluşturmaz.")).toBeVisible();await page.screenshot({path:info.outputPath("client-salon-appointments.png"),fullPage:true});
 const snapshot=salonSnapshot.parse((await (await page.request.get("/api/salon?from=2026-10-12&to=2026-10-18")).json()).data);const a=snapshot.appointments[0]!;
 const check=await page.request.get(`/api/salon/appointments/${a.id}/precheck`);expect(check.status()).toBe(200);const pre=precheckResult.parse((await check.json()).data);expect(pre.recipe_created).toBe(false);expect(pre.last_formula).toBeNull();expect(pre.statuses).toContain("INFORMATION_REQUIRED");
 await page.getByRole("link",{name:"ColorLab’ı aç",exact:true}).click();await expect(page.getByLabel("Renk planı müşterisi")).toHaveValue(f.client.id);await page.goto("/workspace/appointments");await page.getByLabel("Takvim başlangıcı").fill("2026-10-12");await page.getByRole("button",{name:/10:00 · Deniz Operations/}).click();
 expect((await op(page,f.booking(randomUUID(),"2026-10-12T10:30"))).body.code).toBe("STAFF_DOUBLE_BOOKED");expect((await op(page,f.booking(randomUUID(),"2026-10-12T12:00"))).body.code).toBe("STAFF_UNAVAILABLE");
 await page.getByLabel("Durum değişikliği gerekçesi").fill("Müşteri geldi");await page.getByRole("button",{name:"Salonda",exact:true}).click();await expect(page.getByText("Salonda",{exact:true}).first()).toBeVisible();
 const transition=async(expected_version:number,status:string)=>appointment.parse(await f.save({type:"APPOINTMENT_TRANSITION",id:a.id,expected_version,status,reason:"Yerel test durum geçişi"}));await transition(2,"IN_SERVICE");const completed=await transition(3,"COMPLETED");expect(completed.actual_duration_seconds).toBeGreaterThanOrEqual(0);expect((await op(page,{...f.booking(a.id,"2026-10-12T14:00"),expected_version:4})).body.code).toBe("APPOINTMENT_IMMUTABLE");
 await page.setViewportSize({width:320,height:740});await page.goto("/workspace/appointments");await page.getByLabel("Takvim başlangıcı").fill("2026-10-12");await expect(page.getByRole("button",{name:/Deniz Operations/})).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);await page.screenshot({path:info.outputPath("client-salon-mobile-320.png"),fullPage:true});
 await f.account.revoke();await page.evaluate(()=>window.dispatchEvent(new Event("focus")));await expect(page).toHaveURL(/\/workspaces/,{timeout:20000});await expect(page.getByText("Deniz Operations")).toHaveCount(0);
});
test("atomic staff and resource reservations, permanent retry, slots and tenant concealment",async({page,browser})=>{
 test.setTimeout(180000);const f=await seed(page),mutation_id=randomUUID(),id=randomUUID(),q={...f.booking(id,"2026-10-12T10:00"),mutation_id};const first=await op(page,q);expect(first.status).toBe(200);expect((await op(page,q)).body.data.id).toBe(id);expect((await op(page,{...q,definition:{...q.definition,local_start:"2026-10-12T14:00"}})).body.code).toBe("SALON_CONFLICT");
 const races=await Promise.all([op(page,f.booking(randomUUID(),"2026-10-12T15:00")),op(page,f.booking(randomUUID(),"2026-10-12T15:00",f.second.membershipId))]);expect(races.map(r=>r.status).sort()).toEqual([200,409]);expect(races.find(r=>r.status===409)!.body.code).toBe("RESOURCE_UNAVAILABLE");
 const c=await session(page),slots=await page.request.post("/api/salon/slots",{headers:{origin:"http://127.0.0.1:4173","x-workspace-reference":`${c.membership_id}:${c.location_id}`},data:{client_id:f.client.id,service_id:f.serviceId,staff_membership_id:f.account.membershipId,from_date:"2026-10-12",to_date:"2026-10-18",duration_minutes:null,limit:20}});expect(slots.status()).toBe(200);const choices=slotResult.parse((await slots.json()).data);expect(choices.candidates_checked).toBeLessThanOrEqual(672);expect(choices.slots.length).toBeGreaterThan(0);expect(choices.slots.every(s=>s.utc_offset_minutes===180)).toBe(true);
 const other=await browser.newContext(),p=await other.newPage();await login(p,await seedAccount());await expectReady(p);expect((await p.request.get(`/api/salon/appointments/${id}/precheck`)).status()).toBe(404);await other.close();
 const revoke=await op(page,{type:"RESOURCE_SAVE",id:f.resourceId,expected_version:1,definition:{name:"Renk koltuğu",type:"CHAIR",capacity:1,active:false}});expect(revoke.body.code).toBe("RESOURCE_HAS_BOOKINGS");
});
