import {test,expect,type Page} from "@playwright/test";
import {randomUUID} from "node:crypto";
import {seedAccount,login,expectReady} from "./local-auth";
import {stockSnapshot} from "@/lib/stock/model";
test.use({actionTimeout:20000});
async function context(page:Page){const r=await page.request.get("/api/session");expect(r.status()).toBe(200);return (await r.json()).context;}
async function op(page:Page,q:object){const c=await context(page),r=await page.request.post("/api/stock",{headers:{origin:"http://127.0.0.1:4173","x-workspace-reference":`${c.membership_id}:${c.location_id}`},data:{mutation_id:randomUUID(),...q}});return {status:r.status(),body:await r.json()};}
async function read(page:Page,item?:string){const r=await page.request.get("/api/stock"+(item?`?item_id=${item}`:""));expect(r.status()).toBe(200);return stockSnapshot.parse((await r.json()).data);}
const definition={source:"SALON_CUSTOM_OPERATIONAL_PRODUCT",catalog_product_id:null,product_type:"SHAMPOO",display_name:"Salon bakım ürünü",sku:"SYN-STOCK",barcode:"SYN-BARCODE",inventory_unit:"GRAM",active:true,track_quantity:true,lot_required:false,low_threshold:20};
async function setup(page:Page){const account=await seedAccount();await login(page,account);await expectReady(page);const write=async(q:object)=>{const r=await op(page,q);expect(r.status,JSON.stringify(r.body)).toBe(200);return r.body.data;};await write({type:"ENABLE",reason:"Physical opening cutover"});const id=randomUUID();await write({type:"ITEM_SAVE",id,expected_version:0,definition,reason:"Operational product mapping"});return {account,id,write};}
const movement=(type:string,id:string,quantity:number,more:object={})=>({type,stock_item_id:id,lot_id:null,quantity,unit:"GRAM",occurred_at:"2026-10-09T12:00:00Z",reference:"Synthetic factual receipt",reason:"Measured stock fact",...more});

test("real inventory UI opening, receipt, physical count and desktop/mobile captures",async({page},info)=>{
 test.setTimeout(180000);const f=await setup(page);await page.goto("/workspace/stock");await expect(page.getByRole("heading",{name:"Stok ve ürünler",exact:true})).toBeVisible();await expect(page.getByText("Salon bakım ürünü",{exact:true})).toBeVisible();
 expect((await read(page,f.id)).items[0]!.on_hand).toBeNull();
 await page.getByRole("button",{name:"Açılış miktarı",exact:true}).click();await page.getByLabel("Miktar",{exact:true}).fill("100");await page.getByLabel("Etkin tarih").fill("2026-10-09T12:00");await page.getByLabel("Gerekçe").fill("Measured opening count");await page.getByRole("button",{name:"Kaydet",exact:true}).click();await expect(page.getByText("100 g",{exact:true})).toBeVisible();
 await page.getByRole("button",{name:"Stok girişi",exact:true}).click();await page.getByLabel("Miktar",{exact:true}).fill("25");await page.getByLabel("Etkin tarih").fill("2026-10-09T13:00");await page.getByLabel("Referans").fill("Synthetic delivery");await page.getByLabel("Gerekçe").fill("Measured receipt");await page.getByRole("button",{name:"Kaydet",exact:true}).click();await expect(page.getByText("125 g",{exact:true})).toBeVisible();
 await page.getByRole("button",{name:"Fiziksel sayım",exact:true}).click();await page.getByLabel("Ölçülen miktar").fill("120");await page.getByLabel("Gerekçe").fill("Physical count of opened containers");await page.getByRole("button",{name:"Kaydet",exact:true}).click();await expect(page.getByRole("button",{name:"Sayımı onayla"})).toBeVisible();await page.getByRole("button",{name:"Sayımı onayla"}).click();await expect(page.getByText("120 g",{exact:true})).toBeVisible();
 const final=await read(page,f.id);expect(final.items[0]!.on_hand).toBe(120);expect(final.movements.map(m=>m.quantity_delta).reduce((a,b)=>a+b,0)).toBe(120);expect(final.counts[0]!.status).toBe("CONFIRMED");
 for(const [width,name] of [[1440,"desktop"],[320,"mobile-320"]] as const){await page.setViewportSize({width,height:900});await page.screenshot({path:info.outputPath(`stock-overview-${name}.png`),fullPage:true});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);}
 await page.getByRole("button",{name:"Salon bakım ürünü",exact:true}).click();await expect(page.getByRole("heading",{name:"Ürün özeti"})).toBeVisible();for(const [width,name] of [[1440,"desktop"],[320,"mobile-320"]] as const){await page.setViewportSize({width,height:900});await page.screenshot({path:info.outputPath(`stock-detail-${name}.png`),fullPage:true});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);}
});
test("stock receipt permanent replay and negative guard across real server",async({page})=>{const f=await setup(page);await f.write(movement("OPENING",f.id,100));const q=movement("RECEIPT",f.id,25,{mutation_id:randomUUID()}),one=await op(page,q),two=await op(page,q);expect(one.status).toBe(200);expect(two.body.data).toEqual(one.body.data);expect((await op(page,{...q,quantity:26})).status).toBe(409);expect((await read(page,f.id)).items[0]!.on_hand).toBe(125);const blocked=await op(page,movement("ADJUSTMENT_OUT",f.id,126));expect(blocked.status).toBe(409);expect(blocked.body.code).toBe("STOCK_INSUFFICIENT");});
test("UNKNOWN and measured zero remain distinct through real API",async({page})=>{const f=await setup(page);expect((await read(page,f.id)).items[0]!.stock_status).toBe("UNKNOWN");await f.write(movement("OPENING",f.id,0));const item=(await read(page,f.id)).items[0]!;expect(item.stock_status).toBe("OUT");expect(item.on_hand).toBe(0);});
test("count confirmation rejects an intervening receipt",async({page})=>{const f=await setup(page);await f.write(movement("OPENING",f.id,100));const id=randomUUID();await f.write({type:"COUNT_CREATE",id,reason:"Measured count",lines:[{stock_item_id:f.id,lot_id:null,counted_quantity:90}]});await f.write(movement("RECEIPT",f.id,10));const r=await op(page,{type:"COUNT_CONFIRM",id,reason:"Stale confirmation"});expect(r.status).toBe(409);expect(r.body.code).toBe("STOCK_COUNT_STALE");expect((await read(page,f.id)).items[0]!.on_hand).toBe(110);});
test("real lot balance, expiry signal and mobile form",async({page},info)=>{const f=await setup(page),lot=randomUUID();await f.write({type:"LOT_SAVE",id:lot,expected_version:0,stock_item_id:f.id,lot_number:"SYN-LOT",batch_number:"SYN-BATCH",expiry_date:new Date(Date.now()+7*86400000).toISOString().slice(0,10),opened_at:null,received_at:"2026-10-09T12:00:00Z",reason:"Actual label"});await f.write(movement("OPENING",f.id,100,{lot_id:lot}));await f.write(movement("RECEIPT",f.id,20,{lot_id:lot}));const data=await read(page,f.id);expect(data.lots[0]!.on_hand).toBe(120);expect(data.actions.some(a=>a.kind==="EXPIRING_SOON")).toBe(true);await page.goto(`/workspace/stock?item_id=${f.id}`);await expect(page.getByText("SYN-LOT",{exact:true}).first()).toBeVisible();await page.setViewportSize({width:320,height:900});await page.getByRole("button",{name:"Stok girişi",exact:true}).click();await page.screenshot({path:info.outputPath("stock-receipt-mobile-320.png"),fullPage:true});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);});
test("view-only member cannot receive or forge automated usage",async({page,browser})=>{const f=await setup(page);await f.write(movement("OPENING",f.id,100));const member=await f.account.addMember("colorist"),browserContext=await browser.newContext(),viewer=await browserContext.newPage();await login(viewer,member);await expectReady(viewer);await viewer.goto("/workspace/stock");await expect(viewer.getByRole("heading",{name:"Stok ve ürünler",exact:true})).toBeVisible();await expect(viewer.getByRole("button",{name:"Stok girişi",exact:true})).toHaveCount(0);expect((await op(viewer,movement("RECEIPT",f.id,1))).status).toBe(403);expect((await op(page,{...movement("RECEIPT",f.id,1),source_event_id:randomUUID()})).status).toBe(400);expect((await op(page,{...movement("USAGE",f.id,1)})).status).toBe(400);await browserContext.close();});
test("cross-tenant item detail is denied",async({page,browser})=>{const f=await setup(page),other=await seedAccount(),browserContext=await browser.newContext(),viewer=await browserContext.newPage();await login(viewer,other);await expectReady(viewer);expect((await viewer.request.get(`/api/stock?item_id=${f.id}`)).status()).toBe(404);await browserContext.close();});
test("revocation conceals loaded stock",async({page})=>{const f=await setup(page);await f.write(movement("OPENING",f.id,100));await page.goto("/workspace/stock");await expect(page.getByText("Salon bakım ürünü",{exact:true})).toBeVisible();await f.account.revoke();await page.evaluate(()=>window.dispatchEvent(new Event("focus")));await expect(page).toHaveURL(/\/workspaces/,{timeout:25000});await expect(page.getByText("Salon bakım ürünü",{exact:true})).toHaveCount(0);});
