import { z } from "zod";
import { clientDetail } from "@/lib/clients/contracts";
const id=z.uuid().transform(v=>v.toLowerCase()),time=z.iso.datetime({offset:true}),version=z.int().nonnegative();
export const relationshipStatus=z.enum(["NEW","ACTIVE","RETURNING","OVERDUE","INACTIVE","UPCOMING","FOLLOW_UP_REQUIRED"]);
export const noteVisibility=z.enum(["TECHNICAL","RECEPTION","PRIVATE_MANAGEMENT"]);
export const actionKind=z.enum(["REBOOK","WIN_BACK","CARE_CHECK","COLOR_FOLLOWUP","RECOVERY_REASSESSMENT","DUPLICATE_REVIEW"]);
export const actionStatus=z.enum(["OPEN","SNOOZED","DONE","DISMISSED"]);
export const preferenceDefinition=z.strictObject({preferred_staff_id:id.nullable(),preferred_service_ids:id.array().max(20),request_notes:z.string().max(2000).nullable(),preferred_channel:z.enum(["UNKNOWN","PHONE","WHATSAPP","EMAIL"]),allow_manual_contact:z.boolean(),do_not_contact:z.boolean()}).refine(p=>new Set(p.preferred_service_ids).size===p.preferred_service_ids.length);
export const clientPreference=preferenceDefinition.safeExtend({client_id:id,organization_id:id,version:z.int().positive(),updated_at:time,updated_by:id});
export const returnWindow=z.strictObject({service_id:id,organization_id:id,min_days:z.int().min(1).max(730).nullable(),max_days:z.int().min(1).max(730).nullable(),version:z.int().positive(),updated_at:time,updated_by:id});
export const relationshipPolicy=z.strictObject({organization_id:id,location_id:id,inactive_after_overdue_days:z.int().min(1).max(3650).nullable(),version:z.int().positive(),updated_at:time,updated_by:id});
export const options=z.strictObject({services:z.strictObject({id,name:z.string(),active:z.boolean(),return_window:returnWindow.nullable()}).array().max(200),staff:z.strictObject({id,name:z.string(),active:z.boolean(),bookable:z.boolean()}).array().max(200),policy:relationshipPolicy.nullable()});
export const clientSearchFilter=z.strictObject({query:z.string().trim().max(80).optional(),record_status:z.enum(["ACTIVE","ARCHIVED"]).optional(),relationship_status:relationshipStatus.optional(),last_visit_min_days:z.int().min(1).max(3650).optional(),service_last_visit_min_days:z.int().min(1).max(3650).optional(),upcoming:z.enum(["ANY","HAS","NONE"]).optional(),preferred_staff_id:id.optional(),staff_history_id:id.optional(),service_id:id.optional(),last_no_show:z.boolean().optional(),technical_followup:z.boolean().optional(),technical_followup_kind:z.enum(["CARE_CHECK_DUE","COLOR_FOLLOWUP_DUE","RECOVERY_REASSESSMENT_DUE"]).optional()});
export const technicalFollowup=z.strictObject({kind:z.enum(["CARE_CHECK_DUE","COLOR_FOLLOWUP_DUE","RECOVERY_REASSESSMENT_DUE"]),source_domain:z.enum(["live_session","client"]),source_id:id,at:time,basis:z.string()});
export const crmSummary=z.strictObject({client_id:id,requested_client_id:id,organization_id:id,location_id:id,source_client_ids:id.array().min(1).max(20),computed_at:time,relationship_status:relationshipStatus,last_visit_at:time.nullable(),first_visit_at:time.nullable(),total_completed_visits:z.int().nonnegative(),cancellation_count:z.int().nonnegative(),no_show_count:z.int().nonnegative(),days_since_last_visit:z.int().nonnegative().nullable(),average_visit_interval_days:z.number().nonnegative().nullable(),interval_basis:z.enum(["INSUFFICIENT_DATA","LAST_12_COMPLETED_SAME_SERVICE"]),
last_completed_service:z.strictObject({id,name:z.string(),appointment_id:id}).nullable(),last_staff_member:z.strictObject({id,name:z.string()}).nullable(),
upcoming_appointment:z.strictObject({id,client_id:id,start_at:time,service_id:id,service_name:z.string(),staff_id:id,staff_name:z.string(),status:z.enum(["DRAFT","CONFIRMED","ARRIVED","IN_SERVICE"]),precheck:z.literal("NOT_ASSESSED")}).nullable(),
usual_services:z.strictObject({service_id:id,name:z.string(),count:z.int().positive()}).array().max(5),preferred_staff:z.strictObject({source:z.enum(["MANUAL_PREFERENCE","HISTORICAL_PATTERN","UNKNOWN"]),membership_id:id.nullable(),name:z.string().nullable(),count:z.int().nonnegative().nullable(),sample_size:z.int().nonnegative().nullable()}),
appointment_facts:z.strictObject({sample_size:z.int().min(0).max(12),completed:z.int().nonnegative(),cancelled:z.int().nonnegative(),no_show:z.int().nonnegative(),last_status:z.enum(["COMPLETED","CANCELLED","NO_SHOW"]).nullable()}),technical_followups:technicalFollowup.array().max(3),
return_signal:z.strictObject({status:z.enum(["INSUFFICIENT_DATA","NOT_YET_DUE","RETURN_WINDOW_OPEN","OVERDUE","ALREADY_BOOKED"]),service_id:id.nullable(),appointment_id:id.nullable(),days_since:z.int().nonnegative().nullable(),min_days:z.int().positive().nullable(),max_days:z.int().positive().nullable(),policy_version:z.int().positive().nullable()}),finance:z.literal("NOT_AVAILABLE"),recovery_state:z.literal("NOT_ASSESSED")});
export const crmOverview=z.strictObject({summary:crmSummary,preferences:clientPreference.nullable(),technical_sources:z.strictObject({domain:z.literal("hair_passport"),id,client_id:id,version:z.int().positive(),updated_at:time}).array().max(20)});
export const clientTimelineEvent=z.strictObject({event_key:z.string().max(160),event_type:z.string().max(80),timestamp:time,source_domain:z.enum(["client","salon_appointment","hair_passport","hair_history","color_plan","controlled_recipe","live_session","client_note","crm_action","client_merge"]),source_id:id,source_client_id:id,actor_id:id.nullable(),summary:z.string().max(4000),visibility:z.enum(["OPERATIONAL","TECHNICAL","RECEPTION","PRIVATE_MANAGEMENT"])});
export const clientNote=z.strictObject({id,organization_id:id,location_id:id,client_id:id,visibility:noteVisibility,body:z.string().min(1).max(4000),archived:z.boolean(),version:z.int().positive(),created_at:time,updated_at:time,created_by:id,updated_by:id});
export const crmAction=z.strictObject({id,organization_id:id,location_id:id,client_id:id,kind:actionKind,source_domain:z.enum(["salon_appointment","live_session","client"]),source_id:id,basis:z.record(z.string(),z.unknown()),status:actionStatus,effective_status:actionStatus,due_at:time,snoozed_until:time.nullable(),version:z.int().positive(),created_at:time,updated_at:time,created_by:id,updated_by:id});
export const crmAppointment=z.strictObject({id,client_id:id,start_at:time,end_at:time,service_id:id,service_name:z.string(),staff_membership_id:id,staff_display_name:z.string(),status:z.enum(["DRAFT","CONFIRMED","ARRIVED","IN_SERVICE","COMPLETED","CANCELLED","NO_SHOW"]),version:z.int().positive(),completed_at:time.nullable()});
export const page=<T extends z.ZodType>(item:T)=>z.strictObject({items:item.array().max(50),has_more:z.boolean(),offset:z.int().min(0).max(10000)});
export const crmDirectory=z.strictObject({items:z.strictObject({id,full_name:z.string(),phone_masked:z.string(),status:z.enum(["ACTIVE","ARCHIVED"]),summary:crmSummary}).array().max(50),has_more:z.boolean(),offset:z.int().min(0).max(10000),next_offset:z.int().positive(),scan_limit:z.literal(200)});
export const duplicateCandidate=z.strictObject({id,full_name:z.string(),phone_masked:z.string(),status:z.enum(["ACTIVE","ARCHIVED"]),version:z.int().positive(),signals:z.enum(["PHONE","EMAIL","NAME"]).array()});
export const duplicates=z.strictObject({items:duplicateCandidate.array().max(20),warning_only:z.literal(true)});
export const mergeFields=["full_name","phone","email","birth_date","preferred_staff_id","preferred_service_ids","request_notes","preferred_channel","allow_manual_contact","do_not_contact"] as const;
export const mergeDecisions=z.strictObject(Object.fromEntries(mergeFields.map(f=>[f,z.enum(["SOURCE","TARGET"])])) as Record<typeof mergeFields[number],z.ZodEnum<{SOURCE:"SOURCE";TARGET:"TARGET"}>>);
export const mergeReview=z.strictObject({review_token:id,source:clientDetail,target:clientDetail,source_preferences:clientPreference.nullable(),target_preferences:clientPreference.nullable(),source_client_ids:id.array().max(20),target_client_ids:id.array().max(20),required_decisions:z.enum(mergeFields).array().length(10)});
const pagination={offset:z.int().min(0).max(10000).optional(),limit:z.int().min(1).max(50).optional()},mutation={mutation_id:id},target={id,expected_version:version};
export const crmReadRequest=z.discriminatedUnion("operation",[
 z.strictObject({operation:z.literal("list"),filter:clientSearchFilter.optional(),...pagination}),z.strictObject({operation:z.literal("summary"),client_id:id}),z.strictObject({operation:z.literal("duplicates"),client_id:id}),z.strictObject({operation:z.literal("options")}),
 ...(["timeline","notes","appointments"] as const).map(operation=>z.strictObject({operation:z.literal(operation),client_id:id,...pagination})),z.strictObject({operation:z.literal("actions"),client_id:id.optional(),status:actionStatus.optional(),...pagination}),z.strictObject({operation:z.literal("merge_review"),source_client_id:id,target_client_id:id})]);
export const crmCommand=z.discriminatedUnion("type",[
z.strictObject({type:z.literal("PREFERENCE_SAVE"),...mutation,client_id:id,expected_version:version,definition:preferenceDefinition}),z.strictObject({type:z.literal("NOTE_SAVE"),...mutation,...target,client_id:id,visibility:noteVisibility,body:z.string().trim().min(1).max(4000),archived:z.boolean()}),
z.strictObject({type:z.literal("RETURN_WINDOW_SAVE"),...mutation,service_id:id,expected_version:version,min_days:z.int().min(1).max(730).nullable(),max_days:z.int().min(1).max(730).nullable()}).refine(c=>c.min_days===null?c.max_days===null:c.max_days!==null&&c.max_days>=c.min_days),
z.strictObject({type:z.literal("POLICY_SAVE"),...mutation,expected_version:version,inactive_after_overdue_days:z.int().min(1).max(3650).nullable()}),z.strictObject({type:z.literal("ACTION_CREATE"),...mutation,id,client_id:id,kind:actionKind,source_domain:z.enum(["salon_appointment","live_session","client"]),source_id:id}),
z.strictObject({type:z.literal("ACTION_TRANSITION"),...mutation,...target,status:z.enum(["SNOOZED","DONE","DISMISSED"]),snoozed_until:time.nullable()}).refine(c=>(c.status==="SNOOZED")===(c.snoozed_until!==null)),z.strictObject({type:z.literal("MERGE"),...mutation,review_token:id,decisions:mergeDecisions}),z.strictObject({type:z.literal("MERGE_REVERSE"),...mutation,merge_id:id,reason:z.string().trim().min(1).max(500)})]);
export const searchInterpretation=z.strictObject({status:z.enum(["MAPPED","NEEDS_CLARIFICATION"]),filter:clientSearchFilter,explanations:z.string().array().max(10),ambiguities:z.string().array().max(10)});
export const crmError=z.strictObject({code:z.enum(["UNAUTHENTICATED","SESSION_EXPIRED","FORBIDDEN","MEMBERSHIP_REQUIRED","MEMBERSHIP_REVOKED","TENANT_CONTEXT_INVALID","CRM_NOT_FOUND","CRM_CONFLICT","CRM_SIGNAL_CHANGED","CRM_INVALID_TRANSITION","CRM_REVIEW_EXPIRED","CRM_DECISIONS_REQUIRED","CONTACT_NOT_ALLOWED","VALIDATION_FAILED","NETWORK_ERROR"]),message:z.string(),correlationId:id});
export function permissionFor(command:z.infer<typeof crmCommand>){return command.type==="NOTE_SAVE"?({TECHNICAL:"crm.notes.technical",RECEPTION:"crm.notes.reception",PRIVATE_MANAGEMENT:"crm.notes.private"}[command.visibility]):command.type==="PREFERENCE_SAVE"?"crm.preferences.manage":command.type==="RETURN_WINDOW_SAVE"?"salon.catalog.manage":command.type==="POLICY_SAVE"?"crm.policy.manage":command.type.startsWith("MERGE")?"crm.merge":"crm.actions.manage";}
export type Summary=z.infer<typeof crmSummary>;
export type CrmCommand=z.infer<typeof crmCommand>;
export type SearchFilter=z.infer<typeof clientSearchFilter>;
export type Options=z.infer<typeof options>;
