import "server-only";
import { z } from "zod";
import { createClient } from "@/lib/supabase/server";
import { verifiedClientContext } from "@/lib/clients/service";
import { workspaceReference } from "@/lib/tenant/context";
import { AccessError } from "@/lib/tenant/bootstrap";
import { clientDetail } from "@/lib/clients/contracts";
import * as m from "./model";
import { interpretSearch } from "./finder";
type Context=Awaited<ReturnType<typeof verifiedClientContext>>;
export const errorStatus=(code:string)=>["UNAUTHENTICATED","SESSION_EXPIRED"].includes(code)?401:["FORBIDDEN","MEMBERSHIP_REQUIRED","MEMBERSHIP_REVOKED","TENANT_CONTEXT_INVALID","CONTACT_NOT_ALLOWED"].includes(code)?403:code==="CRM_NOT_FOUND"?404:code==="NETWORK_ERROR"?503:code==="VALIDATION_FAILED"?400:409;
async function access(permission:string,reference?:string|null){const ctx=await verifiedClientContext(permission);if(reference!==undefined&&reference!==workspaceReference(ctx))throw new AccessError("TENANT_CONTEXT_INVALID",403);return ctx;}
async function finish(ctx:Context,permission:string){await access(permission,workspaceReference(ctx));}
function unwrap(result:{data:unknown;error:unknown}){if(result.error)throw new AccessError("NETWORK_ERROR",503);const r=z.strictObject({code:z.string().optional(),data:z.unknown().optional()}).safeParse(result.data);if(!r.success)throw new AccessError("NETWORK_ERROR",503);if(r.data.code){const code=m.crmError.shape.code.options.some(c=>c===r.data.code)?r.data.code:"NETWORK_ERROR";throw new AccessError(code,errorStatus(code));}return r.data.data;}
export async function readCrm(raw:unknown,correlationId:string,reference?:string|null){
 const q=m.crmReadRequest.safeParse(raw);if(!q.success)throw new AccessError("VALIDATION_FAILED",400);
 const request=q.data,permission=request.operation==="merge_review"?"crm.merge":"crm.read",context=await access(permission,reference),client=await createClient();
 const schemas={summary:m.crmOverview,list:m.crmDirectory,timeline:m.page(m.clientTimelineEvent),notes:m.page(m.clientNote),appointments:m.page(m.crmAppointment),actions:m.page(m.crmAction),duplicates:m.duplicates,merge_review:m.mergeReview,options:m.options};
 const parsed=schemas[request.operation].safeParse(unwrap(await client.rpc("crm_read",{p_membership_id:context.membership_id,p_location_id:context.location_id,p_request:request})));
 if(!parsed.success)throw new AccessError("NETWORK_ERROR",503);const data=parsed.data;
 // The RPC is the primary tenant boundary; validate response scope before releasing it too.
 if("summary" in data){if(data.summary.organization_id!==context.organization_id||data.summary.location_id!==context.location_id||data.summary.requested_client_id!==("client_id" in request?request.client_id:null)||data.preferences&&data.preferences.organization_id!==context.organization_id||data.technical_sources.some(s=>!data.summary.source_client_ids.includes(s.client_id))||data.summary.last_technical_memory&&!data.summary.source_client_ids.includes(data.summary.last_technical_memory.client_id))throw new AccessError("NETWORK_ERROR",503);}
 if("items" in data)for(const row of data.items){if("organization_id" in row&&row.organization_id!==context.organization_id||"location_id" in row&&row.location_id!==context.location_id||"summary" in row&&typeof row.summary==="object"&&(row.summary.organization_id!==context.organization_id||row.summary.location_id!==context.location_id||!("id" in row)||row.summary.client_id!==row.id))throw new AccessError("NETWORK_ERROR",503);}
 if("review_token" in data&&(request.operation!=="merge_review"||data.source.id!==request.source_client_id||data.target.id!==request.target_client_id||data.source.organization_id!==context.organization_id||data.target.organization_id!==context.organization_id))throw new AccessError("NETWORK_ERROR",503);
 if("policy" in data&&(data.policy&&(data.policy.organization_id!==context.organization_id||data.policy.location_id!==context.location_id)||data.services.some(s=>s.return_window&&s.return_window.organization_id!==context.organization_id)))throw new AccessError("NETWORK_ERROR",503);
 await finish(context,permission);return {data,context,correlationId};
}
export async function mutateCrm(raw:unknown,correlationId:string,reference:string|null){const q=m.crmCommand.safeParse(raw);if(!q.success)throw new AccessError("VALIDATION_FAILED",400);const command=q.data,permission=m.permissionFor(command),context=await access(permission,reference),client=await createClient();const parsed=z.strictObject({id:z.uuid(),version:z.int().positive()}).safeParse(unwrap(await client.rpc("crm_operation",{p_membership_id:context.membership_id,p_location_id:context.location_id,p_command:command,p_correlation_id:correlationId})));if(!parsed.success)throw new AccessError("NETWORK_ERROR",503);const data=parsed.data;if("id" in command&&data.id!==command.id||command.type==="PREFERENCE_SAVE"&&data.id!==command.client_id||command.type==="RETURN_WINDOW_SAVE"&&data.id!==command.service_id||command.type==="POLICY_SAVE"&&data.id!==context.location_id||command.type==="MERGE_REVERSE"&&data.id!==command.merge_id)throw new AccessError("NETWORK_ERROR",503);await finish(context,permission);return {data,context,correlationId};}
export async function interpretCrm(raw:unknown,correlationId:string,reference:string|null){const q=z.strictObject({text:z.string().trim().min(1).max(240)}).safeParse(raw);if(!q.success)throw new AccessError("VALIDATION_FAILED",400);const context=await access("crm.read",reference),result=await readCrm({operation:"options"},correlationId,reference),data=interpretSearch(q.data.text,m.options.parse(result.data));await finish(context,"crm.read");return {data,context,correlationId};}
/** Produces a link only. Sending is a separate, explicit action in the user's messaging app. */
export async function manualContact(raw:unknown,correlationId:string,reference:string|null){const q=z.strictObject({client_id:z.uuid().transform(v=>v.toLowerCase())}).safeParse(raw);if(!q.success)throw new AccessError("VALIDATION_FAILED",400);const context=await access("crm.contact.manual",reference),overview=m.crmOverview.parse((await readCrm({operation:"summary",client_id:q.data.client_id},correlationId,reference)).data),p=overview.preferences;if(!p?.allow_manual_contact||p.do_not_contact||p.preferred_channel!=="WHATSAPP")throw new AccessError("CONTACT_NOT_ALLOWED",403);const client=await createClient(),detail=clientDetail.safeParse(unwrap(await client.rpc("client_operation",{p_membership_id:context.membership_id,p_location_id:context.location_id,p_operation:"detail",p_payload:{client_id:overview.summary.client_id},p_correlation_id:correlationId})));if(!detail.success||detail.data.organization_id!==context.organization_id||detail.data.id!==overview.summary.client_id)throw new AccessError("NETWORK_ERROR",503);if(detail.data.status!=="ACTIVE"||!/^\+[1-9]\d{6,14}$/.test(detail.data.phone_normalized))throw new AccessError("CONTACT_NOT_ALLOWED",403);const current=m.crmOverview.parse((await readCrm({operation:"summary",client_id:q.data.client_id},correlationId,reference)).data);if(current.preferences?.version!==p.version||current.summary.client_id!==overview.summary.client_id)throw new AccessError("CRM_CONFLICT",409);await finish(context,"crm.contact.manual");return {data:{url:`https://wa.me/${detail.data.phone_normalized.slice(1)}`},context,correlationId};}
