export const appointmentLabels: Record<string,string> = {DRAFT:"Taslak",CONFIRMED:"Onaylandı",ARRIVED:"Salonda",IN_SERVICE:"İşlemde",COMPLETED:"Tamamlandı",CANCELLED:"İptal edildi",NO_SHOW:"Gelmedi"};
export const capabilityLabels: Record<string,string> = {GENERAL_COLOR:"Genel renklendirme",GREY_COVERAGE:"Beyaz kapama",BLONDING:"Açma",ADVANCED_BLONDING:"İleri açma",CORRECTION:"Renk düzeltme",VIVID:"Canlı renkler",RECOVERY:"Saç iyileştirme"};
export const levelLabels: Record<string,string> = {NOT_AUTHORIZED:"Yetkinlik onayı yok",ASSISTED:"Gözetim altında",INDEPENDENT:"Bağımsız",SENIOR_REVIEWER:"Kıdemli değerlendirme"};
export const resourceLabels: Record<string,string> = {CHAIR:"Koltuk",WASH_UNIT:"Yıkama ünitesi",COLOR_STATION:"Renk istasyonu",EQUIPMENT:"Ekipman",CUSTOM:"Özel kaynak"};
export const precheckLabels: Record<string,string> = {READY:"Ön kontrol uygun",INFORMATION_REQUIRED:"Bilgi gerekli",TEST_REQUIRED:"Fiziksel test gerekli",REVIEW_REQUIRED:"Uzman incelemesi gerekli",RECOVERY_CONSTRAINT:"Saç iyileştirme değerlendirmesi gerekli",TIME_WARNING:"Ek süre gerekebilir",TECHNICAL_ESCALATION:"Yetkin uzman gerekli"};
export const salonMessages: Record<string,string> = {LOCATION_CLOSED:"Salon bu tarihte kapalı.",STAFF_UNAVAILABLE:"Personel bu saatlerde çalışmıyor veya izin/mola kaydı var.",STAFF_DOUBLE_BOOKED:"Personelin tampon süreleri dahil başka randevusu var.",STAFF_NOT_ELIGIBLE:"Personel bu hizmete atanabilir olarak tanımlanmamış.",RESOURCE_UNAVAILABLE:"Gerekli kaynak kapasitesi bu saatlerde dolu.",INVALID_DURATION:"Süre değişikliği için yetki ve gerekçe gerekir.",OUTSIDE_WORKING_HOURS:"Randevu ve tampon süreleri salonun çalışma saatlerini aşıyor.",TECHNICAL_ESCALATION:"Personelin teknik yetkinliği yetersiz. Yetkin bir uzman seçin.",SALON_CONFLICT:"Kayıt değişti veya aynı istek farklı içerikle kullanıldı. Güncel kaydı açın.",SALON_NOT_FOUND:"Kayıt bulunamadı veya bu çalışma alanında erişilemiyor.",INVALID_TRANSITION:"Bu durum geçişi yapılamaz.",APPOINTMENT_IMMUTABLE:"Sonlandırılmış randevu değiştirilemez.",RESOURCE_HAS_BOOKINGS:"Kaynağın bekleyen randevuları var; kapatılamaz veya kapasitesi azaltılamaz.",INVALID_LOCAL_TIME:"Bu yerel tarih/saat saat diliminde geçerli değil.",AMBIGUOUS_LOCAL_TIME:"Saat dilimi geçişinde bu saat iki kez yaşanıyor. Açık UTC farkı seçin.",VALIDATION_FAILED:"Alanları ve süreleri kontrol edin.",NETWORK_ERROR:"Veriler doğrulanamadı. Bağlantıyı kontrol edip yeniden deneyin.",FORBIDDEN:"Bu işlem için yetkiniz yok.",TENANT_CONTEXT_INVALID:"Çalışma alanı değişti. Sayfayı yeniden açın.",SALON_LIMIT_REACHED:"Bu çalışma alanındaki kayıt sınırına ulaşıldı."};
export const weekdays = ["Pazartesi","Salı","Çarşamba","Perşembe","Cuma","Cumartesi","Pazar"];
export function precheckReason(reason:string) {
 const [code,detail,level]=reason.split(":");
 const labels:Record<string,string>={SERVICE_VERSION_CHANGED:"Hizmet tanımı randevu kaydından sonra değişti.",STAFF_ELIGIBILITY_CHANGED:"Personelin hizmete atanabilirliği veya üyeliği değişti.",RISK_INFORMATION_REQUIRED:"Risk değerlendirmesi için eksik bilgiler tamamlanmalı.",RISK_PHYSICAL_TEST_REQUIRED:"Gerekli fiziksel testler tamamlanmalı.",RISK_RECOVERY_REASSESSMENT:"Saç bütünlüğü için iyileştirme değerlendirmesi gerekli.",HISTORY_SUMMARY_TRUNCATED:"Teknik geçmişin bir kısmı gösteriliyor; geçmişi ayrıca inceleyin.",HAIR_PASSPORT_MISSING:"Müşterinin saç pasaportu henüz oluşturulmamış.",OWN_SALON_DURATION_EXCEEDS_ALLOCATION:"Salonun geçmiş işlem süreleri planlanan süreyi aşıyor.",RISK_GATE:"Risk güvenlik kapısı uzman incelemesi gerektiriyor.",RISK_BAND:"Yüksek teknik risk için yetkin uzman değerlendirmesi gerekli."};
 return code==="COMPETENCY_REQUIRED"?`${capabilityLabels[detail!]??detail}: ${levelLabels[level!]??level} yetkinliği gerekli.`:code==="ASSISTED_COMPETENCY"?`${capabilityLabels[detail!]??detail} için gözetim gerekir.`:labels[code!]??"Teknik geçmişi uzmanla gözden geçirin.";
}
export function minuteText(value:number|null) {return value===null?"":`${String(Math.floor(value/60)).padStart(2,"0")}:${String(value%60).padStart(2,"0")}`;}
export function minuteValue(value:string) {const [hour,minute]=value.split(":").map(Number);return hour!*60+minute!;}

export const historyLabels:Record<string,string> = {BLEACH_LIGHTENING:"Açma",COLOR:"Renklendirme",TONER_GLOSS:"Tonlama"};
