import { salonSnapshot, appointment, serviceDefinition, type SalonCommand } from "@/lib/salon/model";
export const salonId=(n:number)=>`a4000000-0000-4000-8000-${String(n).padStart(12,"0")}`;
export function salonFixture() {
 const organization_id=salonId(1),location_id=salonId(11),actor=salonId(21),membership_id=salonId(111),stamp="2026-10-06T09:00:00Z",owned={organization_id,location_id,created_at:stamp,updated_at:stamp,created_by:actor,updated_by:actor,version:1};
 const definition=serviceDefinition.parse({name:"Synthetic color",category:"COLOR",description:null,organization_wide:false,base_duration_minutes:60,buffer_before_minutes:5,buffer_after_minutes:10,base_price:1000,tax_rate:20,tax_inclusive:false,requires_colorlab:true,requires_hair_passport:true,requires_precheck:true,active:true,eligible_membership_ids:[membership_id],capabilities:[{code:"GENERAL_COLOR",level:"INDEPENDENT"}],resources:[{type:"CHAIR",units:1}]});
 const a=appointment.parse({...owned,id:salonId(301),client_id:salonId(31),client_name:"Synthetic client",service_id:salonId(101),service_name:definition.name,service_version:1,staff_membership_id:membership_id,staff_user_id:actor,staff_display_name:"Synthetic professional",start_at:"2026-10-12T07:00:00Z",end_at:"2026-10-12T08:00:00Z",occupied_start_at:"2026-10-12T06:55:00Z",occupied_end_at:"2026-10-12T08:10:00Z",timezone:"Europe/Istanbul",status:"CONFIRMED",default_duration_minutes:60,scheduled_duration_minutes:60,adjustment_reason:null,base_price:1000,tax_rate:20,tax_inclusive:false,quoted_total:1200,currency:"TRY",buffer_before_minutes:5,buffer_after_minutes:10,colorlab_required:true,hair_passport_required:true,precheck_required:true,notes:null,cancelled_at:null,arrived_at:null,started_at:null,completed_at:null,actual_duration_seconds:null,resources:[{resource_id:salonId(102),name:"Synthetic chair",type:"CHAIR",units:1}],live_session_ids:[]});
 const {organization_wide:_,...fields}=definition;void _;
 const snapshot=salonSnapshot.parse({location:{id:location_id,organization_id,name:"Synthetic branch",timezone:"Europe/Istanbul",currency:"TRY"},categories:[{code:"COLOR",label:"Renklendirme",version:1}],services:[{...fields,...owned,id:salonId(101),currency:"TRY"}],staff:[{...owned,membership_id,default_location_id:location_id,display_name:a.staff_display_name,active:true,bookable:true,working_capacity:null,notes:null,competencies:[{code:"GENERAL_COLOR",level:"INDEPENDENT"}],shifts:[{day:1,type:"SHIFT",starts:540,ends:1080}],role:"owner",membership_status:"active",user_id:actor}],resources:[{...owned,id:salonId(102),name:"Synthetic chair",type:"CHAIR",capacity:1,active:true}],members:[{id:membership_id,user_id:actor,role:"owner",display_name:null}],hours:{version:1,days:Array.from({length:7},(_,i)=>({day:i+1,closed:false,opens:540,closes:1080}))},exceptions:[],availability:[],appointments:[a],has_more:false,evaluated_at:stamp});
 const context={membership_id,organization_id,location_id,organization_name:"Synthetic salon",location_name:"Synthetic branch",role:"owner" as const,membership_status:"active" as const,permissions:["salon.read","salon.catalog.manage","salon.staff.manage","salon.hours.manage","salon.resources.manage","salon.appointments.manage","salon.appointments.adjust_duration","salon.precheck.read","hair_passport.read","clients.read","live_session.view"]};
 const command:SalonCommand={type:"APPOINTMENT_SAVE",mutation_id:salonId(201),id:a.id,expected_version:0,definition:{client_id:a.client_id,service_id:a.service_id,staff_membership_id:membership_id,local_start:"2026-10-12T10:00",utc_offset_minutes:null,scheduled_duration_minutes:null,adjustment_reason:null,notes:null,status:"CONFIRMED"}};
 return {context,snapshot,a,command,definition};
}
