import { act,cleanup,fireEvent,render,screen,waitFor } from "@testing-library/react";
import { afterEach,beforeEach,expect,it,vi } from "vitest";
import { crmFixture } from "@/test/crm-fixtures";
import { salonId as id } from "@/test/salon-fixtures";
const navigation=vi.hoisted(()=>({push:vi.fn()}));
vi.mock("next/navigation",()=>({useRouter:()=>navigation}));
import { ClientCrm } from "./client-crm";
import { ClientCrmDirectory } from "./client-crm-directory";
const fetcher=vi.fn();
beforeEach(()=>{vi.stubGlobal("fetch",fetcher);fetcher.mockImplementation(async(_url:string,init:RequestInit)=>{const f=crmFixture(),q=JSON.parse(init.body as string),data=q.operation==="summary"?f.overview:q.operation==="options"?f.options:q.operation==="list"?{items:[{id:id(31),full_name:"Synthetic client",phone_masked:"+90•••567",status:"ACTIVE",summary:f.summary}],has_more:false,offset:0,next_offset:200,scan_limit:200}:{items:[],has_more:false,offset:0};return new Response(JSON.stringify({data,context:f.context}),{status:200});});});
afterEach(()=>{cleanup();vi.unstubAllGlobals();vi.clearAllMocks();});
it("unknown relationship data stays explicit and rebooking remains a link",async()=>{render(<ClientCrm clientId={id(31)} context={crmFixture().context}/>);await screen.findByText("Tamamlanan ziyaret");expect(screen.getByText("Yeterli veri yok")).toBeVisible();expect(screen.getByText("Henüz çıkarım yok",{exact:false})).toBeVisible();expect(screen.getByRole("link",{name:"Yeniden randevu hazırla"})).toHaveAttribute("href",`/workspace/appointments?client_id=${id(31)}`);expect(fetcher.mock.calls.every(c=>!JSON.parse(c[1].body).type)).toBe(true);});
it("role-bound note editor cannot offer manager or technical visibility to reception",async()=>{const f=crmFixture();f.context.permissions=["crm.read","crm.notes.reception"];fetcher.mockImplementation(async(_url:string,init:RequestInit)=>{const q=JSON.parse(init.body as string),data=q.operation==="summary"?f.overview:q.operation==="options"?f.options:{items:[],has_more:false,offset:0};return new Response(JSON.stringify({data,context:f.context}));});render(<ClientCrm clientId={id(31)} context={f.context}/>);await screen.findByRole("button",{name:"Notlar"});fireEvent.click(screen.getByRole("button",{name:"Notlar"}));await screen.findByLabelText("Görünürlük");expect(screen.queryByRole("option",{name:"Yönetime özel"})).toBeNull();expect(screen.queryByRole("option",{name:"Teknik"})).toBeNull();expect(screen.getByRole("option",{name:"Resepsiyon"})).toBeVisible();});
it("failed scoped read releases no customer summary",async()=>{fetcher.mockResolvedValue(new Response(JSON.stringify({code:"FORBIDDEN"}),{status:403}));render(<ClientCrm clientId={id(31)} context={crmFixture().context}/>);await screen.findByRole("alert");expect(screen.queryByText("Tamamlanan ziyaret")).toBeNull();});
it("finder shows editable filters and never auto-runs interpreted results",async()=>{const f=crmFixture();fetcher.mockImplementation(async(url:string,init:RequestInit)=>{const q=JSON.parse(init.body as string);const data=url.endsWith("interpret")?{status:"MAPPED",filter:{last_visit_min_days:60},explanations:["Son ziyaret en az 60 gün önce."],ambiguities:[]}:q.operation==="options"?f.options:{items:[],has_more:false,offset:0,next_offset:200,scan_limit:200};return new Response(JSON.stringify({data,context:f.context}));});render(<ClientCrmDirectory context={f.context}/>);await screen.findByText("Henüz müşteri yok");fireEvent.change(screen.getByLabelText("Arama isteği"),{target:{value:"60 gündür gelmeyen müşteriler"}});fireEvent.click(screen.getByRole("button",{name:"Filtre olarak yorumla"}));await screen.findByText("Son ziyaret en az 60 gün önce.");expect(screen.getByLabelText("Son ziyaretten en az gün")).toHaveValue(60);await waitFor(()=>expect(fetcher.mock.calls.filter(c=>JSON.parse(c[1].body).operation==="list")).toHaveLength(1));});

it("staff preference exposes a stable exact accessible field name",async()=>{render(<ClientCrm clientId={id(31)} context={crmFixture().context}/>);await screen.findByText("Tamamlanan ziyaret");expect(screen.getByLabelText("Tercih edilen personel",{exact:true})).toHaveAttribute("aria-label","Tercih edilen personel");});

it("action rebooking uses a fresh canonical summary without saving an appointment",async()=>{const f=crmFixture(),stamp=f.summary.computed_at;const action={id:id(401),organization_id:id(1),location_id:id(11),client_id:id(31),kind:"REBOOK",source_domain:"salon_appointment",source_id:id(301),basis:{},status:"OPEN",effective_status:"OPEN",due_at:stamp,snoozed_until:null,version:1,created_at:stamp,updated_at:stamp,created_by:id(21),updated_by:id(21)};fetcher.mockImplementation(async(_url:string,init:RequestInit)=>{const q=JSON.parse(init.body as string),data=q.operation==="options"?f.options:q.operation==="actions"?{items:[action],has_more:false,offset:0}:q.operation==="summary"?{...f.overview,summary:{...f.summary,client_id:id(32),source_client_ids:[id(31),id(32)],last_completed_service:{id:id(101),name:"Dip boya",appointment_id:id(301)},preferred_staff:{source:"MANUAL_PREFERENCE",membership_id:id(111),name:"Selin",count:null,sample_size:null}}}:{items:[],has_more:false,offset:0,next_offset:200,scan_limit:200};return new Response(JSON.stringify({data,context:f.context}));});render(<ClientCrmDirectory context={f.context}/>);await screen.findByText("Henüz müşteri yok");fireEvent.click(screen.getByRole("button",{name:"CRM aksiyon merkezi"}));fireEvent.click(await screen.findByRole("button",{name:"Randevu oluştur"}));await waitFor(()=>expect(navigation.push).toHaveBeenCalledWith(`/workspace/appointments?client_id=${id(32)}&service_id=${id(101)}&staff_id=${id(111)}`));expect(fetcher.mock.calls.some(c=>JSON.parse(c[1].body).operation==="summary")).toBe(true);expect(fetcher.mock.calls.every(c=>!JSON.parse(c[1].body).type)).toBe(true);});

it("saved note text does not change its accessible field name",async()=>{const f=crmFixture(),stamp=f.summary.computed_at,note={id:id(611),organization_id:id(1),location_id:id(11),client_id:id(31),visibility:"PRIVATE_MANAGEMENT",body:"Management note",archived:false,version:1,created_at:stamp,updated_at:stamp,created_by:id(21),updated_by:id(21)};fetcher.mockImplementation(async(_url:string,init:RequestInit)=>{const q=JSON.parse(init.body as string),data=q.operation==="summary"?f.overview:q.operation==="options"?f.options:{items:q.operation==="notes"?[note]:[],has_more:false,offset:0};return new Response(JSON.stringify({data,context:f.context}));});render(<ClientCrm clientId={id(31)} context={f.context}/>);fireEvent.click(await screen.findByRole("button",{name:"Notlar"}));await waitFor(()=>expect(screen.getAllByLabelText("Not",{exact:true})).toHaveLength(2));expect(screen.getAllByLabelText("Not",{exact:true})[1]).toHaveValue("Management note");});

it("a delayed precheck cannot describe a replacement upcoming appointment",async()=>{const f=crmFixture(),stamp=f.summary.computed_at;let refresh=()=>{},release=()=>{};const original=window.setInterval,interval=vi.spyOn(window,"setInterval").mockImplementation(((handler:TimerHandler,timeout?:number,...args:unknown[])=>{if(timeout===15000){refresh=handler as ()=>void;return original(()=>{},timeout);}return original(handler,timeout,...args);}) as typeof window.setInterval);const visible=vi.spyOn(document,"hidden","get").mockReturnValue(false);let upcoming={id:id(301),client_id:id(31),start_at:stamp,service_id:id(101),service_name:"First booking",staff_id:id(111),staff_name:"Selin",status:"CONFIRMED",precheck:"NOT_ASSESSED"};const pending=new Promise<Response>(resolve=>{release=()=>resolve(new Response(JSON.stringify({context:f.context,data:{appointment_id:id(301),appointment_version:1,evaluated_at:stamp,statuses:["READY"],reasons:[],risk:null,freshness:{state:"MISSING",updated_at:null},recovery:"NOT_ASSESSED",complexity:"UNKNOWN",integrity_history:[],recent_technical_history:[],last_formula:null,last_outcome:null,duration:{source:"SERVICE_DEFAULT",sample_count:0,estimated_minutes:60,allocated_minutes:60,additional_minutes:0},competencies:[],recipe_created:false}})));});fetcher.mockImplementation(async(url:string,init:RequestInit)=>{if(url.endsWith("precheck"))return pending;const q=JSON.parse(init.body as string),data=q.operation==="summary"?{...f.overview,summary:{...f.summary,upcoming_appointment:upcoming}}:q.operation==="options"?f.options:{items:[],has_more:false,offset:0};return new Response(JSON.stringify({data,context:f.context}));});try{render(<ClientCrm clientId={id(31)} context={f.context}/>);fireEvent.click(await screen.findByRole("button",{name:"Teknik ön kontrolü aç"}));upcoming={...upcoming,id:id(302),service_name:"Replacement booking"};await act(async()=>refresh());await screen.findByText(/Replacement booking/);await act(async()=>release());expect(screen.queryByText("Ön kontrol uygun",{exact:true})).toBeNull();expect(screen.getByText("Ön kontrol henüz değerlendirilmedi.",{exact:true})).toBeVisible();}finally{interval.mockRestore();visible.mockRestore();}});
