"use client";
import { useCallback,useEffect,useRef,useState } from "react";
import { z } from "zod";
import { options,type CrmCommand } from "@/lib/crm/model";
import { crmMessages } from "@/lib/crm/labels";
import { tenantContextSchema,workspaceReference,type ActiveTenantContext } from "@/lib/tenant/context";
import { SalonCard } from "./salon-frame";
type Command=CrmCommand extends infer C?C extends CrmCommand?Omit<C,"mutation_id">:never:never;
export function ClientCrmSettings({context}:{context:ActiveTenantContext}){const [data,setData]=useState<z.infer<typeof options>|null>(null),[revision,setRevision]=useState(0),[error,setError]=useState(""),[busy,setBusy]=useState(false),pending=useRef<{body:string;id:string}|null>(null),reference=workspaceReference(context);const call=useCallback(async(raw:object,write=false)=>{const r=await fetch(`/api/crm${write?"":"/read"}`,{method:"POST",headers:{"content-type":"application/json","x-workspace-reference":reference},body:JSON.stringify(raw),cache:"no-store",signal:AbortSignal.timeout(15000)}),b=await r.json();if(!r.ok)throw new Error(b.code);if(workspaceReference(tenantContextSchema.parse(b.context))!==reference)throw new Error("TENANT_CONTEXT_INVALID");return b.data;},[reference]);useEffect(()=>{let alive=true;call({operation:"options"}).then(raw=>{if(alive)setData(options.parse(raw));}).catch(e=>{if(alive){setData(null);setError(crmMessages[e.message]??"CRM ayarları doğrulanamadı.");}});return()=>{alive=false;};},[call,revision]);const execute=async(command:Command)=>{if(busy)return;setBusy(true);const body=JSON.stringify(command);if(pending.current?.body!==body)pending.current={body,id:crypto.randomUUID()};try{await call({...command,mutation_id:pending.current.id},true);pending.current=null;setError("");setRevision(r=>r+1);}catch(e){setError(crmMessages[e instanceof Error?e.message:""]??"İşlem doğrulanamadı.");}finally{setBusy(false);}};return <section className="crm-panel" aria-label="CRM dönüş ayarları"><SalonCard title="Hizmete özel müşteri dönüş aralıkları"><p>Aralıklar salon tarafından belirlenir. Alanları boş bırakmak bilinmiyor anlamına gelir; evrensel dönüş süresi uygulanmaz.</p>{error&&<p role="alert">{error}</p>}{data?.services.map(service=><ReturnEditor key={`${service.id}:${service.return_window?.version??0}`} service={service} disabled={busy||!context.permissions.includes("salon.catalog.manage")} execute={execute}/>)}</SalonCard>{data&&context.permissions.includes("crm.policy.manage")&&<PolicyEditor key={data.policy?.version??0} policy={data.policy} disabled={busy} execute={execute}/>}</section>;}
function ReturnEditor({service,disabled,execute}:{service:z.infer<typeof options>["services"][number];disabled:boolean;execute:(c:Command)=>Promise<void>}){const [min,setMin]=useState(String(service.return_window?.min_days??"")),[max,setMax]=useState(String(service.return_window?.max_days??""));return <form className="crm-form" onSubmit={e=>{e.preventDefault();void execute({type:"RETURN_WINDOW_SAVE",service_id:service.id,expected_version:service.return_window?.version??0,min_days:min?Number(min):null,max_days:max?Number(max):null});}}><fieldset disabled={disabled}><legend>{service.name}{!service.active&&" · Arşivde"}</legend><div className="crm-filter-row"><label>En erken gün<input type="number" min={1} max={730} required={!!max} value={min} onChange={e=>setMin(e.target.value)}/></label><label>En geç gün<input type="number" min={Number(min)||1} max={730} required={!!min} value={max} onChange={e=>setMax(e.target.value)}/></label><button className="button button-secondary">Dönüş aralığını kaydet</button></div></fieldset></form>;}
function PolicyEditor({policy,disabled,execute}:{policy:z.infer<typeof options>["policy"];disabled:boolean;execute:(c:Command)=>Promise<void>}){const [days,setDays]=useState(String(policy?.inactive_after_overdue_days??""));return <SalonCard title="Uzun süre gelmeme eşiği"><form className="crm-form" onSubmit={e=>{e.preventDefault();void execute({type:"POLICY_SAVE",expected_version:policy?.version??0,inactive_after_overdue_days:days?Number(days):null});}}><fieldset disabled={disabled}><label>Hizmet dönüş aralığı geçtikten sonra kaç gün?<input type="number" min={1} max={3650} value={days} onChange={e=>setDays(e.target.value)}/></label><p>Boş bırakılırsa uzun süre gelmedi çıkarımı ve geri dönüş aksiyonu üretilmez.</p><button className="button button-primary">İlişki eşiğini kaydet</button></fieldset></form></SalonCard>;}
