import { afterEach,beforeEach,expect,it,vi } from "vitest";
import { cleanup,fireEvent,render,screen,waitFor } from "@testing-library/react";
import fixture from "../../../contracts/fixtures/controlled-recipe-contract.json";
import { storedControlledRecipe } from "@/lib/brand/controlled-model";
import { ControlledRecipe } from "./controlled-recipe";
const record=storedControlledRecipe.parse(fixture.stored),correlationId=record.id;
const props={clientId:record.clientId,planId:record.planId,reference:"synthetic",enabled:true,canCreate:true};
const options={schemaVersion:1,status:"OPTIONS_FOR_REVIEW",catalogId:record.catalogId,catalogVersion:1,catalogFingerprint:"a".repeat(64),candidates:[record.result.selected],whiteRatio:.95,evidenceIds:record.result.context.evidenceIds,regionId:record.result.context.regionId,executable:false,explanation:"Source-qualified options"};
const create=vi.fn(),fetcher=vi.fn();
beforeEach(()=>{
 vi.clearAllMocks();create.mockResolvedValue(Response.json({data:record,correlationId}));
 fetcher.mockImplementation(async(url,init)=>String(url).endsWith("/catalogs")?Response.json({data:[{id:record.catalogId,version:1}],correlationId}):String(url).includes("?client_id=")?Response.json({data:[],correlationId}):String(url).endsWith("/options")?Response.json({data:options,correlationId}):create(url,init));
 vi.stubGlobal("fetch",fetcher);
});
afterEach(()=>{cleanup();vi.unstubAllGlobals();});
async function ready(){render(<ControlledRecipe {...props}/>);await waitFor(()=>expect(screen.getByLabelText("Doğrulanmış katalog")).toHaveValue(record.catalogId));fireEvent.click(screen.getByRole("button",{name:"Uyumlu tonları getir"}));await screen.findByText("Source-qualified options",{exact:false});}
function select(){fireEvent.change(screen.getByLabelText("Uzman ton ve geliştirici seçimi"),{target:{value:`${record.result.selected.productId}:${record.result.selected.developerId}`}});fireEvent.change(screen.getByLabelText("Boya miktarı (g)"),{target:{value:"30.15"}});}
it("no quantity is prefilled or treated as dosage advice",async()=>{await ready();expect(screen.getByLabelText("Boya miktarı (g)")).toHaveValue(null);expect(screen.getByRole("button",{name:"Kontrollü taslağı kaydet"})).toBeDisabled();expect(screen.getByText(/uygulama izni vermez/)).toBeVisible();});
it("sends only professional selection and displays stored arithmetic and source range",async()=>{await ready();select();fireEvent.click(screen.getByRole("button",{name:"Kontrollü taslağı kaydet"}));await screen.findByText(/Toplam: 60.3 g/);const body=JSON.parse(create.mock.calls[0]![1].body);expect(body).toMatchObject({client_id:record.clientId,plan_id:record.planId,color_grams:30.15,supersedes_id:null});expect(Object.keys(body).sort()).toEqual(["catalog_id","client_id","color_grams","developer_id","plan_id","product_id","request_id","supersedes_id"].sort());expect(screen.getByText(/Uygulama başlatılamaz.*30–45 dakika/)).toBeVisible();});
it("network retry retains the same request identity and parent",async()=>{await ready();select();create.mockRejectedValueOnce(new Error("network"));fireEvent.click(screen.getByRole("button",{name:"Kontrollü taslağı kaydet"}));await screen.findByRole("alert");fireEvent.click(screen.getByRole("button",{name:"Kontrollü taslağı kaydet"}));await screen.findByText(/Toplam: 60.3 g/);expect(create.mock.calls[0]![1].body).toBe(create.mock.calls[1]![1].body);});
it("editing a saved draft sends a new identity and explicit parent, preserving prior result",async()=>{await ready();select();fireEvent.click(screen.getByRole("button",{name:"Kontrollü taslağı kaydet"}));await screen.findByText(/Toplam: 60.3 g/);fireEvent.change(screen.getByLabelText("Boya miktarı (g)"),{target:{value:"45"}});create.mockResolvedValueOnce(Response.json({data:{...record,id:"c1000000-0000-4000-8000-000000050002",version:2,supersedesId:record.id,result:{...record.result,colorGrams:45,developerGrams:45,totalGrams:90}},correlationId}));fireEvent.click(screen.getByRole("button",{name:"Yeni reçete sürümünü kaydet"}));await screen.findByText(/Toplam: 90 g/);const first=JSON.parse(create.mock.calls[0]![1].body),second=JSON.parse(create.mock.calls[1]![1].body);expect(second.supersedes_id).toBe(record.id);expect(second.request_id).not.toBe(first.request_id);expect(record.result.colorGrams).toBe(30.15);});
it("read-only membership cannot save a professional selection",async()=>{render(<ControlledRecipe {...props} canCreate={false}/>);await waitFor(()=>expect(screen.getByLabelText("Doğrulanmış katalog")).toHaveValue(record.catalogId));fireEvent.click(screen.getByRole("button",{name:"Uyumlu tonları getir"}));await screen.findByText("Source-qualified options",{exact:false});select();expect(screen.getByRole("button",{name:"Kontrollü taslağı kaydet"})).toBeDisabled();expect(create).not.toHaveBeenCalled();});
it("loss of validated context hides a pending result",async()=>{
 let resolve!:(value:Response)=>void;create.mockImplementationOnce(()=>new Promise<Response>(r=>{resolve=r;}));
 const view=render(<ControlledRecipe {...props}/>);await waitFor(()=>expect(screen.getByLabelText("Doğrulanmış katalog")).toHaveValue(record.catalogId));fireEvent.click(screen.getByRole("button",{name:"Uyumlu tonları getir"}));await screen.findByText("Source-qualified options",{exact:false});select();fireEvent.click(screen.getByRole("button",{name:"Kontrollü taslağı kaydet"}));await waitFor(()=>expect(create).toHaveBeenCalled());view.rerender(<ControlledRecipe {...props} enabled={false}/>);resolve(Response.json({data:record,correlationId}));await waitFor(()=>expect(screen.queryByText(/Toplam: 60.3 g/)).toBeNull());expect(screen.getByLabelText("Kontrollü marka reçetesi")).not.toBeVisible();
});
