"use client";
import {useCallback,useEffect,useRef,useState} from "react";
import Link from "next/link";
import {SalonFrame,SalonHeading,SalonCard,SalonStat} from "./salon-frame";
import {financeSnapshot,financeCommand,financePermission,financeResult,parseMoney,formatMoney,type FinanceSnapshot,type FinanceCommand} from "@/lib/finance/model";
import {tenantContextSchema,workspaceReference,type ActiveTenantContext} from "@/lib/tenant/context";
const labels:Record<string,string>={SERVICE_CHARGE:"Hizmet ücreti",MANUAL_CHARGE:"Manuel hizmet ücreti",RETAIL_SALE:"Perakende satış",PAYMENT:"Ödeme",DEPOSIT:"Depozito",ALLOCATE:"Kredi uygula",REFUND:"Para iadesi",REVERSAL:"Kayıt iptali",EXPENSE:"Gider",CLIENT_CREDIT:"Müşteri alacağı",CLIENT_DEBIT:"Müşteri borcu",ADJUSTMENT:"Kasa düzeltmesi",CASH_OPEN:"Kasa aç",CASH_CLOSE_SUBMIT:"Kasa sayımı",CURRENCY_SET:"Finans başlangıcı",CASH:"Nakit",CARD:"Kart",BANK_TRANSFER:"Havale",OTHER:"Diğer",RENT:"Kira",UTILITIES:"Faturalar",SUPPLIES:"Sarf malzemeleri",MAINTENANCE:"Bakım",MARKETING:"Pazarlama",OPEN:"Açık",CLOSING_REVIEW:"Kapanış kontrolü",CLOSED:"Kapalı"};
const errors:Record<string,string>={FINANCE_ALLOCATION_CONFLICT:"Ödeme veya ücretin kalan tutarı değişti. Yenileyip dağıtımı kontrol edin.",FINANCE_REFUND_LIMIT:"İade, ödemenin iade edilebilir tutarını aşamaz.",FINANCE_CONFLICT:"Kayıt değişti veya işlem kimliği farklı içerikle kullanıldı.",CASH_NOT_OPEN:"Nakit işlem için açık kasa gerekli.",CASH_CLOSE_STALE:"Kasa sayımından sonra yeni hareket oluştu. Yeniden sayım gönderin.",CASH_DIFFERENCE_ACK_REQUIRED:"Kasa farkını açıkça onaylayın; otomatik dengeleme yapılmaz.",CASH_DATE_OUTSIDE_SESSION:"Nakit işlem tarihi açık kasa döneminde olmalı.",CASH_HISTORY_CLOSED:"Kapalı kasa geçmişi değiştirilemez. Gerçek para iadesini yeni açık kasada kaydedin.",OVERPAYMENT_CONFIRM_REQUIRED:"Dağıtılmayan tutarın müşteri kredisi olacağını onaylayın.",CURRENCY_LOCKED:"Finans hareketinden sonra temel para birimi değiştirilemez.",CURRENCY_MISMATCH:"Para birimi organizasyonun temel para birimiyle aynı olmalı.",SERVICE_NOT_COMPLETED:"Yalnız tamamlanmış randevu ücretlendirilebilir.",FINANCE_CHARGE_HAS_PAYMENTS:"Dağıtılmış ödeme bulunan ücret önce ödeme kayıtları düzeltilmeden iptal edilemez.",CLIENT_NOT_CURRENT:"Yeni işlem için güncel müşteri kimliğini seçin.",STOCK_INSUFFICIENT:"Perakende stok yetersiz. Satış ve stok hareketi kaydedilmedi.",STOCK_LOT_REQUIRED:"Bu ürün için gerçek lot kimliğini seçin.",STOCK_OPENING_REQUIRED:"Ürünün ölçülmüş stok açılışı gerekli.",VALIDATION_FAILED:"Alanları ve para biriminin ondalık hassasiyetini kontrol edin.",NETWORK_ERROR:"Finans yüklenemedi. Aynı işlemi tekrar denemek güvenlidir."};
type Mode=Exclude<FinanceCommand["type"],"CASH_CLOSE_CONFIRM">;
const currentLocal=()=>{const d=new Date();return new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,23);};
export function FinanceWorkspace(){
 const [data,setData]=useState<FinanceSnapshot|null>(null),[ctx,setCtx]=useState<ActiveTenantContext|null>(null),[error,setError]=useState(""),[notice,setNotice]=useState(""),[busy,setBusy]=useState(false),[mode,setMode]=useState<Mode|null>(null),[clientId,setClientId]=useState(""),[day,setDay]=useState(""),[offset,setOffset]=useState(0),[documentId,setDocumentId]=useState(""),[allocationRows,setAllocationRows]=useState([0]),[formKey,setFormKey]=useState(""),[retailItem,setRetailItem]=useState("");
 const generation=useRef(0),context=useRef<ActiveTenantContext|null>(null),filters=useRef<Record<string,string|number>>({}),pending=useRef<{key:string;id:string}|null>(null),formId=useRef("");
 const cancelRequests=useCallback(()=>{generation.current++;},[]);
 const conceal=useCallback(()=>{generation.current++;context.current=null;setCtx(null);setData(null);setMode(null);setDocumentId("");},[]);
 const fail=useCallback((code:string)=>{if(["FORBIDDEN","UNAUTHENTICATED","SESSION_EXPIRED","MEMBERSHIP_REQUIRED","MEMBERSHIP_REVOKED","TENANT_CONTEXT_INVALID"].includes(code)){conceal();window.location.assign(["UNAUTHENTICATED","SESSION_EXPIRED"].includes(code)?"/sign-in":"/workspaces");}else setError(errors[code]??code);},[conceal]);
 const load=useCallback(async()=>{const n=++generation.current;try{const q=new URLSearchParams(Object.entries(filters.current).map(([k,v])=>[k,String(v)])),r=await fetch("/api/finance?"+q,{cache:"no-store"}),b=await r.json();if(n!==generation.current||document.hidden)return;if(!r.ok){fail(b.code??"NETWORK_ERROR");return;}const c=tenantContextSchema.parse(b.context),d=financeSnapshot.parse(b.data);if(context.current&&workspaceReference(context.current)!==workspaceReference(c)){conceal();return;}context.current=c;setCtx(c);setData(d);setDay(d.day);setError("");}catch{if(n===generation.current)fail("NETWORK_ERROR");}},[conceal,fail]);
 useEffect(()=>{const initial=setTimeout(()=>{const q=new URLSearchParams(window.location.search);for(const key of ["client_id","appointment_id","document_id"]){const v=q.get(key);if(v&&/^[0-9a-f-]{36}$/i.test(v)){filters.current[key]=v;if(key==="client_id")setClientId(v);if(key==="document_id")setDocumentId(v);}}void load();},0);const changed=()=>{conceal();if(!document.hidden)void load();};document.addEventListener("visibilitychange",changed);window.addEventListener("focus",changed);const timer=setInterval(()=>{if(!document.hidden)void load();},15000);return()=>{cancelRequests();clearTimeout(initial);clearInterval(timer);document.removeEventListener("visibilitychange",changed);window.removeEventListener("focus",changed);};},[load,conceal,cancelRequests]);
 const can=(p:string)=>ctx?.permissions.includes(p)??false,code=data?.settings?.currency??"TRY",exponent=data?.settings?.exponent??2;
 const money=(s:string|null|undefined)=>s===null||s===undefined?"Yetki kapsamında değil":formatMoney(s,code,exponent);
 function open(m:Mode){setMode(m);setError("");setAllocationRows([0]);setRetailItem(data?.stock_items[0]?.id??"");formId.current=crypto.randomUUID();setFormKey(formId.current);pending.current=null;}
 async function save(raw:unknown){const parsed=financeCommand.safeParse(raw),c=context.current;if(!parsed.success){fail("VALIDATION_FAILED");return;}if(!c||busy)return;const q=parsed.data,key=JSON.stringify({...q,mutation_id:undefined});if(pending.current?.key!==key)pending.current={key,id:q.mutation_id};const n=generation.current;setBusy(true);setNotice("");setError("");try{const r=await fetch("/api/finance",{method:"POST",headers:{"Content-Type":"application/json","x-workspace-reference":workspaceReference(c)},body:JSON.stringify({...q,mutation_id:pending.current.id})}),b=await r.json();if(n!==generation.current||document.hidden)return;if(!r.ok){fail(b.code??"NETWORK_ERROR");return;}financeResult.parse(b.data);pending.current=null;setMode(null);setNotice("Finans işlemi kaydedildi.");await load();}catch{fail("NETWORK_ERROR");}finally{setBusy(false);}}
 async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(!mode||!data)return;const f=new FormData(e.currentTarget),text=(k:string)=>String(f.get(k)??"").trim(),optional=(k:string)=>text(k)||null,base={type:mode,mutation_id:crypto.randomUUID(),reason:text("reason")},posted={...base,id:formId.current,currency:code,occurred_at:text("occurred_at")?new Date(text("occurred_at")).toISOString():new Date().toISOString()};let q:unknown;
  try{const amount=(k="amount")=>parseMoney(text(k),exponent),allocations=allocationRows.filter(i=>text("charge_"+i)).map(i=>({charge_id:text("charge_"+i),amount_minor:amount("allocation_"+i)}));
   if(mode==="CURRENCY_SET")q={...base,currency:text("currency"),expected_version:data.settings?.version??0};
   else if(mode==="CASH_OPEN")q={...base,id:formId.current,currency:code,opening_cash_minor:amount("opening")};
   else if(mode==="CASH_CLOSE_SUBMIT")q={...base,id:data.cash_sessions.find(s=>s.status!=="CLOSED")?.id,expected_version:data.cash_sessions.find(s=>s.status!=="CLOSED")?.version,counted_cash_minor:amount("counted")};
   else if(mode==="SERVICE_CHARGE")q={...base,id:formId.current,appointment_id:text("appointment_id")};
   else if(mode==="MANUAL_CHARGE")q={...posted,client_id:text("client_id"),amount_minor:amount(),tax_rate_bps:Number(parseMoney(text("tax_rate"),2)),tax_inclusive:f.has("tax_inclusive"),description:text("description")};
   else if(mode==="RETAIL_SALE")q={...posted,client_id:text("client_id"),stock_item_id:text("stock_item_id"),lot_id:optional("lot_id"),quantity:text("quantity").replace(",","."),unit_price_minor:amount("unit_price"),tax_rate_bps:Number(parseMoney(text("tax_rate"),2)),tax_inclusive:f.has("tax_inclusive"),description:text("description")};
   else if(mode==="PAYMENT"||mode==="DEPOSIT")q={...posted,client_id:text("client_id"),amount_minor:amount(),method:text("method"),appointment_id:optional("appointment_id"),external_reference:optional("external_reference"),...(mode==="PAYMENT"?{allocations,confirm_credit:f.has("confirm_credit")}: {})};
   else if(mode==="ALLOCATE")q={...base,client_id:text("client_id"),payment_id:text("payment_id"),allocations};
   else if(mode==="REFUND")q={...base,id:formId.current,original_payment_id:text("payment_id"),amount_minor:amount(),occurred_at:posted.occurred_at};
   else if(mode==="REVERSAL")q={...base,id:formId.current,document_id:documentId};
   else if(mode==="EXPENSE")q={...posted,amount_minor:amount(),method:text("method"),category:text("category"),description:text("description"),stock_receipt_id:optional("stock_receipt_id"),external_reference:optional("external_reference")};
   else q={...posted,amount_minor:amount(),description:text("description"),...(mode==="ADJUSTMENT"?{direction:text("direction")}: {client_id:text("client_id")})};
  }catch{fail("VALIDATION_FAILED");return;}await save(q);
 }
 const closedCash=data?.cash_sessions.find(s=>s.status==="CLOSED"),cash=data?.cash_sessions.find(s=>s.status!=="CLOSED"),selected=data?.documents.find(d=>d.id===documentId),charges=data?.documents.filter(d=>d.outstanding_minor!==null&&BigInt(d.outstanding_minor)>0n)??[],credits=data?.documents.filter(d=>d.available_credit_minor!==null&&BigInt(d.available_credit_minor)>0n)??[];
 const clientField=<label>Müşteri<select name="client_id" required defaultValue={clientId}><option value="">Seçin</option>{data?.clients.map(c=><option key={c.id} value={c.id}>{c.display_name}</option>)}</select></label>;
 const methodField=<label>Ödeme yöntemi<select name="method">{["CASH","CARD","BANK_TRANSFER","OTHER"].map(m=><option key={m} value={m}>{labels[m]}</option>)}</select></label>;
 const allocationFields=<div className="stock-span"><p>Dağıtım açıkça kaydedilir. Bir ücreti birden fazla ödeme yöntemiyle ödeyebilirsiniz.</p>{allocationRows.map(i=><div className="finance-allocation" key={i}><label>Ücret {i+1}<select name={"charge_"+i}><option value="">Dağıtım yok</option>{charges.map(d=><option key={d.id} value={d.id}>{d.description} Â· kalan {money(d.outstanding_minor)}</option>)}</select></label><label>Dağıtılacak tutar {i+1}<input name={"allocation_"+i} inputMode="decimal" placeholder="0"/></label></div>)}{allocationRows.length<20&&<button type="button" className="text-link" onClick={()=>setAllocationRows(r=>[...r,r.length])}>Dağıtım satırı ekle</button>}</div>;
 return <SalonFrame active="finance" workspace={ctx?.location_name}><main id="main-content" className="salon-main stock-workspace finance-workspace"><SalonHeading title="Salon finansı" description="Ücretleri, ödemeleri, müşteri hesaplarını ve kasayı kayıtlarla takip edin." actions={<button className="button button-secondary" onClick={()=>void load()}>Yenile</button>}/>{error&&<p role="alert" className="stock-error">{error}</p>}{notice&&<p role="status">{notice}</p>}
 {!data?<SalonCard><p>Finans yükleniyor…</p></SalonCard>:<>
 {!data.settings?<SalonCard title="Finans başlangıcı"><p>Organizasyon için tek temel para birimi seçin. Finans hareketinden sonra değiştirilemez.</p>{can("finance.adjust")&&<button className="button" onClick={()=>open("CURRENCY_SET")}>Temel para birimini seç</button>}</SalonCard>:<>
 <div className="stock-toolbar"><label>Gün<input type="date" value={day} onChange={e=>{setDay(e.target.value);filters.current.day=e.target.value;filters.current.offset=0;setOffset(0);void load();}}/></label><label>Müşteri hesabı<select value={clientId} onChange={e=>{setClientId(e.target.value);if(e.target.value)filters.current.client_id=e.target.value;else delete filters.current.client_id;delete filters.current.appointment_id;filters.current.offset=0;setOffset(0);setDocumentId("");void load();}}><option value="">Tüm müşteriler</option>{data.clients.map(c=><option key={c.id} value={c.id}>{c.display_name}</option>)}</select></label></div>
 <div className="salon-stats"><SalonStat label="Günlük hizmet ücretleri" value={money(data.summary.service_charges_minor)} icon="reports"/><SalonStat label="Alınan ödemeler" value={money(data.summary.payments_minor)} icon="finance"/><SalonStat label="Para iadeleri" value={money(data.summary.refunds_minor)} icon="reports"/><SalonStat label="Müşteri hesap bakiyesi" value={money(data.summary.open_client_balance_minor)} icon="clients"/></div>
 <div className="stock-toolbar">{(["SERVICE_CHARGE","MANUAL_CHARGE","RETAIL_SALE","PAYMENT","DEPOSIT","ALLOCATE","REFUND","EXPENSE","CLIENT_CREDIT","CLIENT_DEBIT","ADJUSTMENT"] as const).filter(t=>can(financePermission(t))).map(t=><button key={t} className={t==="PAYMENT"?"button":"button button-secondary"} onClick={()=>open(t)}>{labels[t]}</button>)}</div>
 <div className="stock-columns"><SalonCard title="Ödeme yöntemleri">{data.summary.payments_by_method.map(p=><p key={p.method}>{labels[p.method]} Â· {money(p.amount_minor)}</p>)}{!data.summary.payments_by_method.length&&<p>Bu gün ödeme kaydı yok.</p>}<p>Depozito: {money(data.summary.deposits_minor)}</p><p>Perakende: {money(data.summary.retail_sales_minor)}</p>{can("finance.expense.view")&&<p>Giderler: {money(data.summary.expenses_minor)}</p>}</SalonCard><SalonCard title="Kasa oturumu">{cash?<><p>{labels[cash.status]}</p>{cash.opening_cash_minor!==undefined&&<><p>Açılış: {money(cash.opening_cash_minor)}</p><p>Nakit giriş: {money(cash.cash_in_minor)}</p><p>Nakit çıkış: {money(cash.cash_out_minor)}</p><p>Beklenen: {money(cash.current_expected_minor)}</p>{cash.counted_cash_minor!==null&&cash.counted_cash_minor!==undefined&&<><p>Sayılan: {money(cash.counted_cash_minor)}</p><p>Fark: {money(cash.difference_minor)} Â· {BigInt(cash.difference_minor??"0")===0n?"Eşleşti":BigInt(cash.difference_minor??"0")>0n?"Fazla":"Eksik"}</p></>}</>}{can("finance.cash.close")&&<button className="button button-secondary" onClick={()=>open("CASH_CLOSE_SUBMIT")}>Kasa sayımını gönder</button>}{cash.status==="CLOSING_REVIEW"&&can("finance.cash.close")&&<form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void save({type:"CASH_CLOSE_CONFIRM",mutation_id:crypto.randomUUID(),id:cash.id,expected_version:cash.version,acknowledge_difference:f.has("ack"),reason:String(f.get("reason")??"")});}}><label className="finance-check"><input name="ack" type="checkbox"/>Kasa farkını gördüm; dengeleme kaydı yapılmayacak.</label><label>Kapanış gerekçesi<input name="reason" required maxLength={2000}/></label><button className="button" disabled={busy}>Kasayı kapat</button></form>}</>:<><p>Açık kasa yok.</p>{can("finance.cash.open")&&<button className="button" onClick={()=>open("CASH_OPEN")}>Kasa aç</button>}</>}{closedCash&&can("finance.cash.close")&&<div className="finance-cash-history"><h3>Son kasa kapanışı</h3><p>Açılış: {money(closedCash.opening_cash_minor)} · Nakit giriş: {money(closedCash.cash_in_minor)} · Nakit çıkış: {money(closedCash.cash_out_minor)}</p><p>Beklenen: {money(closedCash.expected_cash_minor)} · Sayılan: {money(closedCash.counted_cash_minor)}</p><p>Fark: {money(closedCash.difference_minor)} · {BigInt(closedCash.difference_minor??"0")===0n?"Eşleşti":BigInt(closedCash.difference_minor??"0")>0n?"Fazla":"Eksik"}</p><p>{closedCash.close_reason}</p></div>}</SalonCard></div>
 </>}
 {mode&&<SalonCard title={labels[mode]}><form key={formKey} className="stock-form" onSubmit={submit}>
 {mode==="CURRENCY_SET"?<label>Temel para birimi<select name="currency">{["TRY","EUR","USD","GBP","JPY","KWD"].map(c=><option key={c}>{c}</option>)}</select></label>:mode==="CASH_OPEN"?<label>Açılış nakdi<input name="opening" required inputMode="decimal"/></label>:mode==="CASH_CLOSE_SUBMIT"?<><p>Beklenen: {money(cash?.current_expected_minor)}</p><label>Sayılan nakit<input name="counted" required inputMode="decimal"/></label></>:mode==="SERVICE_CHARGE"?<label>Tamamlanmış randevu<select name="appointment_id" required><option value="">Seçin</option>{data.appointments.map(a=><option key={a.id} value={a.id}>{a.service_name} Â· {a.quoted_total} {a.currency}</option>)}</select></label>:mode==="REVERSAL"?<p>Orijinal kayıt korunur. Bu işlem gerçek para iadesi değildir.</p>:<>
 {["MANUAL_CHARGE","RETAIL_SALE","PAYMENT","DEPOSIT","ALLOCATE","CLIENT_CREDIT","CLIENT_DEBIT"].includes(mode)&&clientField}
 {mode==="ALLOCATE"||mode==="REFUND"?<label>{mode==="ALLOCATE"?"Kullanılabilir kredi":"Orijinal ödeme"}<select name="payment_id" required><option value="">Seçin</option>{(mode==="ALLOCATE"?credits:data.documents.filter(d=>["PAYMENT","DEPOSIT"].includes(d.type)&&!d.reversed)).map(d=><option key={d.id} value={d.id}>{d.description} Â· {money(mode==="ALLOCATE"?d.available_credit_minor:(BigInt(d.amount_minor)-BigInt(d.refunded_minor)).toString())}</option>)}</select></label>:null}
 {mode!=="RETAIL_SALE"&&mode!=="ALLOCATE"&&<label>Tutar<input name="amount" required inputMode="decimal"/></label>}
 {["PAYMENT","DEPOSIT","EXPENSE"].includes(mode)&&methodField}
 {mode==="PAYMENT"||mode==="ALLOCATE"?allocationFields:null}
 {mode==="PAYMENT"&&<label className="finance-check stock-span"><input type="checkbox" name="confirm_credit"/>Dağıtılmayan tutar müşteri kredisi olsun.</label>}
 {["PAYMENT","DEPOSIT"].includes(mode)&&<label>Randevu (isteğe bağlı)<select name="appointment_id"><option value="">Bağlantı yok</option>{data.appointments.map(a=><option key={a.id} value={a.id}>{a.service_name}</option>)}</select></label>}
 {mode==="RETAIL_SALE"&&<><label>Stok ürünü<select name="stock_item_id" required value={retailItem} onChange={e=>setRetailItem(e.target.value)}>{data.stock_items.map(i=><option key={i.id} value={i.id}>{i.display_name} Â· {i.inventory_unit}</option>)}</select></label><label>Ürün lotu<select key={retailItem} name="lot_id" required={data.stock_items.find(i=>i.id===retailItem)?.lot_required}><option value="">Lot seçilmedi</option>{data.stock_lots.filter(l=>l.stock_item_id===retailItem).map(l=><option key={l.id} value={l.id}>{l.lot_number}{l.batch_number?" · "+l.batch_number:""}</option>)}</select></label><label>Miktar<input name="quantity" inputMode="decimal" required/></label><label>Birim fiyat<input name="unit_price" inputMode="decimal" required/></label></>}
 {["MANUAL_CHARGE","RETAIL_SALE"].includes(mode)&&<><label>Vergi oranı (baz puan)<input name="tax_rate_bps" type="number" min="0" max="10000" step="1" defaultValue="0"/></label><label className="finance-check"><input name="tax_inclusive" type="checkbox" defaultChecked/>Tutar vergi dahil</label></>}
 {mode==="EXPENSE"&&<><label>Kategori<select name="category">{["RENT","UTILITIES","SUPPLIES","MAINTENANCE","MARKETING","OTHER"].map(c=><option key={c} value={c}>{labels[c]}</option>)}</select></label><label>Stok giriş hareketi (isteğe bağlı)<input name="stock_receipt_id"/></label></>}
 {mode==="ADJUSTMENT"&&<label>Kasa etkisi<select name="direction"><option value="IN">Nakit giriş</option><option value="OUT">Nakit çıkış</option></select></label>}
 {["MANUAL_CHARGE","RETAIL_SALE","EXPENSE","CLIENT_CREDIT","CLIENT_DEBIT","ADJUSTMENT"].includes(mode)&&<label>Açıklama<input name="description" required maxLength={500}/></label>}
 {["PAYMENT","DEPOSIT","EXPENSE"].includes(mode)&&<label>Harici referans (isteğe bağlı)<input name="external_reference" maxLength={160}/></label>}
 {mode!=="ALLOCATE"&&<label>İşlem tarihi<input name="occurred_at" type="datetime-local" step="0.001" defaultValue={currentLocal()} required/></label>}
 </>}
 <label className="stock-span">Gerekçe<textarea name="reason" required maxLength={2000}/></label><div className="stock-toolbar stock-span"><button className="button" disabled={busy}>Kaydet</button><button className="button button-secondary" type="button" onClick={()=>setMode(null)}>Vazgeç</button></div></form></SalonCard>}
 {selected&&<SalonCard title="İşlem detayı"><p>{labels[selected.type]} Â· {selected.description}</p><p>Brüt: {money(selected.amount_minor)} Â· Net: {money(selected.net_amount_minor)} Â· Vergi: {money(selected.tax_amount_minor)}</p><p>{selected.outstanding_minor!==null&&<>Kalan: {money(selected.outstanding_minor)} Â· </>}İade: {money(selected.refunded_minor)}</p><p>Kaydeden: {selected.recorded_by} Â· {selected.reason}</p>{selected.service_name_snapshot&&<p>Tarihsel hizmet: {selected.service_name_snapshot}</p>}{selected.appointment_id&&<Link href={`/workspace/appointments/${selected.appointment_id}`}>Randevuyu aç</Link>}<p>{selected.reversed?"Ters kayıtla iptal edildi":"Orijinal kayıt korunuyor"}</p>{can("finance.adjust")&&!selected.reversed&&!['REVERSAL','REFUND'].includes(selected.type)&&<button className="button button-secondary" onClick={()=>open("REVERSAL")}>Kaydı iptal et</button>}</SalonCard>}
 <SalonCard title="Finans geçmişi"><div className="stock-table"><table><thead><tr><th>Tarih / açıklama</th><th>Tür</th><th>Tutar</th><th>Durum</th></tr></thead><tbody>{data.documents.map(d=><tr key={d.id}><td data-label="Tarih / açıklama"><button className="text-link" onClick={()=>setDocumentId(d.id)}>{d.description}</button><small>{new Date(d.occurred_at).toLocaleString("tr-TR")}</small></td><td data-label="Tür">{labels[d.type]}{d.method&&<small>{labels[d.method]}</small>}</td><td data-label="Tutar">{money(d.amount_minor)}</td><td data-label="Durum">{d.reversed?"İptal edildi":d.outstanding_minor!==null?"Kalan: "+money(d.outstanding_minor):d.available_credit_minor!==null?"Kredi: "+money(d.available_credit_minor):"Kayıtlı"}</td></tr>)}</tbody></table></div>{!data.documents.length&&<p>Bu kapsamda finans kaydı yok.</p>}<div className="stock-toolbar"><button className="button button-secondary" disabled={offset===0} onClick={()=>{filters.current.offset=Math.max(0,offset-100);setOffset(Number(filters.current.offset));void load();}}>Önceki</button><span>{offset+1}–{offset+data.documents.length}</span><button className="button button-secondary" disabled={data.documents.length<100||offset>=9900} onClick={()=>{filters.current.offset=offset+100;setOffset(offset+100);void load();}}>Sonraki</button></div></SalonCard>
 <SalonCard title="Müşteri hesapları"><p>Pozitif bakiye müşterinin borcunu, negatif bakiye müşteri alacağını gösterir. Kredi, ücrete ayrıca uygulanmalıdır.</p>{data.client_balances.map(c=><div key={c.client_id} className="stock-action"><strong>{c.display_name}</strong><p>Bakiye: {money(c.balance_minor)} Â· Ücret kalanları: {money(c.outstanding_minor)}</p><p>Kullanılabilir kredi: {money(c.available_credit_minor)}</p></div>)}</SalonCard>
 </>}</main></SalonFrame>;
}
