"use client";
import {useEffect,useState} from "react";
import Link from "next/link";
import {financeSnapshot,formatMoney,type FinanceSnapshot} from "@/lib/finance/model";
import {tenantContextSchema,workspaceReference,type ActiveTenantContext} from "@/lib/tenant/context";
export function FinanceContextPanel({clientId,appointmentId,context}:{clientId:string;appointmentId?:string;context:ActiveTenantContext}){
 const [data,setData]=useState<FinanceSnapshot|null>(null),[error,setError]=useState("");
 useEffect(()=>{let active=true;const abort=new AbortController();const load=async()=>{setData(null);if(document.hidden)return;try{const q=new URLSearchParams({client_id:clientId,...(appointmentId?{appointment_id:appointmentId}:{})}),r=await fetch("/api/finance?"+q,{cache:"no-store",signal:abort.signal}),b=await r.json();if(!active)return;if(!r.ok){setError("Finans özeti erişilemiyor.");return;}const c=tenantContextSchema.parse(b.context),d=financeSnapshot.parse(b.data);if(workspaceReference(c)!==workspaceReference(context))return;setData(d);setError("");}catch{if(active)setError("Finans özeti yüklenemedi.");}};void load();const conceal=()=>{setData(null);if(!document.hidden)void load();};document.addEventListener("visibilitychange",conceal);window.addEventListener("focus",conceal);return()=>{active=false;abort.abort();document.removeEventListener("visibilitychange",conceal);window.removeEventListener("focus",conceal);};},[clientId,appointmentId,context]);
 const show=(s:string)=>formatMoney(s,data?.settings?.currency??"TRY",data?.settings?.exponent??2);
 return <section className="salon-card" aria-label="Finans özeti"><h2>{appointmentId?"Randevu ödemeleri":"Müşteri hesabı"}</h2>{error&&<p role="status">{error}</p>}{data?.settings?<><p>Hesap bakiyesi: {show(data.client_balances[0]?.balance_minor??"0")}</p><p>Kullanılabilir kredi: {show(data.client_balances[0]?.available_credit_minor??"0")}</p>{data.documents.slice(0,5).map(d=><p key={d.id}>{d.description} · {show(d.amount_minor)}{d.outstanding_minor!==null&&<> · kalan {show(d.outstanding_minor)}</>}{BigInt(d.refunded_minor)>0n&&<> · iade {show(d.refunded_minor)}</>}</p>)}{!data.documents.length&&<p>Finans kaydı yok.</p>}</>:<p>Finans özeti hazır olduğunda burada gösterilir.</p>}<Link className="button button-secondary" href={`/workspace/finance?client_id=${clientId}${appointmentId?`&appointment_id=${appointmentId}`:""}`}>Finans işlemlerini aç</Link></section>;
}
