import { hairTr as t, hairObservationTr as o } from "@/lib/i18n/hair-tr";
import type { ReactNode } from "react";
import { displayValue, formatHairDate as date, orderedRegions, regionName, type Assessment, type Evidence } from "@/lib/hair-passport/display";
import type { HairSnapshot } from "@/lib/hair-passport/contracts";
import { hairEditTr as e } from "@/lib/i18n/hair-tr";
export function EvidenceBadge({ evidence }: { evidence: Evidence }) {
 return <div className="hp-evidence"><span className="hp-badge">{t.sources[evidence.source]}</span><span>{evidence.confidence.state === "KNOWN" ? `${t.confidence}: ${new Intl.NumberFormat("tr-TR", { style: "percent", maximumFractionDigits: 1 }).format(evidence.confidence.value)}` : t.noConfidence}</span>{evidence.verified_by && <span>{t.verified}</span>}{evidence.observed_at.state === "KNOWN" && <span>{t.observed}: {date(evidence.observed_at.value)}</span>}{evidence.relevant_until && <span>{t.relevant}: {date(evidence.relevant_until)}</span>}{evidence.context && <p>{evidence.context}</p>}</div>;
}
export function TechnicalStateCard({ assessment }: { assessment: Assessment }) {
 const values = assessment.state === "ASSESSED" ? assessment.observation : assessment.state === "UNVERIFIED" ? assessment.values : null;
 return <><p className="hp-state">{t.states[assessment.state]}</p>{values ? <dl className="hp-values">{Object.entries(t.fields).map(([key, label]) => {
 const value = values[key as keyof typeof t.fields];
 return <div key={key}><dt>{label}</dt><dd>{typeof value === "object" && value !== null ? displayValue(key, value) : value ?? t.states.UNKNOWN}</dd></div>;
 })}</dl> : <p className="hp-muted">{t.partial}</p>}{assessment.state === "ASSESSED" && <EvidenceBadge evidence={assessment.observation.evidence} />}</>;
}
function Pager({ page, label, change }: { page: HairSnapshot["history"] | HairSnapshot["physical_tests"] | HairSnapshot["observations"]; label: string; change: (offset: number) => void }) {
 return <nav className="hp-pager" aria-label={label}><button className="button button-secondary" disabled={page.offset === 0} onClick={() => change(Math.max(0, page.offset - page.page_size))}>{t.previous}</button><span>{t.page} {Math.floor(page.offset / page.page_size) + 1}</span><button className="button button-secondary" disabled={!page.has_more || page.next_offset === null || page.next_offset > 10000} onClick={() => change(page.next_offset!)}>{t.next}</button></nav>;
}
export function HairPassportOverview({ snapshot: s, change, canEdit = false, onEditCore, onEditRegion, onAddRegion, canAddObservation = false, onAddObservation, observationForm }: { snapshot: HairSnapshot; change: (kind: "observations_offset" | "tests_offset" | "history_offset", offset: number) => void; canEdit?: boolean; onEditCore?: () => void; onEditRegion?: (id: string) => void; onAddRegion?: () => void; canAddObservation?: boolean; onAddObservation?: () => void; observationForm?: ReactNode }) {
 const observations = s.observations.items;
 return <>
 <div className="hp-summary"><span className="hp-badge">{t.states[s.passport.status]}</span><span>{t.updated}: {date(s.passport.updated_at)}</span><span>{t.states[s.core.state]}</span></div>
 <nav className="hp-jumps" aria-label={t.title}>{(["core", "regions", "observations", "tests", "history"] as const).map(key => <a key={key} href={`#hp-${key}`}>{t[key]}</a>)}</nav>
 <section id="hp-core" className="hp-section"><div className="hp-section-heading"><h2>{t.core}</h2>{canEdit && <button className="button button-secondary" onClick={onEditCore}>{e.editCore}</button>}</div><div className="hp-card"><TechnicalStateCard assessment={s.core} /></div></section>
 <section id="hp-regions" className="hp-section"><div className="hp-section-heading"><h2>{t.regions}</h2>{canEdit && <button className="button button-secondary" onClick={onAddRegion}>{e.addRegion}</button>}</div>{!s.regions.length && <p className="hp-empty">{t.noRegions}</p>}<div className="hp-regions">{orderedRegions(s).map(r => <article className="hp-card" key={r.id}><div className="hp-section-heading"><h3>{regionName(s, r.id)}</h3>{canEdit && r.status === "ACTIVE" && <button className="hp-text-button" onClick={() => onEditRegion?.(r.id)} aria-label={`${regionName(s, r.id)} · ${e.editRegion}`}>{e.editRegion}</button>}</div>{r.status === "ARCHIVED" && <p>{t.states.ARCHIVED}</p>}<TechnicalStateCard assessment={r.assessment} /></article>)}</div></section>
 <section id="hp-observations" className="hp-section"><div className="hp-section-heading"><h2>{t.observations}</h2>{canAddObservation && <button className="button button-secondary" onClick={onAddObservation}>{o.add}</button>}</div>{observationForm}<p className="hp-muted">{t.observationHint}</p>{!observations.length ? <p className="hp-empty">{t.noObservations}</p> : <ol className="hp-records">{observations.map(item => <li className="hp-card" key={item.id}><h3>{regionName(s, item.region_id)}</h3><p>{t.recorded}: <time dateTime={item.recorded_at}>{date(item.recorded_at)}</time></p>{item.supersedes_id && <p>{t.correction}</p>}<TechnicalStateCard assessment={{ state: "ASSESSED", observation: item }} /></li>)}</ol>}<Pager page={s.observations} label={t.observations} change={offset => change("observations_offset", offset)} /></section>
 <section id="hp-tests" className="hp-section"><h2>{t.tests}</h2>{!s.physical_tests.items.length ? <p className="hp-empty">{t.noTests}</p> : <ol className="hp-records">{s.physical_tests.items.map(test => <li className="hp-card" key={test.id}><div className="hp-record-heading"><h3>{t.testTypes[test.type]}</h3><span>{regionName(s, test.region_id)}</span></div><p className="hp-result">{displayValue("result", test.result)}</p><p><time dateTime={test.performed_at}>{date(test.performed_at)}</time> · {t.performer}</p>{test.notes && <p>{test.notes}</p>}{test.supersedes_id && <p>{t.correction}</p>}<EvidenceBadge evidence={test.evidence} /></li>)}</ol>}<Pager page={s.physical_tests} label={t.tests} change={offset => change("tests_offset", offset)} /></section>
 <section id="hp-history" className="hp-section"><h2>{t.history}</h2>{!s.history.items.length ? <p className="hp-empty">{t.noHistory}</p> : <ol className="hp-records">{s.history.items.map(h => <li className="hp-card" key={h.id}><div className="hp-record-heading"><h3>{t.categories[h.category]}</h3><span>{h.performed_on.state === "UNKNOWN" ? t.unknownDate : `${h.performed_on.state === "APPROXIMATE" ? t.approximate + " · " : ""}${date(h.performed_on.value, true)}`}</span></div><p className="hp-muted">{h.region_ids.length ? h.region_ids.map(id => regionName(s, id)).join(" · ") : t.whole}</p><p>{h.description}</p><p>{t.product}: {displayValue("product", h.product)}</p>{h.attributed_salon && <p>{t.salon}: {h.attributed_salon}</p>}{h.attributed_professional && <p>{t.professional}: {h.attributed_professional}</p>}{h.supersedes_id && <p>{t.correction}</p>}<EvidenceBadge evidence={h.evidence} /></li>)}</ol>}<Pager page={s.history} label={t.history} change={offset => change("history_offset", offset)} /></section>
 </>;
}
