import { act, cleanup, fireEvent, render, screen } from "@testing-library/react";
import { afterEach, expect, it, vi } from "vitest";
vi.mock("@/lib/hair-passport/load", () => ({ loadPassport: vi.fn(), PassportLoadError: class extends Error { constructor(public code: string) { super(code); } } }));
vi.mock("@/lib/hair-passport/mutate", () => ({ sendHairMutation: vi.fn(), PassportMutationError: class extends Error { constructor(public code: string) { super(code); } } }));
vi.mock("@/lib/hair-passport/observation-mutate", () => ({ sendObservation: vi.fn() }));
vi.mock("@/lib/hair-passport/physical-test-mutate", () => ({ sendPhysicalTest: vi.fn() }));
import { loadPassport, PassportLoadError } from "@/lib/hair-passport/load";
import { sendHairMutation, PassportMutationError } from "@/lib/hair-passport/mutate";
import { sendObservation } from "@/lib/hair-passport/observation-mutate";
import { sendPhysicalTest } from "@/lib/hair-passport/physical-test-mutate";
import { HairPassportWorkspace } from "./hair-passport-workspace";
import { hairTr as t, hairEditTr as e, hairObservationTr as o, hairPhysicalTestTr as p } from "@/lib/i18n/hair-tr";
import { readFixtures } from "@/test/hair-passport-fixtures";
const loaded = { client: { full_name: "Sentetik müşteri", status: "ARCHIVED" }, snapshot: null, permissions: ["hair_passport.create", "hair_passport.update"], workspaceReference: "selection" } as Awaited<ReturnType<typeof loadPassport>>;
afterEach(() => { cleanup(); vi.resetAllMocks(); });
it("conceals identity on initial load, then renders archived no-passport state", async () => {
 let resolve!: (value: typeof loaded) => void;
 vi.mocked(loadPassport).mockImplementation(() => new Promise(r => { resolve = r; }));
 render(<HairPassportWorkspace clientId="test" />);
 expect(screen.queryByText(loaded.client.full_name)).toBeNull(); expect(screen.getByRole("status")).toHaveTextContent(t.loading);
 await act(async () => { await Promise.resolve(); resolve(loaded); });
 expect(screen.getByText(t.archived)).toBeVisible(); expect(screen.getByText(t.emptyTitle)).toBeVisible();
 expect(screen.queryByRole("button", { name: e.create })).toBeNull();
});
it("offers a minimal create action only to an active authorized user and reloads server state", async () => {
 const active = { ...loaded, client: { ...loaded.client, status: "ACTIVE" as const } };
 vi.mocked(loadPassport).mockResolvedValueOnce(active).mockResolvedValue({ ...active, snapshot: readFixtures.populated.data as typeof active.snapshot });
 vi.mocked(sendHairMutation).mockResolvedValue({} as Awaited<ReturnType<typeof sendHairMutation>>);
 render(<HairPassportWorkspace clientId="test" />);
 fireEvent.click(await screen.findByRole("button", { name: e.create }));
 expect(screen.getByRole("heading", { name: e.createTitle })).toBeVisible();
 fireEvent.click(screen.getByRole("button", { name: e.save }));
 expect(await screen.findByText(e.saved)).toBeVisible();
 expect(vi.mocked(sendHairMutation).mock.calls[0]![0]).toMatchObject({ operation: "create_passport", payload: { request_id: expect.any(String) } });
 expect(screen.getAllByRole("heading", { name: "Dip" }).length).toBeGreaterThan(0);
});
it("keeps active read-only users free of mutation controls", async () => {
 vi.mocked(loadPassport).mockResolvedValue({ ...loaded, client: { ...loaded.client, status: "ACTIVE" }, permissions: ["hair_passport.read"] } as typeof loaded);
 render(<HairPassportWorkspace clientId="test" />);
 await screen.findByText(t.emptyTitle);
 expect(screen.queryByRole("button", { name: e.create })).toBeNull();
});
it("shows observation entry only with active mutation permission", async () => {
 const clientId = readFixtures.populated.data.passport.client_id;
 const base = { ...loaded, client: { ...loaded.client, status: "ACTIVE" as const }, snapshot: readFixtures.populated.data };
 vi.mocked(loadPassport).mockResolvedValueOnce({ ...base, permissions: ["hair_passport.read"] } as typeof loaded);
 render(<HairPassportWorkspace clientId={clientId} />);
 await screen.findByRole("heading", { name: t.observations });
 expect(screen.queryByRole("button", { name: o.add })).toBeNull();
 cleanup();
 vi.mocked(loadPassport).mockResolvedValue({ ...base, permissions: ["hair_passport.read", "hair_passport.add_observation"] } as typeof loaded);
 render(<HairPassportWorkspace clientId={clientId} />);
 expect(await screen.findByRole("button", { name: o.add })).toBeVisible();
});
it("offers physical test entry only to an active user with add_test permission", async () => {
 const base = { ...loaded, client: { ...loaded.client, status: "ACTIVE" as const }, snapshot: readFixtures.populated.data };
 vi.mocked(loadPassport).mockResolvedValueOnce({ ...base, permissions: ["hair_passport.read"] } as typeof loaded);
 render(<HairPassportWorkspace clientId={base.snapshot.passport.client_id} />);
 await screen.findByRole("heading", { name: t.tests });
 expect(screen.queryByRole("button", { name: p.add })).toBeNull();
 cleanup();
 vi.mocked(loadPassport).mockResolvedValueOnce({ ...base, client: loaded.client, permissions: ["hair_passport.read", "hair_passport.add_test"] } as typeof loaded);
 render(<HairPassportWorkspace clientId={base.snapshot.passport.client_id} />);
 await screen.findByRole("heading", { name: t.tests });
 expect(screen.queryByRole("button", { name: p.add })).toBeNull();
 cleanup();
 vi.mocked(loadPassport).mockResolvedValue({ ...base, permissions: ["hair_passport.read", "hair_passport.add_test"] } as typeof loaded);
 render(<HairPassportWorkspace clientId={base.snapshot.passport.client_id} />);
 expect(await screen.findByRole("button", { name: p.add })).toBeVisible();
});
it("validates, saves a global physical test and shows only refreshed server records", async () => {
 const base = { ...loaded, client: { ...loaded.client, status: "ACTIVE" as const }, snapshot: readFixtures.populated.data, permissions: ["hair_passport.read", "hair_passport.add_test"] } as typeof loaded;
 const next = structuredClone(base);
 next.snapshot!.physical_tests.items.unshift({ ...next.snapshot!.physical_tests.items[0]!, id: "b2000000-0000-4000-8000-000000000099", type: "POROSITY", result: { state: "KNOWN", value: "HIGH" } });
 vi.mocked(loadPassport).mockResolvedValueOnce(base).mockResolvedValue(next);
 vi.mocked(sendPhysicalTest).mockResolvedValue({} as Awaited<ReturnType<typeof sendPhysicalTest>>);
 render(<HairPassportWorkspace clientId={base.snapshot!.passport.client_id} />);
 fireEvent.click(await screen.findByRole("button", { name: p.add }));
 expect(screen.getByRole("heading", { name: p.title })).toHaveFocus();
 fireEvent.click(screen.getByRole("button", { name: e.save }));
 expect(await screen.findByRole("alert")).toHaveTextContent(p.validation.result);
 fireEvent.change(screen.getByLabelText(p.porosityResult), { target: { value: "HIGH" } });
 fireEvent.click(screen.getByRole("button", { name: e.save }));
 expect(await screen.findByText(p.saved)).toBeVisible();
 expect(vi.mocked(sendPhysicalTest).mock.calls[0]![0]).toMatchObject({ operation: "add_physical_test", payload: { type: "POROSITY", result: { state: "KNOWN", value: "HIGH" } } });
 expect(screen.getAllByRole("listitem").length).toBeGreaterThan(base.snapshot!.physical_tests.items.length);
});
it("keeps a request ID for uncertain retry and clears the form after permission revocation", async () => {
 const base = { ...loaded, client: { ...loaded.client, status: "ACTIVE" as const }, snapshot: readFixtures.populated.data, permissions: ["hair_passport.read", "hair_passport.add_test"] } as typeof loaded;
 vi.mocked(loadPassport).mockResolvedValueOnce(base).mockResolvedValue({ ...base, permissions: ["hair_passport.read"] } as typeof loaded);
 vi.mocked(sendPhysicalTest).mockRejectedValueOnce(new PassportMutationError("NETWORK_ERROR")).mockRejectedValueOnce(new PassportMutationError("FORBIDDEN"));
 render(<HairPassportWorkspace clientId={base.snapshot!.passport.client_id} />);
 fireEvent.click(await screen.findByRole("button", { name: p.add }));
 fireEvent.change(screen.getByLabelText(p.porosityResult), { target: { value: "LOW" } });
 fireEvent.click(screen.getByRole("button", { name: e.save }));
 expect(await screen.findByText(p.errors.NETWORK_ERROR)).toBeVisible();
 fireEvent.click(screen.getByRole("button", { name: e.save }));
 expect(vi.mocked(sendPhysicalTest).mock.calls[0]![0].payload.request_id).toBe(vi.mocked(sendPhysicalTest).mock.calls[1]![0].payload.request_id);
 await screen.findByRole("heading", { name: t.tests });
 expect(screen.queryByRole("button", { name: p.add })).toBeNull();
 expect(screen.queryByText(p.saved)).toBeNull();
});
it("requires attestation, sends one professional observation and reloads confirmed history", async () => {
 const clientId = readFixtures.populated.data.passport.client_id;
 const base = { ...loaded, client: { ...loaded.client, status: "ACTIVE" as const }, snapshot: readFixtures.populated.data, permissions: ["hair_passport.read", "hair_passport.add_observation"] } as typeof loaded;
 const next = structuredClone(base);
 next.snapshot!.observations.items.unshift({ ...next.snapshot!.observations.items[0]!, id: "b2000000-0000-4000-8000-000000000099" });
 vi.mocked(loadPassport).mockResolvedValueOnce(base).mockResolvedValue(next);
 vi.mocked(sendObservation).mockResolvedValue({} as Awaited<ReturnType<typeof sendObservation>>);
 render(<HairPassportWorkspace clientId={clientId} />);
 fireEvent.click(await screen.findByRole("button", { name: o.add }));
 fireEvent.change(screen.getByLabelText(o.value), { target: { value: "5" } });
 fireEvent.click(screen.getByRole("button", { name: e.save }));
 expect(await screen.findByRole("alert")).toHaveTextContent(o.validation.verified);
 fireEvent.click(screen.getByLabelText(o.verify));
 fireEvent.click(screen.getByRole("button", { name: e.save }));
 expect(await screen.findByText(o.saved)).toBeVisible();
 expect(vi.mocked(sendObservation).mock.calls[0]![0]).toMatchObject({ operation: "add_observation", payload: { technical: { natural_level: { state: "KNOWN", value: 5 } }, evidence: { source: "PROFESSIONAL_VERIFIED", attestation: "PERSONALLY_ASSESSED" } } });
 expect(screen.getAllByRole("listitem").length).toBeGreaterThan(1);
});
it("reuses request ID after uncertain network failure and rechecks revoked access", async () => {
 const clientId = readFixtures.populated.data.passport.client_id;
 const base = { ...loaded, client: { ...loaded.client, status: "ACTIVE" as const }, snapshot: readFixtures.populated.data, permissions: ["hair_passport.read", "hair_passport.add_observation"] } as typeof loaded;
 vi.mocked(loadPassport).mockResolvedValue(base);
 vi.mocked(sendObservation).mockRejectedValueOnce(new PassportMutationError("NETWORK_ERROR")).mockRejectedValueOnce(new PassportMutationError("FORBIDDEN"));
 render(<HairPassportWorkspace clientId={clientId} />);
 fireEvent.click(await screen.findByRole("button", { name: o.add }));
 fireEvent.change(screen.getByLabelText(o.value), { target: { value: "5" } });
 fireEvent.click(screen.getByLabelText(o.verify));
 fireEvent.click(screen.getByRole("button", { name: e.save }));
 expect(await screen.findByText(o.errors.NETWORK_ERROR)).toBeVisible();
 fireEvent.click(screen.getByRole("button", { name: e.save }));
 expect(vi.mocked(sendObservation).mock.calls[0]![0].payload.request_id).toBe(vi.mocked(sendObservation).mock.calls[1]![0].payload.request_id);
 expect(await screen.findByRole("button", { name: o.add })).toBeVisible();
 expect(screen.queryByText(o.saved)).toBeNull();
});
it("shows a version conflict and safe reload action without a saved notice", async () => {
 const active = { ...loaded, client: { ...loaded.client, status: "ACTIVE" as const } };
 vi.mocked(loadPassport).mockResolvedValue(active);
 vi.mocked(sendHairMutation).mockRejectedValue(new PassportMutationError("CONFLICT"));
 render(<HairPassportWorkspace clientId="test" />);
 fireEvent.click(await screen.findByRole("button", { name: e.create }));
 fireEvent.click(screen.getByRole("button", { name: e.save }));
 expect(await screen.findByText(e.errors.CONFLICT)).toBeVisible();
 expect(screen.queryByText(e.saved)).toBeNull();
 fireEvent.click(screen.getByRole("button", { name: e.reload }));
 expect(await screen.findByRole("button", { name: e.create })).toBeVisible();
});
it("rechecks access after mutation permission loss", async () => {
 const active = { ...loaded, client: { ...loaded.client, status: "ACTIVE" as const } };
 vi.mocked(loadPassport).mockResolvedValueOnce(active).mockResolvedValue({ ...active, permissions: ["hair_passport.read"] });
 vi.mocked(sendHairMutation).mockRejectedValue(new PassportMutationError("FORBIDDEN"));
 render(<HairPassportWorkspace clientId="test" />);
 fireEvent.click(await screen.findByRole("button", { name: e.create }));
 fireEvent.click(screen.getByRole("button", { name: e.save }));
 await screen.findByText(t.emptyTitle);
 expect(screen.queryByRole("button", { name: e.create })).toBeNull();
 expect(screen.queryByText(e.saved)).toBeNull();
});
it.each(["FORBIDDEN", "CLIENT_NOT_FOUND", "NETWORK_ERROR"])("conceals data on %s and allows retry", async code => {
 vi.mocked(loadPassport).mockRejectedValueOnce(new PassportLoadError(code)).mockResolvedValue(loaded);
 render(<HairPassportWorkspace clientId="test" />);
 expect(await screen.findByRole("alert")).toHaveTextContent(t.errors[code as keyof typeof t.errors]);
 expect(screen.queryByText(loaded.client.full_name)).toBeNull();
 fireEvent.click(screen.getByText(t.retry)); expect(await screen.findByText(loaded.client.full_name)).toBeVisible();
});
it("conceals prior identity during focus revalidation and ignores superseded responses", async () => {
 let resolve!: (value: typeof loaded) => void;
 vi.mocked(loadPassport).mockResolvedValueOnce(loaded).mockImplementation(() => new Promise(r => { resolve = r; }));
 render(<HairPassportWorkspace clientId="test" />); await screen.findByText(loaded.client.full_name);
 fireEvent.focus(window); expect(screen.queryByText(loaded.client.full_name)).toBeNull();
 fireEvent(window, new Event("offline"));
 await act(async () => resolve(loaded));
 expect(screen.queryByText(loaded.client.full_name)).toBeNull(); expect(screen.getByRole("alert")).toBeVisible();
});
