"use client";
import { useCallback,useEffect,useRef,useState } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { SalonFrame,SalonHeading,SalonCard } from "./salon-frame";
import { tenantContextSchema,workspaceReference,type ActiveTenantContext } from "@/lib/tenant/context";
import { liveSession,liveCommand,terminal,permissionFor,type LiveSession } from "@/lib/live/model";
import { timerElapsed } from "@/lib/live/engine";
import { storeDraft,readDrafts,removeDraft,reconcileDraft,type Draft } from "@/lib/live/offline";
const statusLabels:Record<string,string>={PREPARING:"Hazırlanıyor",READY:"Başlamaya hazır",IN_PROGRESS:"Uygulama sürüyor",PAUSED:"Duraklatıldı",CHECKPOINT_REQUIRED:"Kontrol gerekli",COMPLETION_REVIEW:"Sonuç incelemesi",COMPLETED:"Tamamlandı",CANCELLED:"İptal edildi",ABORTED:"Güvenlik nedeniyle sonlandırıldı"};
const errors:Record<string,string>={SESSION_START_BLOCKED_STALE_INPUT:"Saç, reçete veya katalog değişti. Güncel renk planıyla yeni reçete oluşturun.",LIVE_SESSION_CONFLICT:"Aynı kayıtta başka değişiklik var. Taslağı ve güncel kaydı karşılaştırıp yeniden karar verin.",LIVE_CONTROLLER_CONFLICT:"Kontrol başka cihazda. Kontrol devri gereklidir.",LIVE_CHECKPOINT_REQUIRED:"Zorunlu kontrol tamamlanmadan ilerlenemez.",LIVE_COMPLETION_INCOMPLETE:"Adımlar, kontroller, sayaçlar, kullanım ve bölgesel sonucu tamamlayın.",FORBIDDEN:"Bu işlem için yetkiniz yok."};
export function LiveSessionWorkspace({clientId,recipeId,sessionId}:{clientId:string;recipeId?:string;sessionId?:string}){
 const router=useRouter();
 const [ctx,setCtx]=useState<ActiveTenantContext|null>(null),[session,setSession]=useState<LiveSession|null>(null),[sessions,setSessions]=useState<LiveSession[]>([]),[online,setOnline]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(""),[review,setReview]=useState(""),[accepted,setAccepted]=useState(false),[note,setNote]=useState(""),[drafts,setDrafts]=useState<Draft[]>([]),[now,setNow]=useState(0);
 const [device,setDevice]=useState(""),[clock,setClock]=useState<number|null>(null);const reference=useRef(""),generation=useRef(0),pending=useRef<{key:string;mutation_id:string}|null>(null);
 const scope=ctx&&session?`${ctx.membership_id}:${ctx.location_id}:${device}:${session.id}`:"";
 const load=useCallback(async()=>{const g=++generation.current;try{const r=await fetch("/api/session",{cache:"no-store"});const b=await r.json();if(!r.ok){setSession(null);setCtx(null);if(r.status===401)window.location.replace("/sign-in");throw new Error(b.code);}const context=tenantContextSchema.parse(b.context),ref=workspaceReference(context);if(reference.current&&reference.current!==ref){setSession(null);setCtx(null);window.location.replace("/workspaces");return;}reference.current=ref;const result=await fetch(`/api/live-sessions${sessionId?`/${sessionId}`:""}?client_id=${clientId}`,{cache:"no-store"});const body=await result.json();if(!result.ok){if([401,403,404].includes(result.status)){setSession(null);setCtx(null);}throw new Error(body.code);}if(g!==generation.current||document.hidden)return;const serverMs=Date.parse(result.headers.get("X-Server-Time")??"");if(Number.isFinite(serverMs))setClock(serverMs);setCtx(context);if(sessionId)setSession(liveSession.parse(body.data));else setSessions(liveSession.array().parse(body.data));setError("");}catch(e){if(g===generation.current)setError(errors[e instanceof Error?e.message:""]??"Bağlantı kurulamadı. Yeniden yükleyin.");}},[clientId,sessionId]);
 useEffect(()=>{const generationRef=generation;const selectedDevice=sessionStorage.getItem("elifora-live-device")??crypto.randomUUID();sessionStorage.setItem("elifora-live-device",selectedDevice);queueMicrotask(()=>setDevice(selectedDevice));queueMicrotask(()=>void load());const refresh=()=>{setOnline(navigator.onLine);if(navigator.onLine)void load();};const offline=()=>{setOnline(false);++generation.current;};const visibility=()=>{if(document.hidden)++generation.current;else refresh();};window.addEventListener("online",refresh);window.addEventListener("offline",offline);window.addEventListener("focus",refresh);document.addEventListener("visibilitychange",visibility);return()=>{++generationRef.current;window.removeEventListener("online",refresh);window.removeEventListener("offline",offline);window.removeEventListener("focus",refresh);document.removeEventListener("visibilitychange",visibility);};},[load]);
 useEffect(()=>{if(clock===null)return;const anchor=performance.now();const tick=()=>setNow(clock+performance.now()-anchor);const timer=setInterval(tick,250);return()=>clearInterval(timer);},[clock]);
 useEffect(()=>{if(scope)void readDrafts(scope).then(setDrafts).catch(()=>setError("Yerel taslak deposu kullanılamıyor."));},[scope,session?.recordVersion]);
 async function post(body:unknown,id?:string){const r=await fetch(`/api/live-sessions${id?`/${id}?client_id=${clientId}`:""}`,{method:"POST",headers:{"Content-Type":"application/json","X-Workspace-Reference":reference.current},body:JSON.stringify(body),cache:"no-store"});const b=await r.json();if(!r.ok)throw new Error(b.code);const serverMs=Date.parse(r.headers.get("X-Server-Time")??"");if(Number.isFinite(serverMs))setClock(serverMs);return liveSession.parse(b.data);}
 async function act(patch:Record<string,unknown>){if(!session||!ctx||busy)return;const key=JSON.stringify(patch);if(pending.current?.key!==key)pending.current={key,mutation_id:crypto.randomUUID()};const c=liveCommand.safeParse({...patch,expected_version:session.recordVersion,control_epoch:session.controlEpoch,device_id:device,mutation_id:pending.current.mutation_id});if(!c.success){setError("Alanları ve miktarları kontrol edin.");return;}if(!ctx.permissions.includes(permissionFor(c.data.type))){setError("Bu işlem için yetkiniz yok.");return;}setBusy(true);setError("");try{if(!navigator.onLine){await storeDraft({key:c.data.mutation_id,scope,command:c.data,createdAt:new Date().toISOString()});pending.current=null;setDrafts(await readDrafts(scope));}else{const next=await post(c.data,session.id);if(!document.hidden){setSession(current=>!current||next.recordVersion>=current.recordVersion?next:current);pending.current=null;}}}catch(e){setError(errors[e instanceof Error?e.message:""]??"İşlem kaydedilemedi; aynı girdilerle yeniden deneyin.");}finally{setBusy(false);}}
 async function create(){if(!recipeId||!ctx||!accepted||!review.trim()||busy)return;const key=`CREATE:${recipeId}:${review}`;if(pending.current?.key!==key)pending.current={key,mutation_id:crypto.randomUUID()};setBusy(true);try{const s=await post({mutation_id:pending.current.mutation_id,device_id:device,client_id:clientId,recipe_id:recipeId,professional_review:true,review_note:review});router.push(`/workspace/live-sessions?client_id=${clientId}&session_id=${s.id}`);}catch(e){setError(errors[e instanceof Error?e.message:""]??"Seans hazırlanamadı.");setBusy(false);}}
 async function sync(d:Draft){if(!session||!navigator.onLine)return;const command=d.command;if(d.photo&&command.type==="PHOTO"&&session.photos.some(p=>p.id===command.photo_id)){setBusy(true);try{await uploadBytes(session.id,command.photo_id,d.photo);await removeDraft(d.key);setDrafts(await readDrafts(scope));}catch{setError("Fotoğraf henüz yüklenemedi; taslak korunuyor.");}finally{setBusy(false);}return;}if(reconcileDraft(d,session.recordVersion,session.controlEpoch)==="CONFLICT_REVIEW"){setError("Taslak sürümü güncel değil. Taslağı silmeden içeriğini inceleyin; güncel formdan yeniden kaydedin.");return;}setBusy(true);try{const next=await post(command,session.id);setSession(current=>!current||next.recordVersion>=current.recordVersion?next:current);if(d.photo&&command.type==="PHOTO")await uploadBytes(next.id,command.photo_id,d.photo);await removeDraft(d.key);setDrafts(await readDrafts(scope));}catch(e){setError(errors[e instanceof Error?e.message:""]??"Senkronizasyon tamamlanamadı.");}finally{setBusy(false);}}
 async function uploadBytes(id:string,photoId:string,file:Blob){const r=await fetch(`/api/live-sessions/${id}/photos/${photoId}?client_id=${clientId}`,{method:"POST",headers:{"Content-Type":file.type,"X-Workspace-Reference":reference.current},body:file});if(!r.ok)throw new Error("LIVE_PHOTO_UPLOAD_FAILED");}
 async function photo(file:File,kind:string){if(!session||!ctx||busy)return;setBusy(true);setError("");try{const command=liveCommand.parse({type:"PHOTO",photo_id:crypto.randomUUID(),kind,content_type:file.type,mutation_id:crypto.randomUUID(),device_id:device,expected_version:session.recordVersion,control_epoch:session.controlEpoch});if(command.type!=="PHOTO")throw new Error();const draft={key:command.mutation_id,scope,command,createdAt:new Date().toISOString(),photo:file};await storeDraft(draft);if(navigator.onLine){const next=await post(command,session.id);setSession(current=>!current||next.recordVersion>=current.recordVersion?next:current);await uploadBytes(next.id,command.photo_id,file);await removeDraft(draft.key);}setDrafts(await readDrafts(scope));}catch{setError("Fotoğraf yerel taslakta korunur. Yükleme tamamlanmadan seans kapatılamaz.");}finally{setBusy(false);}}
 const disabled=busy||!ctx,criticalDisabled=disabled||!online||!session||session.controllerDeviceId!==device||!ctx?.permissions.includes("live_session.control")||terminal(session.status);
 return <SalonFrame active="colorlab" workspace={ctx?.organization_name}><main id="main-content" className="salon-main live-workspace"><SalonHeading title="Canlı renk seansı" description="Onaylı reçete, uygulama sırası ve gerçek sonuç."/><Link href="/workspace/colorlab">ColorLab’a dön</Link>{error&&<p role="alert" className="salon-notice">{error}</p>}<button className="button button-secondary" disabled={busy||!online} onClick={()=>void load()}>Güncel kaydı yükle</button>{!online&&<p role="status" className="salon-notice">Çevrimdışı · sayaçlar devam eder. Not, kontrol ve kullanım yalnız yerel taslak olarak saklanır. Yetki tekrar doğrulanmadan son kayıt yapılamaz.</p>}
 {!ctx?<p>Çalışma alanı doğrulanıyor…</p>:!session?<><SalonCard title="Profesyonel reçete onayı">{recipeId?<><p>Reçete sürümü: {recipeId}. Kaynakları, tonu, miktarı ve müşteri değerlendirmesini ColorLab’da inceleyin.</p><label>Profesyonel inceleme notu<textarea value={review} onChange={e=>setReview(e.target.value)} maxLength={2000}/></label><label className="hp-check"><input type="checkbox" checked={accepted} onChange={e=>setAccepted(e.target.checked)}/>Reçeteyi ve resmi koşulları bu uygulama için değerlendirdim.</label><button className="button button-primary" disabled={disabled||!online||!accepted||!review.trim()} onClick={()=>void create()}>Onayla ve seans hazırla</button></>:<p>ColorLab’da kayıtlı reçeteyi açarak profesyonel inceleme yapın.</p>}</SalonCard><SalonCard title="Müşterinin seans geçmişi">{sessions.map(s=><p key={s.id}><Link href={`/workspace/live-sessions?client_id=${clientId}&session_id=${s.id}`}>{statusLabels[s.status]} · {new Date(s.createdAt).toLocaleString("tr-TR")}</Link></p>)}</SalonCard></>:<>
 <div className="salon-notice live-status"><strong>{statusLabels[session.status]} · Sürüm {session.recordVersion}</strong><p>Reçete: {session.recipes.find(r=>r.id===session.currentRecipeId)!.result.selected.displayName} · {session.recipes.find(r=>r.id===session.currentRecipeId)!.result.selected.developerName}</p><p>Güvenlik: {session.riskEvents.some(e=>!e.resolvedAt)?"⚠ Yeni bilgi / kontrol gerekli":`✓ Başlangıç değerlendirmesi ${session.riskSnapshot.gate}`} · {session.controllerDeviceId===device?"Kontrol bu cihazda":"Salt görüntüleme / katkı"}</p></div>
 <div className="salon-toolbar">{session.status==="PREPARING"&&<button className="button button-primary" disabled={criticalDisabled} onClick={()=>void act({type:"READY"})}>Hazırlığı onayla</button>}{session.status==="READY"&&<button className="button button-primary" disabled={criticalDisabled} onClick={()=>void act({type:"START"})}>Seansı başlat</button>}{session.status==="IN_PROGRESS"&&<button className="button button-secondary" disabled={criticalDisabled} onClick={()=>void act({type:"PAUSE"})}>Seansı duraklat</button>}{["PAUSED","CHECKPOINT_REQUIRED"].includes(session.status)&&<><button className="button button-secondary" disabled={criticalDisabled} onClick={()=>void act({type:"REASSESS",reason:"Profesyonel kontrol ve güncel güvenlik değerlendirmesi"})}>Güvenliği yeniden değerlendir</button><button className="button button-primary" disabled={criticalDisabled} onClick={()=>void act({type:"RESUME"})}>Seansa devam et</button></>}</div>
 <div className="live-columns"><div><SalonCard title="Uygulama sırası">{session.steps.map(st=><div key={st.id} className="live-item"><strong>{st.sequenceIndex+1}. {st.instructionText}</strong><p>{st.status} · Bölge {st.regionId}</p><button className="button button-secondary" disabled={criticalDisabled} onClick={()=>void act({type:st.status==="PENDING"?"STEP_START":"STEP_COMPLETE",step_id:st.id})}>{st.status==="PENDING"?"Adımı başlat":"Adımı tamamla"}</button></div>)}{!terminal(session.status)&&<SequenceEditor session={session} disabled={criticalDisabled} act={act}/>}</SalonCard></div>
 <div><SalonCard title="Sayaçlar">{session.timers.map(t=><TimerDisplay key={t.id} timer={t} now={now||Date.parse(session.updatedAt)} disabled={criticalDisabled} act={act}/>)}{!terminal(session.status)&&<TimerEditor disabled={criticalDisabled} act={act} session={session}/>}</SalonCard><SalonCard title="Canlı güvenlik">{session.riskEvents.map(e=><p key={e.id}>⚠ {e.type} · {e.action} · {e.note}</p>)}{!terminal(session.status)&&<RiskEditor disabled={disabled} act={act}/>}</SalonCard></div>
 <div><SalonCard title="Kaplar ve gerçek kullanım">{session.bowls.map(b=><UsageEditor key={b.id} bowl={b} disabled={disabled||terminal(session.status)} act={act}/>)}{!terminal(session.status)&&<BowlEditor disabled={criticalDisabled} session={session} act={act}/>}</SalonCard><SalonCard title="Kontrol noktaları">{session.checkpoints.map(cp=><CheckpointEditor key={cp.id} cp={cp} disabled={disabled||terminal(session.status)} act={act}/>)}{!terminal(session.status)&&<button className="button button-secondary" disabled={criticalDisabled} onClick={()=>void act({type:"CHECKPOINT_ADD",step_id:session.steps[0]!.id,checkpoint_type:"VISUAL_CHECK",required:false})}>İsteğe bağlı görsel kontrol ekle</button>}</SalonCard><SalonCard title="Teknik notlar">{session.notes.map(n=><p key={n.id}>{n.text}</p>)}{!terminal(session.status)&&<><label>Hızlı not<textarea value={note} onChange={e=>setNote(e.target.value)} maxLength={2000}/></label><button className="button button-secondary" disabled={disabled||!note.trim()} onClick={()=>void act({type:"NOTE",text:note})}>Notu kaydet</button><PhotoEditor disabled={disabled||!ctx.permissions.includes("live_session.contribute")} session={session} upload={photo}/></>}</SalonCard></div></div>
 {drafts.length>0&&<SalonCard title="Yerel taslaklar / çakışma incelemesi">{drafts.map(d=><div key={d.key} className="live-item"><strong>{d.command.type} · {reconcileDraft(d,session.recordVersion,session.controlEpoch)}</strong><pre>{JSON.stringify(d.command,null,2)}</pre><button className="button button-secondary" disabled={busy||!online} onClick={()=>void sync(d)}>Taslağı açık onayla senkronize et</button><button className="button button-secondary" onClick={()=>void removeDraft(d.key).then(()=>readDrafts(scope)).then(setDrafts)}>Taslağı sil</button></div>)}</SalonCard>}
 {!terminal(session.status)&&<><CompletionEditor session={session} disabled={criticalDisabled} act={act}/><RevisionEditor session={session} disabled={criticalDisabled} act={act}/><TransferEditor disabled={criticalDisabled} act={act}/><label>İptal / sonlandırma gerekçesi<textarea value={note} onChange={e=>setNote(e.target.value)}/></label><div className="salon-toolbar"><button className="button button-secondary" disabled={criticalDisabled||!note.trim()} onClick={()=>void act({type:"CANCEL",reason:note})}>Seansı iptal et</button><button className="button button-secondary" disabled={criticalDisabled||!note.trim()} onClick={()=>void act({type:"ABORT",reason:note})}>Güvenlik nedeniyle sonlandır</button></div></>}
 {session.outcome&&<SalonCard title="Profesyonel sonuç"><p>{session.outcome.professionalAssessment}</p>{session.outcome.regionalResults.map(r=><p key={r.regionId}>Seviye {r.achievedLevel} · {r.achievedTone} · {r.uniformity} · {r.hairIntegrity}</p>)}<p>Gerçek işlem süresi: {session.actualProcessSeconds??"Tamamlama bekleniyor"} sn</p><Link href={`/workspace/clients/${clientId}/hair-passport`}>Hair Passport geçmişini aç</Link></SalonCard>}
 <details><summary>Değişmez sapma ve reçete geçmişi</summary>{session.deviations.map(d=><p key={d.id}>{d.type} · {d.reason} · {new Date(d.at).toLocaleString("tr-TR")}</p>)}{session.recipes.map(r=><p key={r.id}>Reçete sürüm {r.version} · {r.result.selected.displayName} · {r.result.totalGrams} g</p>)}</details>
 </>}</main></SalonFrame>;
}
type Action=(patch:Record<string,unknown>)=>Promise<void>;
function TimerEditor({disabled,act,session}:{disabled:boolean;act:Action;session:LiveSession}){const [label,setLabel]=useState(""),[minutes,setMinutes]=useState("");return <div className="live-item"><label>Sayaç adı<input value={label} onChange={e=>setLabel(e.target.value)} maxLength={80}/></label><label>Uzmanın seçtiği süre (dakika)<input type="number" min="1" max="1440" value={minutes} onChange={e=>setMinutes(e.target.value)}/></label><p>Belgeli süre aralığı 30–45 dk; bu alan hatırlatıcıdır.</p><button className="button button-primary" disabled={disabled||!label||!minutes} onClick={()=>void act({type:"TIMER_ADD",label,duration_seconds:Number(minutes)*60,step_id:session.steps.find(s=>s.status==="IN_PROGRESS")?.id??null,region_id:null})}>Sayaç başlat</button></div>;}
function UsageEditor({bowl,disabled,act}:{bowl:LiveSession["bowls"][number];disabled:boolean;act:Action}){const [prepared,setPrepared]=useState(""),[used,setUsed]=useState(""),[reason,setReason]=useState("");return <div className="live-item"><strong>{bowl.label}</strong><p>Planlanan karışım: {bowl.plannedGrams} g</p>{bowl.closed?<p>Hazırlanan {bowl.preparedGrams} g · Kullanılan {bowl.usedGrams} g · Atık {bowl.wasteGrams} g</p>:<><p>Kalan karışım tekrar kullanılmaz; kap kapandığında kalan miktar atık kaydedilir. 1:1 karışım için 0,02 g hassasiyet kullanın.</p><label>Hazırlanan karışım (g)<input type="number" step="0.02" value={prepared} onChange={e=>setPrepared(e.target.value)}/></label><label>Kullanılan karışım (g)<input type="number" step="0.02" value={used} onChange={e=>setUsed(e.target.value)}/></label><label>Kullanım açıklaması<input value={reason} onChange={e=>setReason(e.target.value)}/></label><button className="button button-primary" disabled={disabled||!prepared||!used||!reason} onClick={()=>void act({type:"USAGE",bowl_id:bowl.id,prepared_grams:Number(prepared),used_grams:Number(used),reason})}>Kullanımı kaydet ve kabı kapat</button></>}</div>;}
function CheckpointEditor({cp,disabled,act}:{cp:LiveSession["checkpoints"][number];disabled:boolean;act:Action}){const [note,setNote]=useState("");return <div className="live-item"><strong>{cp.type} · {cp.required?"Zorunlu":"İsteğe bağlı"} · {cp.result}</strong>{cp.result==="PENDING"&&<><label>Kontrol notu<input value={note} onChange={e=>setNote(e.target.value)}/></label><div className="salon-toolbar">{["PASS","CONCERN","FAIL"].map(result=><button className="button button-secondary" key={result} disabled={disabled||!note} onClick={()=>void act({type:"CHECKPOINT_RECORD",checkpoint_id:cp.id,result,note})}>{{PASS:"Kontrol uygun",CONCERN:"Endişe var",FAIL:"Kontrol başarısız"}[result]}</button>)}</div></>}</div>;}
function RiskEditor({disabled,act}:{disabled:boolean;act:Action}){const [type,setType]=useState("UNEXPECTED_BREAKAGE"),[note,setNote]=useState("");return <div><label>Yeni teknik bilgi<select value={type} onChange={e=>setType(e.target.value)}>{["UNEXPECTED_BREAKAGE","UNEXPECTED_LIFT","ELASTICITY_CONCERN","UNEXPECTED_BAND","SCALP_CONCERN"].map(t=><option key={t}>{t}</option>)}</select></label><label>Güvenlik notu<textarea value={note} onChange={e=>setNote(e.target.value)}/></label><button className="button button-primary" disabled={disabled||!note||!navigator.onLine} onClick={()=>void act({type:"RISK_EVENT",event_type:type,note})}>Teknik olayı kaydet</button></div>;}
function SequenceEditor({session,disabled,act}:{session:LiveSession;disabled:boolean;act:Action}){const [text,setText]=useState(""),[reason,setReason]=useState("");return <details><summary>Profesyonel uygulama sırasını düzenle</summary><p>Yeni satır = yeni adım. Mevcut dip bölgesi korunur; adı üzerinden farklı bölge türetilmez.</p><label>Adım metinleri<textarea value={text} onChange={e=>setText(e.target.value)}/></label><label>Sıra değişikliği gerekçesi<input value={reason} onChange={e=>setReason(e.target.value)}/></label><button className="button button-secondary" disabled={disabled||!text.trim()||!reason} onClick={()=>void act({type:"SEQUENCE",reason,steps:text.split("\n").filter(Boolean).map((line,i)=>({id:session.steps[i]?.id??crypto.randomUUID(),region_id:session.bowls[0]!.regionIds[0],bowl_id:session.bowls[0]!.id,instruction_type:"APPLICATION",instruction_text:line}))})}>Sırayı kaydet</button></details>;}
function BowlEditor({session,disabled,act}:{session:LiveSession;disabled:boolean;act:Action}){const [label,setLabel]=useState(""),[grams,setGrams]=useState(""),[reason,setReason]=useState("");return <details><summary>Aynı onaylı bölge için yeni kap</summary><label>Kap adı<input value={label} onChange={e=>setLabel(e.target.value)}/></label><label>Planlanan karışım (g)<input type="number" value={grams} onChange={e=>setGrams(e.target.value)}/></label><label>Kap gerekçesi<input value={reason} onChange={e=>setReason(e.target.value)}/></label><button className="button button-secondary" disabled={disabled||!label||!grams||!reason} onClick={()=>void act({type:"BOWL_ADD",label,planned_grams:Number(grams),region_id:session.recipes.find(r=>r.id===session.currentRecipeId)!.result.context.regionId,reason})}>Kap ekle</button></details>;}
function TransferEditor({disabled,act}:{disabled:boolean;act:Action}){const [user,setUser]=useState(""),[device,setDevice]=useState(""),[reason,setReason]=useState("");return <details><summary>Kontrol devri</summary><label>Yetkili kullanıcı kimliği<input value={user} onChange={e=>setUser(e.target.value)}/></label><label>Hedef cihaz kimliği<input value={device} onChange={e=>setDevice(e.target.value)}/></label><p>Bu cihaz: {typeof window!=="undefined"?sessionStorage.getItem("elifora-live-device"):""}</p><label>Devir gerekçesi<input value={reason} onChange={e=>setReason(e.target.value)}/></label><button className="button button-secondary" disabled={disabled} onClick={()=>void act({type:"TRANSFER_CONTROL",user_id:user,target_device_id:device,reason})}>Kontrolü devret</button></details>;}
function RevisionEditor({session,disabled,act}:{session:LiveSession;disabled:boolean;act:Action}){const [id,setId]=useState(""),[note,setNote]=useState(""),[accepted,setAccepted]=useState(false);return <details><summary>Yeni onaylı reçete sürümüne geç</summary><p>Mevcut reçete {session.currentRecipeId} korunur. Yeni sürümü ColorLab’da oluşturun; mevcut kaplar eski reçeteye bağlı kalır.</p><label>Yeni reçete kaydı kimliği<input value={id} onChange={e=>setId(e.target.value)}/></label><label>Revizyon ve inceleme gerekçesi<textarea value={note} onChange={e=>setNote(e.target.value)}/></label><label className="hp-check"><input type="checkbox" checked={accepted} onChange={e=>setAccepted(e.target.checked)}/>Yeni reçeteyi profesyonel olarak inceledim.</label><button className="button button-secondary" disabled={disabled||!accepted} onClick={()=>void act({type:"RECIPE_REVISION",recipe_id:id,professional_review:true,review_note:note,reason:note})}>Revizyonu doğrula</button></details>;}
function CompletionEditor({session,disabled,act}:{session:LiveSession;disabled:boolean;act:Action}){
 const [assessment,setAssessment]=useState(""),[level,setLevel]=useState(""),[tone,setTone]=useState(""),[reviewed,setReviewed]=useState(false);
 const [profile,setProfile]=useState<NonNullable<LiveSession["outcome"]>["profile"]>({colorAccuracy:"UNKNOWN",uniformity:"UNKNOWN",hairIntegrity:"UNKNOWN",processEfficiency:"UNKNOWN",formulaStability:"UNKNOWN"});
 const labels={colorAccuracy:"Renk doğruluğu",uniformity:"Bölgesel eşitlik",hairIntegrity:"Saç bütünlüğü",processEfficiency:"İşlem verimliliği",formulaStability:"Formül kararlılığı"};
 return <SalonCard title="Zorunlu sonuç incelemesi">{session.status==="COMPLETION_REVIEW"?<button className="button button-primary" disabled={disabled} onClick={()=>void act({type:"COMPLETE"})}>Seansı tamamla ve Hair Passport’a ekle</button>:<>
 <p>Gerçek kullanım, süre ve sapmaları inceleyin. Bölgesel sonucu profesyonel olarak doğrulayın.</p>
 {session.targetSnapshot.definition.regions.map(r=><p key={r.regionId}>Hedef bölge {r.regionId}: {r.preserve?"Mevcut rengi koru":`Seviye ${r.level} · ${r.toneFamily}`}</p>)}
 <label>Ulaşılan seviye<input type="number" min="1" max="12" value={level} onChange={e=>setLevel(e.target.value)}/></label><label>Ulaşılan ton<input value={tone} onChange={e=>setTone(e.target.value)}/></label>
 {(Object.keys(labels) as (keyof typeof labels)[]).map(key=><label key={key}>{labels[key]}<select value={profile[key]} onChange={e=>setProfile({...profile,[key]:e.target.value as typeof profile[typeof key]})}>{["UNKNOWN","ACCEPTABLE","CONCERN","UNACCEPTABLE"].map(value=><option key={value}>{value}</option>)}</select></label>)}
 <label>Profesyonel değerlendirme<textarea value={assessment} onChange={e=>setAssessment(e.target.value)}/></label><label className="hp-check"><input type="checkbox" checked={reviewed} onChange={e=>setReviewed(e.target.checked)}/>Gerçek kullanım, süre, sapmalar ve bölgesel sonucu inceledim.</label>
 <button className="button button-primary" disabled={disabled||!level||!tone||!assessment||!reviewed} onClick={()=>void act({type:"COMPLETION_REVIEW",outcome:{regionalResults:[...new Set(session.bowls.flatMap(b=>b.regionIds))].map(regionId=>({regionId,achievedLevel:Number(level),achievedTone:tone,uniformity:profile.uniformity,hairIntegrity:profile.hairIntegrity,assessment})),profile,professionalAssessment:assessment,deviationsReviewed:true}})}>Sonuç incelemesini kaydet</button></>}</SalonCard>;
}

function PhotoEditor({session,disabled,upload}:{session:LiveSession;disabled:boolean;upload:(file:File,kind:string)=>Promise<void>}){const [kind,setKind]=useState("PROCESS");return <div><label>Fotoğraf türü<select value={kind} onChange={e=>setKind(e.target.value)}>{["BEFORE","CHECKPOINT","PROCESS","AFTER"].map(k=><option key={k}>{k}</option>)}</select></label><label>Özel teknik fotoğraf<input type="file" accept="image/png,image/jpeg,image/webp" disabled={disabled} onChange={e=>{const file=e.target.files?.[0];if(file)void upload(file,kind);}}/></label>{session.photos.map(p=><p key={p.id}><a href={`/api/live-sessions/${session.id}/photos/${p.id}?client_id=${session.clientId}`} target="_blank" rel="noreferrer">{p.kind} fotoğrafını aç</a></p>)}</div>;}

function TimerDisplay({timer:t,now,disabled,act}:{timer:LiveSession["timers"][number];now:number;disabled:boolean;act:Action}){const elapsed=timerElapsed(t,now);return <div className="live-item"><strong>{t.label} · {t.status}</strong><output className="live-timer" aria-label={`${t.label} kalan süre`}>{Math.ceil(Math.max(0,t.plannedDuration-elapsed)/60)} dk · {Math.floor(elapsed)} sn</output>{elapsed>=t.plannedDuration&&<p>⏱ Süre doldu · profesyonel kontrol gerekli. Otomatik uygulama talimatı değildir.</p>}{!["COMPLETED","CANCELLED"].includes(t.status)&&<div className="salon-toolbar"><button className="button button-secondary" disabled={disabled} onClick={()=>void act({type:"TIMER_ACTION",timer_id:t.id,action:t.status==="RUNNING"?"PAUSE":"RESUME"})}>{t.status==="RUNNING"?"Duraklat":"Sürdür"}</button><button className="button button-secondary" disabled={disabled} onClick={()=>void act({type:"TIMER_ACTION",timer_id:t.id,action:"COMPLETE"})}>Sayacı tamamla</button><button className="button button-secondary" disabled={disabled} onClick={()=>void act({type:"TIMER_ACTION",timer_id:t.id,action:"CANCEL"})}>Sayacı iptal et</button></div>}</div>;}
