import { expect,it,vi,beforeEach } from "vitest";
import { render,screen,waitFor,fireEvent,cleanup } from "@testing-library/react";
import { liveFixture } from "@/test/live-fixtures";
import { fixtureId } from "@/test/confidence-fixtures";
import { LiveSessionWorkspace } from "./live-session-workspace";
const mocks=vi.hoisted(()=>({draft:vi.fn(),read:vi.fn(),remove:vi.fn(),push:vi.fn()}));
vi.mock("next/navigation",()=>({useRouter:()=>({push:mocks.push})}));
vi.mock("@/lib/live/offline",async original=>({...await original<typeof import("@/lib/live/offline")>(),storeDraft:mocks.draft,readDrafts:mocks.read,removeDraft:mocks.remove}));
const ctx={membership_id:fixtureId(900),organization_id:fixtureId(8001),location_id:fixtureId(2),organization_name:"Synthetic live salon",location_name:"Synthetic",role:"owner",membership_status:"active",permissions:["live_session.view","live_session.start","live_session.control","live_session.contribute","live_session.usage","live_session.checkpoint","live_session.revise","live_session.complete","live_session.cancel"]};
beforeEach(()=>{cleanup();vi.clearAllMocks();mocks.read.mockResolvedValue([]);mocks.draft.mockResolvedValue(undefined);sessionStorage.clear();Object.defineProperty(navigator,"onLine",{configurable:true,value:true});});
function setup(specific=false){const f=liveFixture();f.s.status="IN_PROGRESS";f.s.startedAt=f.a.now;sessionStorage.setItem("elifora-live-device",f.q.device_id);vi.stubGlobal("fetch",vi.fn(async (url:string)=>Response.json(url==="/api/session"?{context:ctx}:{data:specific?f.s:[]},{headers:{"X-Server-Time":f.a.now}})));render(<LiveSessionWorkspace clientId={f.s.clientId} recipeId={f.q.recipe_id} sessionId={specific?f.s.id:undefined}/>);return f;}
it("creation requires explicit professional review, not just an old stored recipe",async()=>{setup();await screen.findByLabelText("Profesyonel inceleme notu");const button=screen.getByRole("button",{name:"Onayla ve seans hazırla"});expect(button).toBeDisabled();fireEvent.change(screen.getByLabelText("Profesyonel inceleme notu"),{target:{value:"Reviewed current official recipe"}});expect(button).toBeDisabled();fireEvent.click(screen.getByLabelText("Reçeteyi ve resmi koşulları bu uygulama için değerlendirdim."));expect(button).toBeEnabled();});
it("live mode shows explicit control and checkpoint labels",async()=>{setup(true);await screen.findByText(/Kontrol bu cihazda/);expect(screen.getByText(/HAIR_INTEGRITY_CHECK · Zorunlu · PENDING/)).toBeVisible();expect(screen.getByRole("button",{name:"Seansı duraklat"})).toBeEnabled();});
it("offline note is a scoped local draft and never final server mutation",async()=>{const f=setup(true);await screen.findByLabelText("Hızlı not");Object.defineProperty(navigator,"onLine",{configurable:true,value:false});fireEvent(window,new Event("offline"));fireEvent.change(screen.getByLabelText("Hızlı not"),{target:{value:"Local assessed note"}});fireEvent.click(screen.getByRole("button",{name:"Notu kaydet"}));await waitFor(()=>expect(mocks.draft).toHaveBeenCalled());expect(mocks.draft.mock.calls[0]![0]).toMatchObject({scope:`${ctx.membership_id}:${ctx.location_id}:${f.q.device_id}:${f.s.id}`,command:{type:"NOTE",text:"Local assessed note",expected_version:1}});expect(screen.getByRole("button",{name:"Seansı duraklat"})).toBeDisabled();});
it("outcome ratings are independent; no blanket technical score is inferred",async()=>{setup(true);await screen.findByLabelText("Renk doğruluğu");fireEvent.change(screen.getByLabelText("Renk doğruluğu"),{target:{value:"ACCEPTABLE"}});expect(screen.getByLabelText("Saç bütünlüğü")).toHaveValue("UNKNOWN");expect(screen.getByLabelText("Formül kararlılığı")).toHaveValue("UNKNOWN");});
