import { act,cleanup,fireEvent,render,screen,waitFor } from "@testing-library/react";
import { afterEach,beforeEach,expect,it,vi } from "vitest";
import { SalonOperations } from "./salon-operations";
import { salonFixture } from "@/test/salon-fixtures";
beforeEach(()=>{Object.defineProperty(HTMLDialogElement.prototype,"showModal",{configurable:true,value:function(this:HTMLDialogElement){this.setAttribute("open","");}});const f=salonFixture();vi.stubGlobal("fetch",vi.fn().mockResolvedValue({ok:true,status:200,json:async()=>({data:f.snapshot,context:f.context})}));});
afterEach(()=>{cleanup();Reflect.deleteProperty(HTMLDialogElement.prototype,"showModal");vi.unstubAllGlobals();vi.restoreAllMocks();});
it("real settings edit preserves the full service definition",async()=>{render(<SalonOperations section="settings"/>);await screen.findByRole("heading",{name:"Hizmet kataloğu"});fireEvent.click(screen.getByRole("button",{name:"Hizmeti düzenle"}));await screen.findByRole("dialog");expect(screen.getByLabelText("Hizmet adı")).toHaveValue("Synthetic color");expect(screen.getByLabelText("Varsayılan süre (dk)")).toHaveValue(60);expect(screen.getByLabelText("ColorLab gerekli")).toBeChecked();expect(screen.getByLabelText("Genel renklendirme")).toHaveValue("INDEPENDENT");});
it("readonly member can see real team but cannot alter profiles",async()=>{const f=salonFixture();f.context.permissions=["salon.read"];vi.mocked(fetch).mockResolvedValue({ok:true,status:200,json:async()=>({data:f.snapshot,context:f.context})} as Response);render(<SalonOperations section="team"/>);await screen.findByRole("heading",{name:"Synthetic professional"});expect(screen.queryByRole("button",{name:"Personeli düzenle"})).toBeNull();expect(screen.queryByRole("button",{name:"Üyelikten personel tanımla"})).toBeNull();});
it("offline event conceals customer appointments and open forms",async()=>{render(<SalonOperations section="appointments"/>);await screen.findByRole("heading",{name:"Randevular"});fireEvent.change(screen.getByLabelText("Takvim başlangıcı"),{target:{value:"2026-10-12"}});await screen.findByRole("button",{name:/Synthetic client/});fireEvent.click(screen.getByRole("button",{name:"Randevu oluştur"}));await screen.findByRole("dialog");fireEvent(window,new Event("offline"));await waitFor(()=>{expect(screen.queryByRole("dialog")).toBeNull();expect(screen.queryByText("Synthetic client")).toBeNull();expect(screen.queryByRole("button",{name:/Synthetic client/})).toBeNull();});});
it("malformed foreign snapshot is concealed rather than rendered",async()=>{const f=salonFixture();f.snapshot.location.organization_id="a4000000-0000-4000-8000-000000000099";vi.mocked(fetch).mockResolvedValue({ok:true,status:200,json:async()=>({data:f.snapshot,context:f.context})} as Response);render(<SalonOperations section="appointments"/>);await screen.findByRole("alert");expect(screen.queryByRole("button",{name:/Synthetic client/})).toBeNull();});
function backgroundTick(){let tick=()=>{};const original=window.setInterval.bind(window);vi.spyOn(window,"setInterval").mockImplementation((handler,delay)=>{if(delay!==60000)return original(handler,delay) as unknown as ReturnType<typeof setInterval>;tick=handler as ()=>void;return 1 as unknown as ReturnType<typeof setInterval>;});return async()=>{await act(async()=>{tick();});};}
it("authorized background refresh preserves an open editor and its original version",async()=>{
 const tick=backgroundTick();render(<SalonOperations section="settings"/>);await screen.findByRole("heading",{name:"Hizmet kataloğu"});fireEvent.click(screen.getByRole("button",{name:"Hizmeti düzenle"}));fireEvent.change(screen.getByLabelText("Hizmet adı"),{target:{value:"Unsaved professional edit"}});
 const f=salonFixture();f.snapshot.services[0]!.version=2;vi.mocked(fetch).mockResolvedValue({ok:true,status:200,json:async()=>({data:f.snapshot,context:f.context})} as Response);await tick();expect(screen.getByLabelText("Hizmet adı")).toHaveValue("Unsaved professional edit");
 vi.mocked(fetch).mockResolvedValue({ok:false,status:409,json:async()=>({code:"SALON_CONFLICT"})} as Response);fireEvent.click(screen.getByRole("button",{name:"Değişiklikleri kaydet"}));await screen.findByRole("alert");expect(JSON.parse(vi.mocked(fetch).mock.lastCall![1]!.body as string).expected_version).toBe(1);
});
it("working-hour edits keep their original version across background refresh",async()=>{
 const tick=backgroundTick();render(<SalonOperations section="settings"/>);await screen.findByRole("heading",{name:"Hizmet kataloğu"});fireEvent.click(screen.getByRole("button",{name:"Çalışma saatleri"}));fireEvent.change(screen.getByLabelText("Pazartesi açılış"),{target:{value:"10:00"}});
 const f=salonFixture(),version=f.snapshot.hours.version;f.snapshot.hours.version=version+1;vi.mocked(fetch).mockResolvedValue({ok:true,status:200,json:async()=>({data:f.snapshot,context:f.context})} as Response);await tick();expect(screen.getByLabelText("Pazartesi açılış")).toHaveValue("10:00");
 vi.mocked(fetch).mockResolvedValue({ok:false,status:409,json:async()=>({code:"SALON_CONFLICT"})} as Response);fireEvent.click(screen.getByRole("button",{name:"Değişiklikleri kaydet"}));await screen.findByRole("alert");expect(JSON.parse(vi.mocked(fetch).mock.lastCall![1]!.body as string).expected_version).toBe(version);
});
it("failed background authorization refresh conceals data and pending edits",async()=>{
 const tick=backgroundTick();render(<SalonOperations section="settings"/>);await screen.findByRole("heading",{name:"Hizmet kataloğu"});fireEvent.click(screen.getByRole("button",{name:"Hizmeti düzenle"}));vi.mocked(fetch).mockResolvedValue({ok:false,status:503,json:async()=>({code:"NETWORK_ERROR"})} as Response);await tick();await screen.findByRole("alert");expect(screen.queryByRole("dialog")).toBeNull();expect(screen.queryByText("Synthetic color")).toBeNull();
});
