import {it,expect,vi,beforeEach,afterEach} from "vitest";
import {render,screen,waitFor,fireEvent,cleanup} from "@testing-library/react";
import {StockWorkspace} from "./stock-workspace";
import {stockFixture} from "@/test/stock-fixtures";
beforeEach(()=>{vi.stubGlobal("fetch",vi.fn(async()=>Response.json({context:stockFixture().context,data:stockFixture().snapshot})));});
afterEach(()=>{cleanup();vi.unstubAllGlobals();});
it("renders actual balance and existing brand frame",async()=>{render(<StockWorkspace/>);expect(await screen.findByText("100 g")).toBeVisible();expect(screen.getByRole("heading",{name:"Stok ve ürünler"})).toBeVisible();expect(screen.getByRole("region",{name:"Operasyon aksiyon merkezi"})).toBeVisible();});
it("UNKNOWN is never a fabricated zero",async()=>{const f=stockFixture();f.snapshot.items[0]!.on_hand=null;f.snapshot.items[0]!.stock_status="UNKNOWN";vi.mocked(fetch).mockResolvedValue(Response.json({context:f.context,data:f.snapshot}));render(<StockWorkspace/>);await screen.findByText("Synthetic salon product");expect(screen.queryByText("0 g")).toBeNull();expect(screen.getAllByText("Bilinmiyor").length).toBeGreaterThan(0);});
it("view-only permissions conceal all mutation entry points",async()=>{const f=stockFixture();f.context.permissions=["stock.view"];vi.mocked(fetch).mockResolvedValue(Response.json({context:f.context,data:f.snapshot}));render(<StockWorkspace/>);await screen.findByText("100 g");expect(screen.queryByRole("button",{name:"Stok girişi",exact:true})).toBeNull();expect(screen.queryByRole("button",{name:"Ürün ekle"})).toBeNull();});
it("background hides inventory and discards late response",async()=>{render(<StockWorkspace/>);await screen.findByText("100 g");Object.defineProperty(document,"hidden",{configurable:true,value:true});fireEvent(document,new Event("visibilitychange"));await waitFor(()=>expect(screen.queryByText("100 g")).toBeNull());Object.defineProperty(document,"hidden",{configurable:true,value:false});});
