"use client";
import { useCallback,useEffect,useRef,useState } from "react";
import Link from "next/link";
import {OperationalActionBoundary} from "./operational-action-boundary";
import { SalonFrame,SalonHeading,SalonCard,SalonStat } from "./salon-frame";
import { stockSnapshot,stockResult,stockCommand,stockDefinition,stockPermission,type StockSnapshot,type StockCommand } from "@/lib/stock/model";
import { tenantContextSchema,workspaceReference,type ActiveTenantContext } from "@/lib/tenant/context";

const units={GRAM:"g",MILLILITER:"ml",UNIT:"adet"},statuses={OK:"Yeterli",LOW:"Azaldı",OUT:"Tükendi",UNKNOWN:"Bilinmiyor"};
const errors:Record<string,string>={STOCK_COUNT_STALE:"Sayım sırasında stok değişti veya bekleyen kullanım var. Yeni sayım oluşturun.",STOCK_INSUFFICIENT:"Stok yetersiz. Teknik kullanım korunuyor; stok girişini kontrol edin.",STOCK_USAGE_RECONCILIATION_REQUIRED:"Hazırlanan miktar bilinmiyor. Canlı oturumda malzeme mutabakatı kaydedin.",STOCK_PRODUCT_MAPPING_REQUIRED:"Doğrulanmış ürünü bu şubenin stok kartıyla eşleyin.",STOCK_OPENING_REQUIRED:"Önce ölçülmüş açılış miktarını kaydedin. Ölçülmüş sıfır geçerlidir.",UNIT_CONVERSION_REQUIRED:"Birimler uyumsuz. Gram ve mililitre otomatik çevrilmez.",STOCK_LOT_REQUIRED:"Bu ürün için gerçek lot seçimi gerekli.",STOCK_LOT_CONFLICT:"Lot bu ürüne ait değil veya önceki kullanımla uyuşmuyor.",STOCK_CONFLICT:"Kayıt değişti veya işlem daha önce farklı içerikle kullanıldı. Yenileyin.",STOCK_MAPPING_IMMUTABLE:"Ürün, birim ve takip türü tarihçe nedeniyle değiştirilemez.",VALIDATION_FAILED:"Alanları ve miktarın en fazla iki ondalık basamağını kontrol edin.",NETWORK_ERROR:"Stok yüklenemedi. Tekrar deneyin."};
type Mode="ITEM_SAVE"|"LOT_SAVE"|"OPENING"|"RECEIPT"|"ADJUSTMENT_IN"|"ADJUSTMENT_OUT"|"COUNT_CREATE"|"POLICY";
function text(f:FormData,k:string){return String(f.get(k)??"").trim();}
function optional(f:FormData,k:string){return text(f,k)||null;}
export function StockWorkspace(){
 const [data,setData]=useState<StockSnapshot|null>(null),[ctx,setCtx]=useState<ActiveTenantContext|null>(null),[error,setError]=useState(""),[notice,setNotice]=useState(""),[busy,setBusy]=useState(false),[query,setQuery]=useState(""),[offset,setOffset]=useState(0),[selected,setSelected]=useState(""),[,setTraceLot]=useState(""),[mode,setMode]=useState<Mode|null>(null),[editing,setEditing]=useState(""),[catalog,setCatalog]=useState(""),[formItem,setFormItem]=useState(""),[eventLots,setEventLots]=useState<Record<string,string>>({});
 const generation=useRef(0),visible=useRef(true),context=useRef<ActiveTenantContext|null>(null),filters=useRef({query:"",offset:0,selected:"",traceLot:""}),pending=useRef<{key:string;mutationId:string}|null>(null),formId=useRef("");
 const cancelRequests=useCallback(()=>{generation.current++;},[]);
 const conceal=useCallback(()=>{generation.current++;context.current=null;setData(null);setCtx(null);setMode(null);setNotice("");},[]);
 const fail=useCallback((code:string)=>{if(["SESSION_EXPIRED","UNAUTHENTICATED","FORBIDDEN","MEMBERSHIP_REVOKED","MEMBERSHIP_REQUIRED","TENANT_CONTEXT_INVALID"].includes(code)){conceal();window.location.assign(code==="UNAUTHENTICATED"||code==="SESSION_EXPIRED"?"/sign-in":"/workspaces");}else setError(errors[code]??code);},[conceal]);
 const load=useCallback(async()=>{
  const n=++generation.current,f=filters.current;setError("");
  try{const params=new URLSearchParams();if(f.query)params.set("query",f.query);params.set("offset",String(f.offset));if(f.selected)params.set("item_id",f.selected);if(f.traceLot)params.set("lot_id",f.traceLot);
   const reply=await fetch("/api/stock?"+params,{cache:"no-store"}),body=await reply.json();if(n!==generation.current||!visible.current)return;
   if(!reply.ok){fail(body.code??"NETWORK_ERROR");return;}const c=tenantContextSchema.parse(body.context),d=stockSnapshot.parse(body.data);
   if(context.current&&workspaceReference(context.current)!==workspaceReference(c)){conceal();return;}context.current=c;setCtx(c);setData(d);
  }catch{if(n===generation.current)fail("NETWORK_ERROR");}
 },[conceal,fail]);
 useEffect(()=>{const initial=setTimeout(()=>{const p=new URLSearchParams(window.location.search),id=p.get("item_id");if(id&&/^[0-9a-f-]{36}$/i.test(id)){filters.current.selected=id;setSelected(id);}void load();},0);const changed=()=>{visible.current=!document.hidden;conceal();if(visible.current)void load();};document.addEventListener("visibilitychange",changed);window.addEventListener("focus",changed);const interval=setInterval(()=>{if(visible.current)void load();},15000);return()=>{cancelRequests();clearTimeout(initial);clearInterval(interval);document.removeEventListener("visibilitychange",changed);window.removeEventListener("focus",changed);};},[load,conceal,cancelRequests]);
 const permitted=(permission:string)=>ctx?.permissions.includes(permission)??false;
 async function save(command:StockCommand){const current=context.current;if(!current||busy)return;const key=JSON.stringify({...command,mutation_id:undefined});if(pending.current?.key!==key)pending.current={key,mutationId:command.mutation_id};command={...command,mutation_id:pending.current.mutationId};const n=generation.current;setBusy(true);setError("");setNotice("");
  try{const r=await fetch("/api/stock",{method:"POST",headers:{"Content-Type":"application/json","x-workspace-reference":workspaceReference(current)},body:JSON.stringify(command)}),body=await r.json();if(n!==generation.current||!visible.current)return;
   if(!r.ok){fail(body.code??"NETWORK_ERROR");return;}const result=stockResult.parse(body.data);pending.current=null;if(result.status==="FAILED")setNotice(errors[result.error_code??""]??"Stok olayı işlenemedi; teknik kayıt korundu.");else{setNotice("İşlem kaydedildi.");setMode(null);}await load();
  }catch{fail("NETWORK_ERROR");}finally{setBusy(false);}
 }
 async function submit(event:React.FormEvent<HTMLFormElement>){event.preventDefault();if(!mode||!data)return;const f=new FormData(event.currentTarget),reason=text(f,"reason"),mutation_id=crypto.randomUUID();let raw:unknown;
  if(mode==="ITEM_SAVE") {const option=data.catalog_options.find(p=>p.id===catalog),old=data.items.find(i=>i.id===editing);raw={type:mode,mutation_id,id:editing||formId.current,expected_version:old?.version??0,reason,definition:{source:old?.source??option?.source??"SALON_CUSTOM_OPERATIONAL_PRODUCT",catalog_product_id:old?.catalog_product_id??option?.id??null,product_type:text(f,"product_type"),display_name:text(f,"display_name"),sku:optional(f,"sku"),barcode:optional(f,"barcode"),inventory_unit:old?.inventory_unit??text(f,"unit"),active:f.has("active"),track_quantity:old?.track_quantity??f.has("track_quantity"),lot_required:f.has("lot_required"),low_threshold:text(f,"low_threshold")===""?null:Number(text(f,"low_threshold"))}};}
  else if(mode==="LOT_SAVE")raw={type:mode,mutation_id,id:formId.current,expected_version:0,stock_item_id:formItem,lot_number:text(f,"lot_number"),batch_number:optional(f,"batch_number"),expiry_date:optional(f,"expiry_date"),opened_at:text(f,"opened_at")?new Date(text(f,"opened_at")).toISOString():null,received_at:new Date(text(f,"received_at")).toISOString(),reason};
  else if(mode==="POLICY")raw={type:mode,mutation_id,expected_version:data.settings?.version??0,negative_policy:text(f,"negative_policy"),reason};
  else if(mode==="COUNT_CREATE")raw={type:mode,mutation_id,id:formId.current,lines:[{stock_item_id:formItem,lot_id:optional(f,"lot_id"),counted_quantity:Number(text(f,"quantity"))}],reason};
  else {const i=data.items.find(i=>i.id===formItem);raw={type:mode,mutation_id,stock_item_id:formItem,lot_id:optional(f,"lot_id"),quantity:Number(text(f,"quantity")),unit:i?.inventory_unit,occurred_at:new Date(text(f,"occurred_at")).toISOString(),reference:optional(f,"reference"),reason};}
  const p=stockCommand.safeParse(raw);if(!p.success){fail("VALIDATION_FAILED");return;}await save(p.data);
 }
 function open(m:Mode,item="",edit=""){formId.current=crypto.randomUUID();pending.current=null;setMode(m);setFormItem(item||data?.items[0]?.id||"");setEditing(edit);setCatalog("");setError("");}
 const item=data?.items.find(i=>i.id===selected),old=data?.items.find(i=>i.id===editing);
 return <SalonFrame active="stock" workspace={ctx?.location_name}><main id="main-content" className="salon-main stock-workspace"><SalonHeading title={item?.display_name??"Stok ve ürünler"} description="Şube stoğunu, ölçülmüş kullanımı ve ürün lotlarını takip edin." actions={<button className="button button-secondary" onClick={()=>void load()} disabled={busy}>Yenile</button>}/>
 {error&&<p role="alert" className="stock-error">{error}</p>}{notice&&<p role="status">{notice}</p>}
 {!data?<SalonCard><p>Stok yükleniyor…</p></SalonCard>:!data.settings?<SalonCard title="Stok başlangıcı"><p>Açılış miktarları fiziksel ölçüme dayanır. Daha önceki canlı oturumlar PRE_STOCK_HISTORY olarak kalır ve otomatik düşülmez.</p>{permitted("stock.manage_items")&&<button className="button" disabled={busy} onClick={()=>void save({type:"ENABLE",mutation_id:crypto.randomUUID(),reason:"Şubede fiziksel açılış sayımıyla stok takibini başlat"})}>Stok takibini başlat</button>}</SalonCard>:<>
 <div className="salon-stats three"><SalonStat label="Aktif stok kartı" value={data.monitoring.active_items} icon="reports"/><SalonStat label="Azalan stok" value={data.monitoring.low_items} icon="reports"/><SalonStat label="Tükenen stok" value={data.monitoring.out_items} icon="reports"/><SalonStat label="Yaklaşan son kullanım" value={data.monitoring.expiring_lots} icon="clock"/><SalonStat label="Mutabakat gerekli" value={data.monitoring.unreconciled} icon="reports"/><SalonStat label="Bekleyen kullanım" value={data.monitoring.pending} icon="clock"/><SalonStat label="İşlenemeyen olay" value={data.monitoring.failed} icon="reports"/></div>
 <div className="stock-toolbar">{selected?<button className="button button-secondary" onClick={()=>{filters.current={query:"",offset:0,selected:"",traceLot:""};setSelected("");setTraceLot("");setQuery("");setOffset(0);void load();}}>Tüm ürünler</button>:<form onSubmit={e=>{e.preventDefault();filters.current={query,offset:0,selected:"",traceLot:""};setOffset(0);void load();}}><label>Ürün, SKU, barkod veya üretici kodu<input type="search" maxLength={80} value={query} onChange={e=>setQuery(e.target.value)}/></label><button className="button button-secondary">Ara</button></form>}
 {permitted("stock.manage_items")&&<><button className="button" onClick={()=>open("ITEM_SAVE")}>Ürün ekle</button><button className="button button-secondary" onClick={()=>open("POLICY")}>Stok politikası</button></>}
 {(["OPENING","RECEIPT","ADJUSTMENT_IN","ADJUSTMENT_OUT","COUNT_CREATE","LOT_SAVE"] as const).filter(t=>permitted(stockPermission(t))).map(t=><button key={t} className="button button-secondary" onClick={()=>open(t,selected)}>{({OPENING:"Açılış miktarı",RECEIPT:"Stok girişi",ADJUSTMENT_IN:"Artı düzeltme",ADJUSTMENT_OUT:"Eksi düzeltme",COUNT_CREATE:"Fiziksel sayım",LOT_SAVE:"Lot ekle"})[t]}</button>)}</div>
 {mode&&<SalonCard title={{ITEM_SAVE:editing?"Ürünü düzenle":"Stok kartı ekle",LOT_SAVE:"Gerçek ürün lotu",OPENING:"Ölçülmüş açılış",RECEIPT:"Stok girişi",ADJUSTMENT_IN:"Artı düzeltme",ADJUSTMENT_OUT:"Eksi düzeltme",COUNT_CREATE:"Fiziksel sayım taslağı",POLICY:"Negatif stok politikası"}[mode]}><form className="stock-form" onSubmit={e=>void submit(e)}>
 {mode==="ITEM_SAVE"?<>
 {!editing&&<label>Katalog eşlemesi<select value={catalog} onChange={e=>setCatalog(e.target.value)}><option value="">Salon operasyon ürünü · teknik doğrulama değildir</option>{data.catalog_options.map(p=><option key={p.id} value={p.id}>{p.name} · {p.manufacturer_code}</option>)}</select></label>}
 <label>Ürün adı<input name="display_name" required maxLength={160} key={catalog+editing} defaultValue={old?.display_name??data.catalog_options.find(p=>p.id===catalog)?.name??""}/></label><label>Tür<select name="product_type" defaultValue={old?.product_type??"COLOR"}>{stockDefinition.shape.product_type.options.map(v=><option key={v}>{v}</option>)}</select></label>
 <label>Envanter birimi<select name="unit" defaultValue={old?.inventory_unit??"GRAM"} disabled={!!editing}>{Object.entries(units).map(([u,label])=><option key={u} value={u}>{label}</option>)}</select></label><label>SKU<input name="sku" maxLength={80} defaultValue={old?.sku??""}/></label><label>Barkod<input name="barcode" maxLength={80} defaultValue={old?.barcode??""}/></label><label>Azalma eşiği<input name="low_threshold" type="number" min="0" step="0.01" defaultValue={old?.low_threshold??""}/></label><label><input name="active" type="checkbox" defaultChecked={old?.active??true}/>Aktif</label><label><input name="track_quantity" type="checkbox" disabled={!!editing} defaultChecked={old?.track_quantity??true}/>Miktar takibi</label><label><input name="lot_required" type="checkbox" defaultChecked={old?.lot_required??false}/>Kullanımda lot zorunlu</label>
 </>:mode==="POLICY"?<><label>Negatif stok<select name="negative_policy" defaultValue={data.settings.negative_policy}><option value="BLOCK_NEGATIVE">Engelle</option><option value="WARN_NEGATIVE">Açık uyarıyla izin ver</option></select></label><p>Yetersiz stok teknik oturumu değiştirmez. Politika değişikliği ve negatif hareketler denetlenir.</p></>:<>
 <label>Ürün<select required value={formItem} onChange={e=>setFormItem(e.target.value)}>{data.items.filter(i=>i.active).map(i=><option key={i.id} value={i.id}>{i.display_name} · {units[i.inventory_unit]}</option>)}</select></label>
 {mode==="LOT_SAVE"?<><label>Lot numarası<input name="lot_number" required maxLength={80}/></label><label>Batch numarası<input name="batch_number" maxLength={80}/></label><label>Son kullanım<input name="expiry_date" type="date"/></label><label>Açılış tarihi<input name="opened_at" type="datetime-local"/></label><label>Teslim alma tarihi<input name="received_at" type="datetime-local" required/></label></>:<>
 <label>Lot<select name="lot_id"><option value="">Lot seçilmedi</option>{data.lots.filter(l=>l.stock_item_id===formItem).map(l=><option key={l.id} value={l.id}>{l.lot_number} · {l.on_hand}</option>)}</select></label><label>{mode==="COUNT_CREATE"?"Ölçülen miktar":"Miktar"}<input name="quantity" type="number" min={mode==="OPENING"||mode==="COUNT_CREATE"?0:0.01} step="0.01" required/></label>{mode!=="COUNT_CREATE"&&<><label>Etkin tarih<input name="occurred_at" type="datetime-local" required/></label><label>Referans<input name="reference" maxLength={160}/></label></>}
 </>}</>}
 <label className="stock-span">Gerekçe<textarea name="reason" required minLength={1} maxLength={2000}/></label><div className="stock-span stock-toolbar"><button className="button" disabled={busy||!permitted(stockPermission(mode))}>Kaydet</button><button type="button" className="button button-secondary" onClick={()=>setMode(null)}>Vazgeç</button></div></form></SalonCard>}
 <SalonCard title={item?"Ürün özeti":"Ürün listesi"}><div className="stock-table"><table><thead><tr><th>Ürün / eşleme</th><th>Miktar</th><th>Durum</th><th>İşlem</th></tr></thead><tbody>{data.items.map(i=><tr key={i.id}><td data-label="Ürün / eşleme"><button className="text-link" onClick={()=>{filters.current={query:"",offset:0,selected:i.id,traceLot:""};setSelected(i.id);setTraceLot("");setOffset(0);void load();}}>{i.display_name}</button><small>{i.sku??"SKU yok"} · {i.source==="SALON_CUSTOM_OPERATIONAL_PRODUCT"?"Operasyon ürünü": "Doğrulanmış katalog referansı"}</small></td><td data-label="Miktar">{i.on_hand===null?"Bilinmiyor":`${i.on_hand.toLocaleString("tr-TR")} ${units[i.inventory_unit]}`}</td><td data-label="Durum"><span className="salon-badge" data-state={i.stock_status}>{statuses[i.stock_status]}</span>{i.stock_sync_status==="RETRY_REQUIRED"&&<small>Kullanım senkronu gerekli</small>}</td><td data-label="İşlem">{permitted("stock.manage_items")&&<button className="text-link" onClick={()=>open("ITEM_SAVE",i.id,i.id)}>Düzenle</button>}</td></tr>)}</tbody></table></div>{!data.items.length&&<p>Stok kartı bulunamadı. Örnek ürün veya bakiye oluşturulmaz.</p>}{!selected&&<div className="stock-toolbar"><button className="button button-secondary" disabled={offset===0} onClick={()=>{const n=Math.max(0,offset-50);filters.current.offset=n;setOffset(n);void load();}}>Önceki</button><span>{offset+1}–{offset+data.items.length} / {data.total_items}</span><button className="button button-secondary" disabled={data.items.length<50||offset>=9950} onClick={()=>{filters.current.offset=offset+50;setOffset(offset+50);void load();}}>Sonraki</button></div>}</SalonCard>
 <div className="stock-columns"><SalonCard title="Hareket defteri"><p>Son 100 hareket. Kullanım, hazırlanan ham bileşeni içerir; atık ikinci kez düşülmez.</p><div className="stock-table"><table><thead><tr><th>Tarih / gerekçe</th><th>Tür</th><th>Miktar</th><th>Kaynak</th></tr></thead><tbody>{data.movements.map(m=><tr key={m.id}><td data-label="Tarih / gerekçe">{new Date(m.occurred_at).toLocaleString("tr-TR")}<small>{m.reason}</small><small>{m.reference}</small><small>Kaydeden: {m.recorded_by_name??m.recorded_by.slice(0,8)}</small></td><td data-label="Tür">{m.movement_type}</td><td data-label="Miktar">{m.quantity_delta} {units[m.unit]}</td><td data-label="Kaynak">{m.source_session_id&&m.source_client_id?<Link href={`/workspace/live-sessions?client_id=${m.source_client_id??""}&session_id=${m.source_session_id}`}>Canlı oturum</Link>:m.source_session_id?<span>Teknik kullanım</span>:permitted("stock.adjust")&&!m.reversal_of&&!data.movements.some(r=>r.reversal_of===m.id)&&<button className="text-link" disabled={busy} onClick={()=>{const reason=window.prompt("Ters kayıt gerekçesi");if(reason)void save({type:"REVERSAL",mutation_id:crypto.randomUUID(),movement_id:m.id,reason});}}>Ters kayıt</button>}</td></tr>)}</tbody></table></div>{!data.movements.length&&<p>Henüz hareket yok.</p>}</SalonCard>
 <OperationalActionBoundary domain="STOCK" permissions={ctx?.permissions??[]}><SalonCard title="Stok aksiyon merkezi"><p>Bu uyarılar stok işlemlerine yönlendirir. Teknik risk veya maliyet hesabı üretmez.</p><ul>{data.actions.map(a=><li key={a.key}>{({LOW_STOCK:"Azalan stok",OUT_OF_STOCK:"Tükenen stok",USAGE_RECONCILIATION_REQUIRED:"Malzeme mutabakatı gerekli",UNIT_MAPPING_REQUIRED:"Birim eşlemesi gerekli",PRODUCT_MAPPING_REQUIRED:"Ürün eşlemesi gerekli",EXPIRING_SOON:"Son kullanım yaklaşıyor",EXPIRED:"Son kullanım geçti",STOCK_SYNC_FAILED:"Stok senkronu başarısız"})[a.kind]}{a.source_domain==="stock_item"&&<> · <a href={`/workspace/stock?item_id=${a.source_id}`}>Ürünü aç</a></>}</li>)}</ul>{data.items.filter(i=>["LOW","OUT"].includes(i.stock_status)).map(i=><div className="stock-action" key={i.id}><strong>{i.display_name}</strong><span>{statuses[i.stock_status]}</span>{permitted("stock.receive")&&<button className="text-link" onClick={()=>open("RECEIPT",i.id)}>Stok girişi</button>}</div>)}
 {data.events.map(e=><div className="stock-action" key={e.id}><strong>{e.status==="FAILED"?"İşlenemeyen kullanım":"Bekleyen kullanım"}</strong><p>{errors[e.error_code??""]??"Sunucu stok kuyruğunda işlenmeyi bekliyor."}</p><small>{e.source_domain} · deneme {e.attempts}</small>{permitted("stock.adjust")&&<><label>Gerçek lot<select value={eventLots[e.id]??""} onChange={x=>setEventLots({...eventLots,[e.id]:x.target.value})}><option value="">Lot seçilmedi</option>{data.lots.map(l=><option key={l.id} value={l.id}>{l.lot_number}</option>)}</select></label><button className="button button-secondary" disabled={busy} onClick={()=>void save({type:"PROCESS",mutation_id:crypto.randomUUID(),event_id:e.id,lot_id:eventLots[e.id]||null})}>Yeniden işle</button></>}</div>)}
 {data.lots.filter(l=>l.expiry_status!=="UNKNOWN_OR_CURRENT").map(l=><p key={l.id}>{l.lot_number} · {l.expiry_status==="EXPIRED"?"Son kullanım geçti":"Son kullanım yaklaşıyor"}</p>)}{!data.events.length&&!data.actions.length&&<p>Açık stok uyarısı yok.</p>}</SalonCard></OperationalActionBoundary></div>
 <SalonCard title="Fiziksel sayımlar">{data.counts.map(c=><div className="stock-action" key={c.id}><strong>{new Date(c.created_at).toLocaleString("tr-TR")} · {c.status==="DRAFT"?"Taslak":"Onaylandı"}</strong><p>{c.reason}</p>{c.lines.map((l,n)=><small key={n}>Defter: {l.ledger_quantity} · Ölçülen: {l.counted_quantity}</small>)}{c.status==="DRAFT"&&permitted("stock.count")&&<button className="button button-secondary" disabled={busy} onClick={()=>void save({type:"COUNT_CONFIRM",mutation_id:crypto.randomUUID(),id:c.id,reason:"Fiziksel sayım sonucunu doğrulayıp farkı kaydet"})}>Sayımı onayla</button>}</div>)}{!data.counts.length&&<p>Henüz fiziksel sayım yok.</p>}</SalonCard>
 <SalonCard title="Lot ve ürün izlenebilirliği"><div className="stock-table"><table><thead><tr><th>Lot / batch</th><th>Miktar</th><th>Son kullanım</th><th>İzlenebilirlik</th></tr></thead><tbody>{data.lots.map(l=><tr key={l.id}><td data-label="Lot / batch">{l.lot_number}<small>{l.batch_number??"Batch bilinmiyor"}</small></td><td data-label="Miktar">{l.on_hand??"Bilinmiyor"}</td><td data-label="Son kullanım">{l.expiry_date??"Bilinmiyor"}</td><td data-label="İzlenebilirlik">{permitted("live_session.view")&&permitted("clients.read")&&<button className="text-link" onClick={()=>{filters.current.traceLot=l.id;setTraceLot(l.id);void load();}}>Oturumları gör</button>}</td></tr>)}</tbody></table></div>{data.trace&&<div><h3>Lotla kaydedilmiş oturumlar</h3>{data.trace.map(t=><p key={t.session_id}><Link href={`/workspace/live-sessions?client_id=${t.client_id}&session_id=${t.session_id}`}>Canlı oturum</Link> · <Link href={`/workspace/clients/${t.client_id}`}>Müşteri</Link>{t.appointment_id&&<> · <Link href={`/workspace/appointments/${t.appointment_id}`}>Randevu</Link></>}</p>)}{!data.trace.length&&<p>Bu lotla kaydedilmiş kullanım yok.</p>}</div>}<p>Lot seçilmediyse geçmiş kullanım için lot tahmin edilmez. Teknik geçmiş değişmez.</p></SalonCard>
 <p className="muted">Başlangıç: {new Date(data.settings.enabled_at).toLocaleString("tr-TR")} · Önceki oturumlar PRE_STOCK_HISTORY / NOT_IMPORTED. Transfer, rezervasyon ve maliyet hesabı sonraki kapsamda.</p>
 </>}</main></SalonFrame>;
}
