export const hairTr = {
 title: "Saç Pasaportu", overview: "Genel bakış", clients: "Müşteriler", navigation: "Müşteri bölümleri", readOnly: "Teknik profil · Salt okunur",
 core: "Genel teknik durum", regions: "Teknik bölgeler", observations: "Teknik gözlemler", tests: "Fiziksel testler", history: "Teknik geçmiş",
 intro: "Saçın mevcut değerlendirmesi, bölgesel farklılıkları ve kayıtlı teknik geçmişi.",
 emptyTitle: "Saç Pasaportu henüz oluşturulmadı", empty: "Bu müşterinin teknik profili henüz kayıtlı değil. Oluşturulduğunda değerlendirmeler ve geçmiş burada görüntülenecek.",
 noObservations: "Henüz teknik gözlem kaydı yok.", observationHint: "Genel durum ve bölgelere ait teknik gözlemler en yeniden eskiye gösterilir.", noTests: "Henüz fiziksel test kaydı yok.", noHistory: "Henüz teknik geçmiş kaydı yok.", noRegions: "Henüz teknik bölge kaydı yok.",
 archived: "Arşivlenen müşteri · Geçmiş kayıtlar görüntüleniyor", updated: "Son güncelleme", whole: "Saçın tamamı", evidence: "Kanıt ve kaynak", confidence: "Kayıtlı güven düzeyi", noConfidence: "Güven düzeyi belirtilmedi", verified: "Profesyonel doğrulaması kayıtlı", performer: "Uygulayan kişi sistemde kayıtlı", recorded: "Kayıt zamanı", observed: "Gözlem zamanı", relevant: "Geçerlilik tarihi", product: "Ürün", salon: "Atfedilen salon", professional: "Atfedilen uzman", correction: "Önceki kaydın düzeltmesi", approximate: "Yaklaşık", unknownDate: "Tarih bilinmiyor", previous: "Önceki", next: "Sonraki", page: "Sayfa", unavailable: "Saç Pasaportu gösterilemiyor.", retry: "Yeniden dene", loading: "Teknik profil için erişiminiz doğrulanıyor…", partial: "Eksik bilgiler değerlendirme yapıldıkça tamamlanır.",
 states: { KNOWN: "Kayıtlı", UNKNOWN: "Bilinmiyor", NOT_ASSESSED: "Henüz değerlendirilmedi", NOT_APPLICABLE: "Uygulanamaz", ASSESSED: "Gözlem kayıtlı", UNVERIFIED: "Doğrulanmamış bilgiler", ACTIVE: "Aktif", ARCHIVED: "Arşivde" },
 fields: { natural_level: "Doğal seviye", perceived_level: "Görünür seviye", grey_ratio: "Beyaz oranı", thickness: "Tel kalınlığı", density: "Yoğunluk", porosity: "Gözeneklilik", elasticity: "Esneklik", tone: "Ton / yansıma", cosmetic_color_history: "Kozmetik renk geçmişi", bleach_history: "Açıcı geçmişi", chemical_history: "Kimyasal işlem geçmişi", technical_notes: "Teknik notlar", integrity_notes: "Saç bütünlüğü notları" },
 values: { FINE: "İnce", MEDIUM: "Orta", COARSE: "Kalın", LOW: "Düşük", HIGH: "Yüksek", NORMAL: "Normal" },
 regionTypes: { ROOT: "Dip", MID_LENGTHS: "Orta Uzunluklar", ENDS: "Uçlar", FACE_FRAME: "Yüz çevresi", CROWN: "Tepe", NAPE: "Ense", BANDED_AREA: "Bantlı alan", BLEACHED_AREA: "Açılmış alan", HIGHLIGHTED_AREA: "Röfleli alan", CUSTOM: "Özel bölge" },
 sources: { AI_ESTIMATE: "AI Tahmini", PROFESSIONAL_VERIFIED: "Profesyonel Doğrulaması", PHYSICAL_TEST: "Fiziksel Test", HISTORICAL: "Geçmiş Kayıt", IMPORTED_UNVERIFIED: "İçe Aktarıldı / Doğrulanmadı" },
 testTypes: { POROSITY: "Gözeneklilik testi", ELASTICITY: "Esneklik testi", STRAND: "Tutam testi" },
 categories: { COLOR: "Saç boyama", BLEACH_LIGHTENING: "Açıcı / renk açma", TONER_GLOSS: "Toner / parlaklık", PERM: "Perma", RELAXER_STRAIGHTENING: "Gevşetme / düzleştirme", KERATIN_SMOOTHING: "Keratin / pürüzsüzleştirme", OTHER_CHEMICAL: "Diğer kimyasal işlem" },
 errors: { FORBIDDEN: "Saç Pasaportunu görüntüleme yetkiniz yok.", CLIENT_NOT_FOUND: "Müşteri bulunamadı veya erişim izniniz yok.", MEMBERSHIP_REVOKED: "Çalışma alanı üyeliğiniz kaldırıldı.", MEMBERSHIP_REQUIRED: "Etkin çalışma alanı üyeliği gerekiyor.", TENANT_CONTEXT_INVALID: "Çalışma alanınız değişti. Yeniden seçim yapın.", SESSION_EXPIRED: "Oturumunuz sona erdi.", UNAUTHENTICATED: "Oturum açmanız gerekiyor.", NETWORK_ERROR: "Bağlantı kurulamadı. Yeniden deneyin.", VALIDATION_FAILED: "Teknik profil isteği doğrulanamadı." },
} as const;

export const hairEditTr = {
 editable: "Teknik profil · Düzenlenebilir",
 create: "Hair Passport Oluştur", editCore: "Genel durumu düzenle", editRegion: "Bölgeyi düzenle", addRegion: "Teknik bölge ekle",
 save: "Kaydet", saving: "Kaydediliyor…", saved: "Değişiklikler kaydedildi ve güncel bilgiler yüklendi.", cancel: "Vazgeç", reload: "Güncel bilgileri yükle", unchanged: "Henüz değişiklik yok.", dirty: "Kaydedilmemiş değişiklikler var.",
 createTitle: "Saç Pasaportu oluştur", coreTitle: "Genel teknik durumu düzenle", regionTitle: "Teknik bölgeyi düzenle", newRegionTitle: "Teknik bölge ekle",
 state: "Bilgi durumu", value: "Değer", noChange: "Değiştirme", fieldHelp: "Bilgi durumunu seçin. Kayıtlı seçildiğinde değer girilmelidir; diğer durumlarda değer gönderilmez.",
 percentHelp: "0–100 arasında yüzde girin.", levelHelp: "1–10 arasında seviye girin.", regionType: "Bölge türü", regionLabel: "Bölge adı", customHelp: "Özel bölge için ad zorunludur (en çok 120 karakter).",
 optionalFields: "Teknik alanları şimdi doldurabilir veya Pasaportu boş oluşturup sonra tamamlayabilirsiniz.", optionalRegion: "Bu bölgenin teknik alanlarını şimdi doldurabilir veya sonra düzenleyebilirsiniz.",
 validation: { required: "Bu alan için bir değer girin.", range: "Değer izin verilen aralığın dışında.", invalid: "Teknik bilgi doğrulanamadı. Alanları kontrol edin.", custom: "Özel bölge için geçerli bir ad girin.", unchanged: "Kaydedilecek değişiklik yok." },
 errors: { HAIR_PASSPORT_ALREADY_EXISTS: "Saç Pasaportu başka bir işlemde oluşturuldu. Güncel bilgileri yükleyin.", HAIR_PASSPORT_NOT_FOUND: "Saç Pasaportu bulunamadı. Güncel bilgileri yükleyin.", HAIR_REGION_NOT_FOUND: "Teknik bölge bulunamadı. Güncel bilgileri yükleyin.", HAIR_REGION_ALREADY_EXISTS: "Bu türde teknik bölge zaten var.", INVALID_TECHNICAL_STATE: "Teknik değerler geçersiz. Alanları kontrol edin.", FORBIDDEN: "Bu işlemi yapma yetkiniz yok. Güncel erişiminiz doğrulanacak.", MEMBERSHIP_REVOKED: "Çalışma alanı üyeliğiniz kaldırıldı.", TENANT_CONTEXT_INVALID: "Çalışma alanı değişti. Yeniden seçim yapın.", CONFLICT: "Hair Passport başka bir işlemde güncellendi. Güncel bilgileri yükleyip değişikliklerinizi tekrar kontrol edin.", CLIENT_ARCHIVED: "Arşivlenen müşteri için değişiklik yapılamaz.", SESSION_EXPIRED: "Oturumunuz sona erdi.", UNAUTHENTICATED: "Oturum açmanız gerekiyor.", NETWORK_ERROR: "Bağlantı kurulamadı. Aynı isteği yeniden deneyebilirsiniz.", VALIDATION_FAILED: "İstek doğrulanamadı. Alanları kontrol edin." },
} as const;

export const hairObservationTr = {
 add: "Yeni Gözlem Ekle", title: "Yeni teknik gözlem", field: "Teknik alan", region: "Gözlem bölgesi",
 whole: "Saçın tamamı", state: "Bilgi durumu", value: "Gözlenen değer", confidence: "Gözleme duyulan güven (%)",
 confidenceHelp: "İsteğe bağlıdır. Bu oran saç sağlığını veya riski ölçmez; yalnızca bu gözlemin güven düzeyini belirtir.",
 verify: "Bu değerlendirmeyi profesyonel gözlemim olarak doğruluyorum.",
 saved: "Gözlem kaydedildi; güncel Saç Pasaportu yüklendi.",
 validation: { field: "Teknik alanın değerini ve bilgi durumunu kontrol edin.", value: "Bu alan için geçerli bir değer girin.", state: "Bu bilgi durumu alan için kullanılamaz.", verified: "Kaydetmeden önce profesyonel gözleminizi doğrulayın.", confidence: "Güven düzeyi 0–100 arasında olmalıdır." },
 errors: { HAIR_PASSPORT_NOT_FOUND: "Saç Pasaportu bulunamadı. Güncel bilgileri yükleyin.", HAIR_REGION_NOT_FOUND: "Seçilen bölge artık bulunamıyor. Güncel bilgileri yükleyin.", INVALID_OBSERVATION: "Teknik gözlem geçersiz. Alanları kontrol edin.", INVALID_EVIDENCE: "Profesyonel doğrulama bilgisi geçersiz.", INVALID_CONFIDENCE: "Güven düzeyi geçersiz.", FORBIDDEN: "Gözlem ekleme yetkiniz yok. Erişiminiz yeniden doğrulanacak.", MEMBERSHIP_REVOKED: "Çalışma alanı üyeliğiniz kaldırıldı.", TENANT_CONTEXT_INVALID: "Çalışma alanı değişti. Yeniden seçim yapın.", CLIENT_ARCHIVED: "Arşivlenen müşteri için gözlem eklenemez.", CONFLICT: "Saç Pasaportu başka bir işlemde güncellendi. Güncel bilgileri yükleyip gözleminizi tekrar kontrol edin.", SESSION_EXPIRED: "Oturumunuz sona erdi.", UNAUTHENTICATED: "Oturum açmanız gerekiyor.", NETWORK_ERROR: "Bağlantı belirsiz. Aynı gözlemi yeniden kaydetmeyi deneyebilirsiniz.", VALIDATION_FAILED: "İstek doğrulanamadı. Alanları kontrol edin." },
} as const;
